### ISSUE TITLE
Link To "Component - Seeders" Section of Docs Is Broken

### ISSUE THREAD

**Issue by Funso-Popoola** [apiato/apiato#121]
The link to the Component Seeders section of the docs at [http://apiato.io/D.components/seeders/](http://apiato.io/D.components/seeders/) returns no result i.e. ERR_EMPTY_RESPONSE.

**Comment by Mahmoudz** [comment]
Hi @Funso-Popoola, do you mean this link is not working!?

**Comment by Funso-Popoola** [comment]
Yes, I can't seem to access that particular part of the documentation. I'm not sure whether it's from me or the site. That's because I could visit other sections of the doc.

**Comment by Mahmoudz** [comment]
When I click the link it just work for me!! try cleaning your browser cache!

<img width="1440" alt="screen shot 2017-03-25 at 1 16 35 pm" src="https://cloud.githubusercontent.com/assets/1983984/24324478/520a22c0-115d-11e7-83d5-ae8e0cd9ba5e.png">

**Comment by johannesschobel** [comment]
works perfectly for me..
