### ISSUE TITLE
Container generator and Chat

### ISSUE THREAD

**Issue by objectorientedninja** [apiato/apiato#122]
Any Update on the Container generator? Very impressive work!
also the link on gitter for chat is showing a 404

**Comment by Mahmoudz** [comment]
@objectorientedninja Hello, I was supposed to release that unfinished generator last Monday, but too busy, and I don't think I will be able to even work on it next week. So I'm gonna release it today for sure, as it is, to be continued later by me or other contributors. I will write some description of what's done and how to continue... 

For the chat I guess the link broke after renaming the repo, and messing with Gitter, I wanna give a chance to Slack now for this project would you mind testing it with me!? here's the link https://apiato.slack.com/shared_invite/MTYyMzk3MzIzNjIxLTE0OTA5MDE0NTMtOTljOGU1NmFlZQ just let me know if you were able to join the apiato team on slack.. If it works I will switch from Gitter to Slack immediately.

Thanks,
