### ISSUE TITLE
Feature: Internal Error Codes table

### ISSUE THREAD

**Issue by Mahmoudz** [apiato/apiato#139]
Should return custom error code in addition to the HTTP status code, to inform the users about the error status (better for frontend devs to rely on error code "1234" instead of text message "like: auth failed or so.."). 

Error Codes and description will be added in the Header.md of the Docs generator, so it will be available when generating the API docs autoamtically.

**Comment by johannesschobel** [comment]
The PR #306 (as well as the PR in `apiato/core` ) is a step in this direction!
