### ISSUE TITLE
Feature: Support xml and json responses

### ISSUE THREAD

**Issue by Mahmoudz** [apiato/apiato#141]
transformers should support multiple response formats, users can control what response format they want from the HTTP header or in URL (../resource.xml) "defaulting to JSON".

**Comment by nasrulhazim** [comment]
A reference for this part - [Orchestra Facile Component](https://orchestraplatform.com/docs/latest/components/facile)

**Comment by johannesschobel** [comment]
If you want to output your data as `xml` instead, you may use
```
composer require spatie/array-to-xml
```

Respective package allows to easily transform an array to xml (as the name implies). Handy thing here is, that the `Transformers` already produce an `array`. In this case, you would need to write your own `Serializer` ( https://fractal.thephpleague.com/serializers/ ) for `Fractal` and use your newly created `XMLDataSerializer`..

Hope this helps..
