### ISSUE TITLE
Integration with rinvex/fort

### ISSUE THREAD

**Issue by rogerapras** [apiato/apiato#144]
It is possible to change the apiato to use the fort package https://github.com/rinvex/fort.
What is the difficulty I would have to do?

**Comment by Mahmoudz** [comment]
@rogerapras in general everything is possible. Can you explain why should we replace the current code with that package? Since we do have most of the features, each coming from different package or built in house.

**Comment by rogerapras** [comment]
Hello
I was able to make the change I needed
I changed the package because this one informed by me has more resources
But there is no need for you to change the structure ... after a better study of the code and structure I find it very easy to carry out the replacement of the authorization package

Thank you for responding

**Comment by Mahmoudz** [comment]
@rogerapras sure you're more than welcome :)

**Comment by rogerapras** [comment]
Grateful
Thank you for doing this excellent job with the apiato.
On integration the only problem I had was with the version of the package "laravel / socialite", after I update the version worked everything perfectly.
If I encounter any problems I will be sharing

**Comment by Omranic** [comment]
*apiato/apiato* is really a promising project, I didn't try it yet, but planing to do soon and integrate it with our *rinvex/fort* package and others. Happy to see you @rogerapras already have done that, and will appreciate publishing your steps to make it work peacefully. That would help both package communities 😉
