### ISSUE TITLE
Route Specific Throttling / Rate Limiting

### ISSUE THREAD

**Issue by twcarefoot** [apiato/apiato#145]
I have a route that I need to apply a custom rate limit and expiry to. 

All limits are being overridden by the config variable "api.limit".  (see RoutesLoaderTrait.php)

Is there anyway to achieve this currently?

Dingo/api currently allows for this. Here's a link for reference
https://github.com/dingo/api/wiki/Rate-Limiting#route-specific-throttling

**Comment by Mahmoudz** [comment]
@twcarefoot have you tried grouping (`Route::group..`) your routes and using your throttling rules `'limit' => 100`? This might override the the default rate limiting. 

However if it didn't worked or you don't want the default global throttling at all. You can comment out [this line](https://github.com/apiato/apiato/blob/master/app/Ship/Engine/Loaders/RoutesLoaderTrait.php#L96) and use your own throttling from anywhere (RoutesLoaderTrait is a global place everything here applies to all routes. Or from your own Routes files and grouping).
