### ISSUE TITLE
Any way to use this without changing /etc/hosts ?

### ISSUE THREAD

**Issue by shahzeb1** [apiato/apiato#147]
I am currently serving apiato via `$ artisan serve` and I see this when I visit localhost: 

![image](https://cloud.githubusercontent.com/assets/1383831/25573447/4fb59f36-2dfa-11e7-8c8c-7b1a88795db8.png)

How can I visit the "api" portion of the website? Since the website is being served on "http://127.0.0.1:8000/" there's no way for me to change the subdomain here...

**Comment by llstarscreamll** [comment]
Hi, what about adding a prefix to all your api routes?

**Comment by shahzeb1** [comment]
That's a good solution. So I'll just group all the API routes into a prefix-subgroup. Will report back with findings. 😄
