### ISSUE TITLE
Http/ResponseHeadersMiddleware.php issues

### ISSUE THREAD

**Issue by hezhiying** [apiato/apiato#148]
line:34       
 if(!$request->header('accept') === $contentType){
       throw new MissingeptHeaderException();
 }

Do not understand is not a problem
It should not be this: 

 if($request->header('accept') !== $contentType){
       throw new MissingeptHeaderException();
 }

**Comment by Mahmoudz** [comment]
@hezhiying is `!$request->header('accept') === $contentType` causing a problem on your end?

**Comment by hezhiying** [comment]
Sorry ! I do not understand what conditions are true.

**Comment by ninggf** [comment]
the priority of '!' is higher than '===' (detail on [php.net](http://php.net/manual/en/language.operators.precedence.php)), so the code bellow will not work correctly:
```php
if(!$request->header('accept') === $contentType){
throw new MissingeptHeaderException();
}
```
