### ISSUE TITLE
How to upgrade to newer versions of Apiato ?

### ISSUE THREAD

**Issue by rmkpatchaa** [apiato/apiato#155]
Hi, 
I don't see anywhere in the documentation a guide to upgrade to newer versions of apiato.
I am using **V4.0.2** and want to upgrade to **V4.1.0**

Thanks.

**Comment by johannesschobel** [comment]
As far as i have understood, you can simply pull overwrite everything that has been placed in `app\Ship`.. But i am not entirely sure about this..

**Comment by rmkpatchaa** [comment]
Hmmm it is not that simple ...
I've create my application using composer create-project command. So there is no reference to this repository anymore in my project.
I have tried some git tricks (patch, rebase, ...) but without success.

**Comment by rmkpatchaa** [comment]
The "problem" is not an apiato problem but a composer  one (if we can call it problem).
So I have managed to create a solution that can be found here : https://gist.github.com/rmkpatchaa/991152b85ca8edca69115f214bd569ae
Your remarks are welcome.

**Comment by envision** [comment]
@rmkpatchaa what was the solution? That gist link gives 404...

**Comment by rmkpatchaa** [comment]
@envision sorry the link is here : https://gist.github.com/rmkpatchaa/f5949c4564cd504f72f110e6cbbd015f

It should work in most of the situations. Make sure to commit your actual changes so you can revert if something goes wrong :)

**Comment by envision** [comment]
Here's a related solution when setting up a new project. It seems with Apiato it's more important to have the changes in app files pulled over periodically as this project is about the app files architecture and infrastructural functionalities: https://stackoverflow.com/questions/22275538/setting-up-laravel-project-with-git

**Comment by envision** [comment]
Encountered a problem with that previous StackOverflow solution... When creating project with this command:

    composer create-project apiato/apiato api --prefer-dist

There isn't git repo available after the command unlike the solution's workflow assumes. Does creating from the laravel framework's repo do something different then?

There really should be info on updating the app files in the documentation! Or is it that there are some special composer configs already in place that are having Apiato's own containers updated with composer update?

**Comment by rmkpatchaa** [comment]
First of all, if you do like the stackoverflow method, you will pull all the commits history from apiato. I don't think you want that.

I think this is not an Apiato "problem" but a problem with how composer works.
When you create-project with composer, it juste creates a directory and copies a file structure to it. (with dependancies like laravel) in the composer.json.

As apiato is not in your dependency graph, you can now just pull updates, like you could do with Laravel.
On my project, I didn't deeply modify the apiato default files, as I created a new container (folder) in the App/Containers directory. So the update went smoothly.

You can use the advantage of git to see what have been modified if you use the method I gave above and revert back some parts of your application if you had some changes in the apiato files.
Hope it helps.
