### ISSUE TITLE
[Proposal] Dependencies for Containers

### ISSUE THREAD

**Issue by johannesschobel** [apiato/apiato#161]
Hi guys,

recently I developed a `Team` container, which allows users to organize in teams.. I would be willing to share this container. However, in this process, i realized that we need some kind of  `composer` file for containers, in order to document the dependencies to other containers (e.g., mine, obviously, depends on the `Authorization` and `User` container)..

Do any of you have some good ideas how to realize this feature?
In my opinion, this could be a regular text file and also include some basic "installation" instructions (e.g., you may need to add specific Traits to other models in order to apply functions)

Cheers

**Comment by Mahmoudz** [comment]
@johannesschobel I'm excited to see what people will say about that, I've tried couple things in the past:
- Central config file that holds details about the relations between containers. Not great idea! as there was always central place knowing how to configure the containers, was also used to register config files and service providers... 
- Requiring containers as dependencies in the `composer.json` of each container. But removed that as I got tired from pushing to over 20 container whenever I need to do global changes. And the second reason to removing that, was the little hack I used to do to prevent `composer update` from deleting and override my containers in the `containers` folder "not the `vendor`" which wasn't efficient. 
- I think the easies to do but not the best is to include a readme file in each Container specifying the dependencies between each container and the others who depends on.

Looking forward for some real solutions there, maybe creating something like `apiato.json` which defines the dependencies on other containers and their versions same way like composer. but internally, and that little system should know where to find the container to download it..

**Comment by johannesschobel** [comment]
Hey,
my initial thought-process was to create a readme file for each container which describes potential dependencies to other containers.. For example, in my `Team` container, I would add a dependency to the `User` and `Authorization` container..

However, currently i am not sure, which information should be put inside this readme file.. I will think about it and (maybe) propose a `readme.md` file within my `Team` container..

Cheers

**Comment by johannesschobel** [comment]
I have implemented a `container-installer` that allows to install and update containers from 3rd party members.. please see PR #172 for more details!
