### ISSUE TITLE
MissingJSONHeaderException in ResponseHeadersMiddleware.php line 36

### ISSUE THREAD

**Issue by silgon** [apiato/apiato#164]
Hello,
I'm new with laravel, I'm trying to install it with docker. However, I'm finding a problem with the api part. The image depicting my problem is the following:

![test](https://cloud.githubusercontent.com/assets/901061/26325084/cbd47ad2-3f35-11e7-93bb-b04a0c69fc79.png)

I appreciate any help, I couldn't find any answers online.

**Comment by Mahmoudz** [comment]
Hi @silgon,

You need to pass, `Accept` Header in the request and set it to `application/json`.

**Comment by silgon** [comment]
Thanks for the answer! I just tested it. Sorry for the basic question. =)
