### ISSUE TITLE
API version in headers?

### ISSUE THREAD

**Issue by hxnk** [apiato/apiato#167]
Hi all / @Mahmoudz,

Just discovered this framework and Porto pattern... Really like the approach!

I saw that Apiato uses the URI to determine the API version. 

Are there any plans of adding the option to have the API version in the headers, or does anyone have any experience with adding this functionality themselves? I have an existing project that I would like to refactor/port to use this framework/pattern, but it needs to have the API version in the headers...

Any suggestions on how to approach this would be greatly appreciated :)

Thx!

**Comment by Mahmoudz** [comment]
@hxnk Hi, remove the `prefix` from the `loadApiRoute` function in `RoutesLoaderTrait` file, to remove the versioning feature from the API. And then implement your versioning in the header anyway you like.

**Comment by Mahmoudz** [comment]
http://apiato.io/miscellaneous/faq/#q6
