### ISSUE TITLE
Nested resources example approach needed in docs

### ISSUE THREAD

**Issue by R00118189** [apiato/apiato#173]
I generated post comment and reply containers but am stuck on nested resources, shall the highest lever resource have multiple controllers which use actions from other containers like 
`PostCommentController` in Post container alongside with `PostController` and `CommentReplyController` in Reply container OR `PostCommentReplyController` in Post container.

**Comment by Mahmoudz** [comment]
@R00118189 Hi, I usually have Container per UI. So the Container is always named `Container` with no prefix of the Model name. And that will be used for all the Models of the Container. 

I recommend having 3 Containers (Post, Comment and Reply) each having it's own Controller per UI, disregarding which resource is higher than the other.

Not sure if that answered you, let me know your concerns with that approach. Best,
