### ISSUE TITLE
Unclear where to install exactly when using Laradock

### ISSUE THREAD

**Issue by faphdev** [apiato/apiato#174]
Hello,
Thanks for offering this project.
The instructions assume that you already know how to install...
It does not say whether or not to install within Lardock, in a sub-directory or parent directory.
Thank you.

**Comment by Mahmoudz** [comment]
@faphdev both can work, it's optional. All the details are in the installation steps of the Laradock documentation.

Choose the setup the best suits your needs:

- A) Setup for Single Project
  - A.1) Already have a PHP project
  - A.2) Don’t have a PHP project yet
- B) Setup for Multiple Projects
