### ISSUE TITLE
Restrict access for viewing internal API doc

### ISSUE THREAD

**Issue by ux-engineer** [apiato/apiato#176]
Documentation mentions on how to access internal / private API documentation page:

> Private (internal) API at http://apiato.dev/api/private/documentation/.

Shouldn't there also be snippets or at least a mention that this route should have restricted access?

**Comment by Mahmoudz** [comment]
@envision absolutely this is something was willing to implement. The private API should be protected and give access to specific people. Does anyone has any cool idea whats the best way to do it?

**Comment by envision** [comment]
As this a web route, perhaps there should be a new default permission, i.e. 'can-access-private-documentation', that is added by default for the admin role. If a user tries to get to that page without this new permission the request would get redirected to public API doc page instead. How would that sound?

**Comment by Globulard** [comment]
Any news on this?

**Comment by Mahmoudz** [comment]
@Globulard not yet. If you have some free time feel free to implement it and share it with us. Best,

**Comment by mlfthedifferent** [comment]
May anyone can check this idea. [link to >> Modify documentation generator config to Restrict access for viewing …](https://github.com/mlfthedifferent/mlfapiato/commit/4f6df92e93e8ed1411588c03e52a335a94a1bd9c)
