### ISSUE TITLE
Sensible defaults for tokens' expiration time & add dynamically to doc

### ISSUE THREAD

**Issue by envision** [apiato/apiato#177]
By default the generated doc says:

> The Access Token lives for 3650 days, 0 hours, 0 minutes and 0 seconds. (equivalent to 5256000 minutes). While the Refresh Token lives for 600 days, 0 hours, 0 minutes and 0 seconds. (equivalent to 864000 minutes).

First of all this isn't true as env.example has defaults:

```
API_TOKEN_EXPIRES_IN=5256000
API_REFRESH_TOKEN_EXPIRES=5256000
```

I'm going with 10 minutes for token expiration and 10 days for refresh token expiration.

Also it would nice if these values would be reflected dynamically to the documentation from .env file.

**Comment by envision** [comment]
Actually RenderTemplatesTask.php tries to access Config::get('apiato.api.expires-in') ... I don't have that file even I followed the installation guide at http://apiato.io/A.getting-started/installation/ ?

**Comment by envision** [comment]
Ah the problem is that the default installation's config values are in seconds and this doc is configured to showing config values in minutes at least in regarding to this section!

**Comment by envision** [comment]
Now started to think these are in minutes... Modified like so (10minutes and 10 days):

```
API_TOKEN_EXPIRES_IN=10
API_REFRESH_TOKEN_EXPIRES=14400
```

But now the doc show like this, so definitely something weird going on?

> The Access Token lives for 3650 days, 0 hours, 0 minutes and 0 seconds. (equivalent to 5256000 minutes). While the Refresh Token lives for 10 days, 0 hours, 0 minutes and 0 seconds. (equivalent to 14400 minutes).

**Comment by Mahmoudz** [comment]
@envision those values in the docs are actually dynamic. If you're changing the values in `env.example` it won't work you need to change them in the `.env` file. Also try upgrading your code at least this container `app/Containers/Documentation` as I guess there used to be a bug there. Let me know if this solved, of not I'll check it deeply.

**Comment by jackbraj** [comment]
I am also facing similar issue with generated API docs. I just installed the fresh copy in laradock, adjusted some variables in .env, specifically APP_NAME, APP_URL & API_URL.

Then when I generated the documents php artisan apiato:docs it worked but the generated template isn't showing my app name everywhere. Its only showing my configured API_URL in API Overview section, but the actual endpoints (like oauth) still showing apiato.dev.

Also HTML title and page header showing apiato even if I changed the name in .env.

I checked apidoc.json config in Documentation container and it has default values like apiato
I wonder if this should be updated automatically from .env when generating the documents or I should manually supply the values and keep this in .gitignore.

Thanks for your awesome work.

**Comment by envision** [comment]
As a note about the sensible defaults for these expire times... Esben Peterson the author of [Larapi](https://github.com/esbenp/larapi) (by Trade) has written in his article ['A modern REST API in Laravel 5 Part 4: Authentication using Laravel Passport'](https://esbenp.github.io/2017/03/19/modern-rest-api-laravel-part-4/) that he uses 10 minutes / 10 days config.
