### ISSUE TITLE
How does emailing work with Apiato?

### ISSUE THREAD

**Issue by envision** [apiato/apiato#182]
I found only these files related to emailing:

    app/Ship/Email/Abstracts/MailsAbstract.php
    app/Ship/Email/Contracts/MailsInterface.php

This issue seems to point out that previous email examples was taken out for supporting Laravel's new Mailable class instead...how does mails fit to this architecture? How should I use those two files?

https://github.com/apiato/apiato/issues/47

**Comment by Mahmoudz** [comment]
@envision don't worry about them a anymore I've just delete them 685dd274dbcd8404f81e22707f19c5a5a68ea736. Feel free to implement the email anyway you wish according to the Laravel official way of sending emails.
