### ISSUE TITLE
StateKeeperTrait uses 'state' property on Request class

### ISSUE THREAD

**Issue by envision** [apiato/apiato#184]
Currently it is not possible to have a request parameter with name 'state' (as in all comprehensive address details) when StateKeeperTrait populates that propertyname to Request class.

This property is defined in:
app/Ship/Parents/Requests/StateKeeperTrait.php line 29

**Comment by Mahmoudz** [comment]
@envision yes that's correct, as a quick solution remove the usage of `StateKeeperTrait` from the Request class, if you're not relying on it. If you wish to solve this in a proper way would be cool. I'm open to hear your suggestion.

**Comment by nasrulhazim** [comment]
Easiest is to rename to `states` instead of `state` - as the `state` property contained list of data, should be pluralise property name.
