### ISSUE TITLE
[Feature] Dynamic pagination limit setting by query param OR resource specific

### ISSUE THREAD

**Issue by envision** [apiato/apiato#200]
Currently there is only an app wide PAGINATION_LIMIT setting which defaults to 10.

It would nice if the API could offer dynamic pagination limit that the API's consumer could specifically define by adding a query parameter.

Alternatively a resource could perhaps have it's own pagination setting limit value as defined by a property.

Do you see any value in such a feature request?

**Comment by johannesschobel** [comment]
you can simply append `?limit=100` to the request, in order to get `100` resources.
This will, for this one specific request, circumvent the API default PAGINATION_LIMIT..

Or am I missing something?!

**Comment by johannesschobel** [comment]
We discussed this on slack. It is possible to add the `?limit=100` query parameter to a request. THe `limit` parameter can be used in combination with the `page` parameter to get the **next** 100 elements (e.g., by calling `api.com/endpoint?limit=100&page=2`)

However, you need to be sure that the `Repository` which handles the `paginate()` calls the `parent::boot()` in its own `boot()` method!

For example like so:
```php
<?php

namespace App\Containers\Settings\Data\Repositories;

use App\Containers\Settings\Models\Setting;
use App\Ship\Parents\Repositories\Repository;

class SettingRepository extends Repository
{
    // some stuff here

    public function boot()
    {
        parent::boot();
        // probably do more some stuff here ...
    }

   // some other stuff here
}
```

I will add a little section to the apiato docs to clarify how to use the `?limit` parameter.
