### ISSUE TITLE
Requests with a non-existing include parameter should return pruned error response

### ISSUE THREAD

**Issue by envision** [apiato/apiato#203]
## Expected Behavior
When user requests from an endpoint with an include parameter which is not existing, user should get more pruned error response.

## Actual Behavior
Currently the error response reveals my app's internal file structure with it's too detailed error data:

	{
	    "errors": "Oops something went wrong.",
	    "status_code": 400,
	    "message": "call_user_func() expects parameter 1 to be a valid callback, class 'App\\Containers\\MyPrivateContainer\\UI\\API\\Transformers\\MyPrivateResourceTransformer' does not have a method 'includeSomeNonexistentData'",
	    "exception": "ErrorException"
	}

## Steps to Reproduce the Problem
Query an endpoint with `&include=someNonexistentData`.

Tried with a freshly updated project that was merged with current master branch.

**Comment by johannesschobel** [comment]
hey.. stumbled upon the same issue some time ago and put it on my ToDo list. However, as you mentioned it, I will try to fix it sooner than later..

I think, there are 2 approaches - what do you guys think, would be better?!
1) simply `try/catch \Exception` for the `call_user_func()` function call and output a meaningful exception for the client
2) "sanitize" the `include` params to remove all `includes` that are not within the `available/defaultIncludes` of the respective `Transformer`.

I think, the more "handy" approach would be to go for nr. 1, however, nr 2 would be "better". Approach 2 may need to be adapted if the underlying Transformer approach is changed (or if nested includes will be implemented, ...). Nr 1 would be a "safe bet", I think..

Just tell me, what you think, I can add it to my "soon to be submitted PR" to fix this issue ;)

**Comment by envision** [comment]
Initially 2. approach seemed more simpler. It is also a workable solution for the API consumer in mind – if you request an include that isn’t listed in available includes, it just doesn’t do anything.

But 1. approach would be fine also :)

**Comment by johannesschobel** [comment]
Ok, i just looked at the code..
Approach 1. is quite simple to implement (I would go for this).
Approach 2. would be more problematic, because we need to check for each include if it would be allowed (i.e., available). To do so, one need to inspect each `includeX()` method on the transformer to check, what kind of Transformer is used in this method - and get the `availableIncludes` for this one was well.. And so on.. That is quite ugly ;)

Cheers

**Comment by johannesschobel** [comment]
This can be fixed with this PR here https://github.com/thephpleague/fractal/pull/403

**Comment by johannesschobel** [comment]
My PR for the `fractal` package has been closed and was **not** merged.. Unfortunately, they did not see think it is an issue..

**Comment by johannesschobel** [comment]
This issue can be closed if the mentioned PR gets merged!

**Comment by Mahmoudz** [comment]
Closed by #291
