### ISSUE TITLE
Events and Listeners In Apiato

### ISSUE THREAD

**Issue by Funso-Popoola** [apiato/apiato#211]
## Expected Behavior
That one should be able to use either an apiato-specific artisan command or the default laravel artisan command to "event:generate"; "make:event" and "make:listener" and have the Events and Listeners under specified container. Just as we have for Jobs in apiato.

## Actual Behavior
There is no corresponding apiato-specific artisan command for event/listener. Using the laravel artisan commands for events and listeners kinda breaks the PORTO architecture by creating separate `Events` and `Listeners` folder outside the containers inside the `/app` folder.
In fact, running `php artisan event:generate` gives an error as no `EventServiceProvider` was registered in `config/app.php`

## Steps to Reproduce the Problem

  1. php artisan event:generate
  2. [Optional] php artisan make:event UserRegistered
  3. [Optional] php artisan make:listener DispatchWelcomeMessage --event UserRegistered

## Specifications
Well, I use Laradock as my dev environment but I don't think that matters in this case.

  - Apiato Version: current

## Additional Details
I hope to make it work in apiato in such a way that the SOLID principle in the PORTO architecture remains unbroken and I can keep separate concerns in separate Containers and I don't want my use of Events and Listeners to break that since even my Jobs fall in line.

**Comment by johannesschobel** [comment]
it would be quite "easy" to add a `Generator Command` for `Events` and `Listeners`. I could do that - if that is the only thing that is needed ;)

**Comment by Funso-Popoola** [comment]
The `EventGenerator` and `EventHandlerGenerator` actually exist but weren't registered in the `GeneratorsServiceProvider`

**Comment by Funso-Popoola** [comment]
I guess it's more of:

1. Where are events/listeners registered in apiato?
2. Was the omission of EventServiceProvider in `config/app.php` intentional?

**Comment by Funso-Popoola** [comment]
I think I found just the answer: `App\Ship\Parents\Providers\EventsProvider`.

I'll try that out; hope it works!

**Comment by Mahmoudz** [comment]
Supported now :) 
https://github.com/apiato/core/blob/master/Generator/Commands/EventGenerator.php
https://github.com/apiato/core/blob/master/Generator/Commands/EventHandlerGenerator.php
