### ISSUE TITLE
Can't find the provider class registered in container's MainServiceProvider

### ISSUE THREAD

**Issue by jackbraj** [apiato/apiato#215]
## Expected Behavior

 - Install a package inside a container
 - Add service provider and alias in Main Service Provider
 - publish the vendor files

## Actual Behavior

 - When running php artisan vendor:publish from the root it throws class not found error

## Steps to Reproduce the Problem

  1. Install the package in user container (composer require maatwebsite/excel)
  2. Add Service provider and alias in main service provider
  2. Run php artisan vendor:publish from root directory

## Specifications

Using in laradock on Mac

  - Apiato Version:
    Not sure what version I am using but I have updated apiato at August 2

**Comment by jackbraj** [comment]
I solved this problem. I was installing the package from inside the container.
Now i added the package inside container's composer.json but ran composer install from root of project.

Thanks

**Comment by ab192130** [comment]
@jackbraj I have the same problem :( But when I try to run "`composer install`" from root of the project it says "`Nothing to install or update`"

1. Added "`intervention/image": "^2.5`" to Container's composer.json
2. Ran "`composer install`" from the project root

Result: "`Nothing to install or update`"

What I'm doing wrong? I appreciate any help
