### ISSUE TITLE
Naming conventions for Models in apiato

### ISSUE THREAD

**Issue by FWidm** [apiato/apiato#216]
## Expected Behavior
Object is instanciated and inserted into the database.

## Actual Behavior
Created a new Model (GeoRequestModel) with an unrelated name to the container (Demo) - which led to an issue during the creation of new instances:

```json
"message": "Class App\\Containers\\GeoRequestModel\\Models\\GeoRequestModel does not exist",
"exception": "ReflectionException",
```

## Steps to Reproduce the Problem
- `php artisan apiato:model` &rarr; create a new model with a repository with a name unrelated to the container.
- create a dummy route, controller method (and action) to instantiate the object

## Solutions
- Either provide a notice within the Artisan Command or take precautions for the user. 
    - Naming: provide a naming convention in your documentation (also include the case multiple models in one container - i think you have to add the container name as prefix followed by an underscore and then the model name?)
    - Try to fix the naming and notify the user in the artisan command?

___

**Hint**: I am new to apiato, Laravel and php, so maybe this is common sense in this domain but it was quite new for me, I'd appreciate it if you could add a paragraph naming conventions for such things.

**Comment by twcarefoot** [comment]
From the documentation http://apiato.io/components/repositories/

> Note: If the Repository belongs to Model with a name different than its Container name, the Repository class of that Model must set the property $container and define the Container name.

> Example:

```
<?php

namespace App\Containers\Authorization\Data\Repositories;

use App\Ship\Parents\Repositories\Repository;

class RoleRepository extends Repository
{
    protected $container = 'Authorization'; // the container name. Must be set when the model has different name than the container

    protected $fieldSearchable = [

    ];

}
```

**Comment by FWidm** [comment]
Thanks for the example. I searched for the info in the models section an did not find it. 🙂

**Comment by johannesschobel** [comment]
with the latest update for apiato/core (see [here](https://github.com/apiato/core/pull/8)) this issue should be resolved..
