### ISSUE TITLE
API requests

### ISSUE THREAD

**Issue by EdozdeDandez** [apiato/apiato#218]
## Expected Behavior

Should be able to access api routes

## Actual Behavior

Getting a missing jsonHeader error

## Steps to Reproduce the Problem

  1. Create an api route
  2. Make reference to the route
  3.

## Specifications

  - Apiato Version:

## Additional Details

Must we use javascript to refer to the API routes, using php gives the above error or is there a way to set the header to the form as you submit?

**Comment by johannesschobel** [comment]
You need to set the proper Http request header for the Request. I think that is: Accept: application/json

Should be in the docs

**Comment by Mahmoudz** [comment]
You will need to pass `Accept => application/json` in the request header. as @johannesschobel mentioned.
