### ISSUE TITLE
Route at admin.apiato.dev doest not work as expected

### ISSUE THREAD

**Issue by phuocnt0612** [apiato/apiato#223]
## Expected Behavior

- Visit `http://admin.apiato.dev`
- Should see an HTML Login page.

## Actual Behavior

It shows the same page as visit `http://apiato.dev`

## Steps to Reproduce the Problem

  1. Open browser
  2. Visit `http://admin.apiato.dev`

## Specifications

  - Apiato Version: 7.0
  - Environment: Laradock

**Comment by Mahmoudz** [comment]
@phuocnt0612 That's wired, there must be something wrong on your end. I just tested it now and I got this. 
<img width="1126" alt="screen shot 2017-09-04 at 7 14 48 pm" src="https://user-images.githubusercontent.com/1983984/30033709-72081e06-91a5-11e7-88cc-f623a477b0e1.png">
Do you have the following in your NGINX config file?

```    
server_name apiato.dev api.apiato.dev admin.apiato.dev;
root /var/www/projects/apiato/apiato/public;
```

**Comment by phuocnt0612** [comment]
@Mahmoudz Yes, below is my nginx conf
```
server {

    listen 80;
    listen [::]:80;

    server_name apiato.dev api.apiato.dev admin.apiato.dev;
    root /var/www/apiato/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
```

I can access to `admin.apiato.dev/login` or `admin.apiato.dev/dashboard`

**Comment by zlanich** [comment]
I too am having this issue still with the latest. http://admin.apiato.develop/login works fine, but http://admin.apiato.develop/ shows the Welcome page instead of the login page. `php artisan route:list` says it's there: SS: http://zsl.io/e9yc2k
