### ISSUE TITLE
Contribute one containers related WePay payment gateway.

### ISSUE THREAD

**Issue by jp1993** [apiato/apiato#225]
## Additional Details

We have create containers ( WePay payment gateway ) like stripe containers.
We want contribute containers so tell me, what is procedure for contribute containers?

**Comment by Mahmoudz** [comment]
Hello @jp1993 just forke, clone, checkout new branch "container-support", push and PR. I'll check it and leave you comments if anything needs change. 

Looking forward :)

**Comment by jp1993** [comment]
Hello Mahmoudz,

Please check below details, We don't have any **permission to push and PR** in new of branch "container-support". 

We have getting this type of error. 

"remote: **Permission** to apiato/apiato.git denied to jp1993.
fatal: **unable to access** 'https://github.com/apiato/apiato.git/': The requested URL returned error: 403"

**Comment by Mahmoudz** [comment]
@jp1993 You'll need to push to your own fork and then create PR to apiato/apiato. You cannot submit a direct PR
