### ISSUE TITLE
Criteria naming convention

### ISSUE THREAD

**Issue by mmieluch** [apiato/apiato#226]
Hi guys,

Excellent work on the project! We found Apiato recently and decided to use it to build an API.

Now to the problem at hand. I'm not really sure if it's just me nitpicking, but current naming convention for criteria is bugging me. I've double checked, and it looks like "criteria" is plural, and the singular for it should be "criterion". Currently Apiato embraces "criteria" for singular and "criterias" for plural.

I personally believe that software should adhere to correct grammar and spelling where possible, but I understand I may be a bit fussy about it. Is updating class names and namespaces to their correct forms something you guys might consider? I'd be willing to spend some time on it during weekend and submit a PR - maybe for a future release to avoid breaking changes?

Thanks!

**Comment by Mahmoudz** [comment]
@mmieluch you're absolutely right. Sure would love to adhere to correct grammar. I had no idea that  it should be criterion :D Feel free to make the change and submit the PR to master please. Also don't forget to update the docs. Best,

**Comment by mmieluch** [comment]
@Mahmoudz Cheers mate, I'll get cracking on weekend. I'll keep you posted.

**Comment by Mahmoudz** [comment]
@mmieluch I'll close the issue now and w'll merge your PR anytime is submitted. Best,
