### ISSUE TITLE
Attach multiples social accounts

### ISSUE THREAD

**Issue by aliasdoc** [apiato/apiato#238]
## Expected Behavior

Hi, is there a way to attach multiples social accounts ??

In my application a user can create an account with social account (facebook, Pinterest or instagram) and I want to let this user attach his other accounts to this account.

Exemple:

User 1 create an account with his facebook account, after he can attach his instagram and Pinterest account to this account.

Thank you.

**Comment by anthonymartin** [comment]
This feature is not supported yet, but I'm working on it.

**Comment by aliasdoc** [comment]
Hi @anthonymartin, ok, thank you for your work, can I help you with some things ?? how many time you think you need to release ?
