### ISSUE TITLE
[Feature] Documentation For Multiple Version

### ISSUE THREAD

**Issue by d8vjork** [apiato/apiato#245]
Hi there, 

I'm really new with Apiato 😆 so I'm centered on docs for learn more about and refactor one of my projects (a large scale app with only API based on Laravel).

Well, I suggest for a future to change doc pages for the different major versions (releases) of the Apiato framework (adding/removing features, we know about it).

Thanks and regards

**Comment by Mahmoudz** [comment]
@d8vjork I have a plan for that. Do you have any tool in mind or way to do this?

**Comment by d8vjork** [comment]
@Mahmoudz I'm thinking for something like the [Laravel docs](https://github.com/laravel/docs) (I like it so much) and I see that you followed the branch of this repo like Laravel framework.

For docs site some static page generator like VueJS (with vue-router) or some other loading files from GH API (with axios), but I don't try it yet.

**Comment by Mahmoudz** [comment]
@d8vjork yep the Laravel docs is a great example, I'd prefer to keep using the same Jekyll template we can add a dropdown to select version. But that version needs to exist somewhere, maybe we can remove the docs to it's own repo and create multiple branches for each version and then use Travis to build all the docs.. This is just one solution, I'd prefer to do the simplest, but maybe we can start with whichever works! 

If anyone interested in doing that please contact me on Slack to discuss it and implement it.

**Comment by d8vjork** [comment]
@Mahmoudz Ok, I can go to Slack and help in what I can 👍

**Comment by karllhughes** [comment]
I'm interested in this too. It seems that the docs are the bleeding edge version and include commands that are not in the latest stable version. For example, the `php artisan apiato:permissions:toRole admin` command isn't in `7.0`, but it is in the `master` branch. Gave me some confusion when getting started.
