### ISSUE TITLE
[Feature] Container Generator Command

### ISSUE THREAD

**Issue by Mahmoudz** [apiato/apiato#248]
We need a container generator command `php artisan apiato:container` same like the individual components generator `php artisan apiato:route`. The command should ask the user few questions in the command line and scaffold a full container based on the user answers. 

Questions Example: 
- Container Name
- Confirm Model Name is same as container name or override the default
- Do you want an API UI?
- Do you want a CRUD endpoints?
...

Interested in adding this feature? Read more
- How the code generator works? http://apiato.io/features/code-generator/
- How to contribute to the code generator? http://apiato.io/miscellaneous/contribution/#Contributing-Generator

**Comment by johannesschobel** [comment]
Hey man, I can deal with this if you like as I already implemented most of the generators so far ;) let's discuss next week if you like..

Cheers

**Comment by johannesschobel** [comment]
If my PR from [here](https://github.com/apiato/core/pull/13) gets merged, you can close this issue here 🎉
