### ISSUE TITLE
Social auth

### ISSUE THREAD

**Issue by musemartins** [apiato/apiato#249]
## Expected Behavior
When accessing /auth/provider it redirects to the provider

## Actual Behavior
It's returning me the following error:
Illuminate \ Contracts \ Container \ BindingResolutionException
Target [Laravel\Socialite\Contracts\Factory] is not instantiable.

## Steps to Reproduce the Problem

1. Go to /auth/facebook for example

## Specifications
I''m using Homestead

  - Apiato Version: Latest

**Comment by Mahmoudz** [comment]
Could be related to this somehow, https://github.com/apiato/apiato/issues/123 I'll close this and w'll comment on the older issue.
