### ISSUE TITLE
Unknown error - Undefined index: host

### ISSUE THREAD

**Issue by karthi191** [apiato/apiato#256]
iam getting error like this Undefined index: host and i attached a clear error in below

Notice: Undefined index: host in /opt/lampp/htdocs/911/config/filesystems.php on line 66

**Comment by Mahmoudz** [comment]
@karthi191 can you provide us with steps to reproduce this error?

**Comment by karthi191** [comment]
i dont now how this error occurs in my project. because its working good til now only getting error from Config::get(app.url)['host']

**Comment by Drummer01** [comment]
@karthi191 APP_URL must contain "http://" part in order to work properly
So, your APP_URL variable inside .env must look like this `APP_URL=http://apiato.dev`
