### ISSUE TITLE
Set the enhanced serialize precision as default for all apiato apps

### ISSUE THREAD

**Issue by FWidm** [apiato/apiato#257]
## Example
A demo action that just returns a float value with `return 1.1;` got transformed into a json response with the value `.100000000000000088817841970012523233890533447265625`.

## Explanation
When floats are returned by controllers it can happen that your local PHP version did not have the correct setting for the json serialize precision. MAMP for example has a default setting in the `PHP.ini` of `serialize_precision = 100` which leads to the example below. I'd propose to add into apiato to make sure everyone uses the more precise float value handling that was suggested and implemented in the following [php-rfc](https://wiki.php.net/rfc/precise_float_value). It can be used by setting the `serialize-prcision` to `-1` from PHP 7.1 onward.

You could add the following snippet to apiato to be sure everyone using PHP7.1 uses this enhanced serialize precision:

```
if (version_compare(phpversion(), '7.1', '>=')) {
    ini_set( 'serialize_precision', -1 );
}
```

I personally put it into one of my Service Providers but i figured it might help other people if the problem is fixed out of the box without thinking of it. I am not too sure on the placement, I figured that `boot()` in a Service Provider was likely the best match. 
I've also seen that LaraDock for example sets this in it's `PHP.ini` file. So I think it is intended to be the default behaviour.

I'd be happy to hear your thoughts!

**Comment by Mahmoudz** [comment]
@FWidm nice suggestion, didn't knew about the existence of this problem. It feels good to have it as solution. I would place it in `bootstrap/app.php` at line 2 (even before creating the Application instance). Would you like to add this by yourself?

**Comment by FWidm** [comment]
Sure, just opened a PR it :)
