### ISSUE TITLE
Installation instructions order

### ISSUE THREAD

**Issue by karllhughes** [apiato/apiato#265]
## Expected Behavior
Installation instructions should clearly show steps in order they must be performed.

## Actual Behavior
It seems that you have to work backwards through the [installation documentation](http://apiato.io/getting-started/installation/).

I'm new to using Laradock and apiato, but when I was first getting started, I had to install apiato first, then clone Laradock into the new project directory in order to get Laradock to run. It's a little unclear that this is the required order of things.

## Specifications
  - Apiato Version: 7.0.3

## Additional Details
I think the fix for this would be to change the order of the installation documentation. It would have been more clear if it were written in this order:

- APIATO Installation
- Environment Setup (with Laradock)
- Play

I know this may not work for every environment though. I haven't done the install with Homestead or local installs.

Anyway, let me know what you think, and if it helps I can submit a PR with the changes. Thanks!

**Comment by Mahmoudz** [comment]
@karllhughes makes sense, thanks for the feedback. Would you please submit a PR with the new order. Feel free to add extra information if needed to simply the process.
