### ISSUE TITLE
Web UI exceptions rendered as JSON

### ISSUE THREAD

**Issue by DomasWEB** [apiato/apiato#274]
## Expected Behavior

Display Laravel type error pages

## Actual Behavior
For example if you are on Web UI and have a request with rules, after hitting that request the content rendered to the browser is JSON response from the API, like so:
```
{
  "status": "error",
  "code": 0,
  "message": "The given data was invalid.",
  "errors": {
    "address2": [
      "Please fill in address2 field."
    ]
  },
  "status_code": 422
}
```
And that is for all exceptions.

## Steps to Reproduce the Problem

Tried with new 
  1. Fresh install of apiato
  2. Go to http://apiato.dev/random-page (which does not exist)
  3. See
```
{
  "status": "error",
  "code": 0,
  "message": "",
  "status_code": 404
}
```

  - Apiato Version: Latest dev-master

## Additional Details

Only after the exceptions refactor this problem occoured.

Code from Illuminate\Foundation\Exceptions\Handler@renderHttpException:
```
public function render($request, Exception $e)
    {
        $e = $this->prepareException($e);

        if ($e instanceof HttpResponseException) {
            return $e->getResponse();
        } elseif ($e instanceof AuthenticationException) {
            return $this->unauthenticated($request, $e);
        } elseif ($e instanceof ValidationException) {
            return $this->convertValidationExceptionToResponse($e, $request);
        }

        return $this->prepareResponse($request, $e);
    }
```

Is this because of Optimus\Heimdal? Should it be modified to some how report it differently?

I am probably one out few people using the WEB UI but this is really terrible as the exception handling on WEB UI is broken.

If we could discuss a solution I could probably do the fix.

Thank you

**Comment by johannesschobel** [comment]
hey there.. this surely is related to `Heimdal` which was introduced shortly by a PR from me that reworked the whole `Exception` handling in Apiato.

I will look into this issue the next days..

How should the Exceptions should be handled in the `WEB UI`? Just display the `whoops` package? Or what is your idea?

**Comment by johannesschobel** [comment]
But you must admit that the new exceptions are soooooo cool because you can customize it ;) will fix the web part though.. any ideas how to display them? Or what to do?

**Comment by cesasol** [comment]
Just getting into apiato and with the same dilema, and for the last question I guess:

- For routing based errors like 404 or 505 a simple page with a not so scary oops message.
- As for things like login or other user/interface action a error variable inside the view and return them to the last view. Although almost every action on the ui is handled with js and ajax requests, this fallback would prove useful for this scenario.

**Comment by johannesschobel** [comment]
@cesasol , @DomasWEB 
Ok, i fixed it.. I will release a PR shortly!

**Comment by DomasWEB** [comment]
@johannesschobel great! can't wait for it :) thanks for your work !

**Comment by johannesschobel** [comment]
@DomasWEB no problem.. i am not entirely sure, if i missed that or whatever..
anyways - it should be fixed in core soon, so just `composer update` to get the latest changes

**Comment by Mahmoudz** [comment]
Fixed https://github.com/apiato/core/pull/28
