### ISSUE TITLE
double time string in apiato:generate:migration generated migrations

### ISSUE THREAD

**Issue by yalsicor** [apiato/apiato#278]
Hi,

with the new apiato:generate:migration command I get double timestrings in the generated file name when I use the default value.

expected: 2017_10_20_143836_create_user_tables.php

generated file: 2017_10_20_143936_2017_10_20_143836_create_user_tables.php

- Apiato Version: apiato version 7.1.1

This only happens, if the default file name is used. If the timestring is appended anyway, the default value should be without it?

Thanks, Yal

**Comment by johannesschobel** [comment]
hey there.. good catch - i'll fix this!

**Comment by johannesschobel** [comment]
will be fixed with the mentioned PR here

**Comment by Mahmoudz** [comment]
closed by #29
