### ISSUE TITLE
Apiato LTS

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#281]
Hi,
I've been looking into this project for the last couple of weeks and i love the general (portos) structure and the added boilerplate code. But it seems like it's still under heavy development. I'm about to start a huge project that i would love to use apiato for but i would need a stable maintained version to do so. Would it be possible to come out with a long term release?

**Comment by Mahmoudz** [comment]
@deviouspk totally understand you concern. I feel version 7.1 should be the LTS, as it is the most stable release when compared to previous releases so far. The project will remain actively developed and improved, but I don't see major changes in the near future. 

I will have to think about your request, and w'll reply next week once I take a final decision whether I should make the 7.1 or the next release or non of them an LTS, with 1 year of bug and security fixes.

Thanks for your request.

**Comment by deviouspk** [comment]
Thankyou,
I'll be waiting for you decision ;)

**Comment by MustangZhong** [comment]
hi there, any update on this?

**Comment by Mahmoudz** [comment]
@deviouspk @MustangZhong Hi, after carefully thinking about this, I conclude that version 7.2 will be the first LTS.
Should be released in the first week of October. More details will be documented. 

Hint: if you're looking to start today, you can clone the master branch, and later merge the 7.2 branch in it, once available.

Best,

**Comment by deviouspk** [comment]
Thankyou :) I'll start writing boilerplate code then wich i will port to the 7.2 ;)

**Comment by Mahmoudz** [comment]
Hello guys, I'm happy to announce the 7.2 is the first LTS [version](https://github.com/apiato/apiato/releases/tag/v7.2.0).
