### ISSUE TITLE
[Feature] reset password

### ISSUE THREAD

**Issue by yalsicor** [apiato/apiato#283]
I recently added reset password functionality to my instance of apiato.

It has a forgetpassword endpoint that sends the user (if there is any) an email with a link and a resetpassword endpoint that resets the password (with the token from the email).

Would that be a beneficial feature to apiato to create a PR for?

Thanks, Yal

**Comment by Mahmoudz** [comment]
@yalsicor Sure, this is useful, w'll be waiting your PR. Thanks in advanced.

**Comment by bloggervista** [comment]
@yalsicor  can you tell us when will this feature come ?? Because We also need it and instead of reinventing the wheel I guess this PR would be better choice.
