### ISSUE TITLE
[Feature] Create Admins from CLI

### ISSUE THREAD

**Issue by Mahmoudz** [apiato/apiato#284]
Create a Command same like `app/Containers/Authorization/UI/CLI/Commands/GiveAllPermissionsToRoleCommand.php` in the same directory. name it `CreateAdminsCommand`.

It should ask the user for name, email and password. And pass them to `CreateUserByCredentialsTask` exactly the same like what's in this seed file `app/Containers/Authorization/Data/Seeders/AuthorizationDefaultUsersSeeder_3.php`.

**Comment by johannesschobel** [comment]
can be closed if the mentioned PR is merged
