### ISSUE TITLE
API Docs generation

### ISSUE THREAD

**Issue by marcoEgger** [apiato/apiato#288]
## Expected Behavior
Documentation is generated successfully.

## Actual Behavior
Generation fails without useful error message.

```
php artisan apiato:docs
Generating API Documentations for (public & private)



  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "$(npm bin)/apidoc -c app/Containers/Documentation/ApiDocJs/public -f public.php -i app -o public/api/d
  ocumentation" failed.

  Exit Code: 1(General error)

  Working directory: D:\Eigene Dateien\Projekte\PHP\image-hub-api

  Output:
  ================


  Error Output:
  ================

```

## Steps to Reproduce the Problem

  1. Create new project with ```composer create-project apiato/apiato image-hub-api```
  2. Clone (and add as git submodule) laradock inside project root
  3. Launch docker with ```sudo docker-compose up nginx mysql redis beanstalkd```
  4. Migrate and seed database while on docker workspace
  5. Install passport while on docker workspace
  6. Run ```npm install apidoc -g``` in project root (not on workspace because of missing npm)
  7. Finally execute ```php artisan apiato:docs```

## Specifications
  - OS: Windows 10
  - Environment: Docker for Windows and Laradock
  - Apiato Version: 7.1.3 (latest release currently)
  - NPM Version: 5.5.1
  - Node Version: 6.6.0

## Additional Details
Tried this with and without admin privileges also on git bash (MINGW64) and PowerShell

**Comment by Mahmoudz** [comment]
Hi @marcoEgger,

Try updating this `'executable' => 'apidoc',` in the config file. 

See Error: ApiDoc not found @ http://apiato.io/features/api-docs-generator/
