### ISSUE TITLE
Auth0 support

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#304]
https://auth0.com is a cloud login service provider that is easy to use has everything developers need for free (up to 7K active users at wich point you might want to upgrade anyway :+1: ) including single sign on for over 50 providers (facebook, google, twitter, github, microsoft,...).  + an official laravel repository. https://github.com/auth0/laravel-auth0.

Since apiato is supporting major payment gateways out of the box i thought we could also include a login provider :)

**Comment by Mahmoudz** [comment]
@deviouspk That looks pretty nice service. It's not totally free as I see it's free for the first 1000 users. I wouldn't mind supporting this, but not as a replacement for the current supported Authentication. I see it as a nice add-on. How would you imagine that implemented. Keeping in mind I willing in the future to support multiple Authentication techniques such as JWT, OpenID.. so this could be just one of the options.

**Comment by deviouspk** [comment]
Well it's free for open source use or up to 7000 users. Hmm for the implementation i would build an abstract layer something like a AuthServiceProvider. Wich could support multiple "drivers" like passport,jwt,openid,auth0,..

**Comment by Mahmoudz** [comment]
@deviouspk yes I mean for our users who want to build projects with Apiato, they will have to pay in the future. Let's see how the implementation would look like, I'd suggest creating multiple containers for each auth method with a master authentication container where we define the driver, which and set the common functionalities.
