### ISSUE TITLE
Cache instead of eloquent for settings container

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#305]
Grabbing the same variable a million times from the database really slows down your application and increases the load on the db server. The cache facade in laravel is specifically designed to handle these kind of problems. Alternatively we could cache the value and rebuild the cache when a setting value is changed. That way we would be able to keep the eloquent model with the benefit of extra performance.

**Comment by Mahmoudz** [comment]
@deviouspk nice suggestion, I actually do this in one of my projects for the settings and some other places, but that project code is older than the one I currently have in Apiato. Would be nice if anyone would to add that.
