### ISSUE TITLE
HashId error for hashed lookup id

### ISSUE THREAD

**Issue by desertfoxmb** [apiato/apiato#308]
Two models
Person (Id, LookupId)
Lookup (Id, Name)

Foreign key from Person.LookupId to Lookup.Id is nullable

CreatePersonRequest has LookupId added to the $decode array
When retrieving list of Lookups for a dropdown in the UI, we hash the ids in the LookupTransformer.
User does not select a Lookup value (allowed behavior)
We then Create the Person

## Expected Behavior
Person is saved with a null LookupId

## Actual Behavior
Exception thrown "Only Hashed ID's allowed"

## Specifications
  - Apiato Version: 7.1.0
  - UI is Angular CLI

## Additional Details
In CreatePersonRequest
` protected $decode = [
        'LookupId'
    ];`

**Comment by Mahmoudz** [comment]
@desertfoxmb Thanks for reporting this, if I understand you right, the problem occurs with passing an optional hashed ID. I fixed that now, hope this was the issue. Kindly run composer update to get v2.0.7 of the apiato/core package which contains the fix. Let me know if that was the issue.

**Comment by desertfoxmb** [comment]
That is indeed what I meant and it is resolved. Thanks for the quick turnaround!

**Comment by desertfoxmb** [comment]
That is indeed what I meant and it is resolved. Thanks for the quick turnaround!
