### ISSUE TITLE
Basic auth question

### ISSUE THREAD

**Issue by kvael** [apiato/apiato#313]
I am not able to authenticate to apiato.
I have followed the apiato documentation and searched the entire Google for answers.

cURL
curl -X GET   http://api.apiato.dev/v1/users   -H 'accept: application/json'   -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbG...'

The response i get
{
	"status": "error",
	"code": 0,
	"message": "Unauthenticated.",
	"errors": "Missing or invalid Access Token!",
	"status_code": 401
}

I am using the access_token i get from http://api.apiato.dev/v1/oauth/token

{
	"token_type": "Bearer",
	"expires_in": 86400,
	"access_token": "eyJ0eXAiOiJKV1QiLCJhbG..."
}

Would appreciate any help or tips. Have been stuck with this problem for two days now.

**Comment by overbid** [comment]
What is your Web Server?
Is your response have refresh token? I assume yes. Could you try http://api.apiato.dev/v1/oauth/token with
```
{
	"client_id": 2,
	"client_secret": "3H...",
	"grant_type": "refresh_token ",
        "refresh_token": "def50..."
}
```
and could you enable all debug in .env for more details.

**Comment by kvael** [comment]
I had used an incorrect login method. When using "OAuth2 - Login (Password Grant)" i get the correct response.

Thanks for pointing me in the right direction
