### ISSUE TITLE
Validator with invalid value for "exists:users,email" rule causing welcome route to render

### ISSUE THREAD

**Issue by adcuz** [apiato/apiato#315]
## Expected Behavior
Standard validation exception should be thrown for all validation errors.

## Actual Behavior
Renders a 200 OK response from the Welcome container's apiRoot() controller method. 

## Steps to Reproduce the Problem
Setup passport and attempt to use the Password Grant proxy method at `/v1/clients/web/admin/login`.
  1. Attempt to login with an email that does not exist in the database. (this will return a 200 status and render welcome)
  2. Attempt to login with an email that does exist in the database, but use an incorrect password (this will correctly throw a login exception)
  3. Enter a correct email/password (correctly logs in)

## Specifications
Latest Apiato master on PHP 7.1 (laradock)

## Additional Details
I've tried to debug to offer a pull request, but I am not yet familiar enough with the Apiato infrastructure to be able to so.

**Comment by adcuz** [comment]
I've discovered that this was only happening in Postman (A desktop client for testing APIs), I think I have it configured incorrectly. This works as expected in other environments (react native in this case), so closing for now.

**Comment by ili5** [comment]
You need to set Accept application/json header in postman to receive JSON response. Otherwise, you will be redirected to welcome page
