### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by emukiri** [apiato/apiato#316]
I have created commands in the CLI section of my container and registered them in the ConsoleKernel.php file as recommended in the documentation. 

`    protected $commands = [
        UpdateTimelinesPhases::class
    ];`

The schedule function has the following code:

`       $schedule->command('updateTimelinesPhases')->everyMinute();
  `

I expect the command to execute after every minute but it does not happen. 

When I run `php artisan updateTimelinesPhases` on the terminal the command executes as expected. My crontab is well setup and commands for my other Laravel projects are being executed as expected.

What could be the issue?

**Comment by adcuz** [comment]
Can you share the code for your command? It might help to diagnose the problem.

**Comment by emukiri** [comment]
Here is the command code:

`class UpdateTimelinesPhases extends ConsoleCommand
{

    protected $signature = 'updateTimelinesPhases';

    protected $description = 'Update Timelines Phases';
    /**
     * @var UpdateTimelinesPhasesAction
     */
    private $updateTimelinesPhasesAction;


    public function __construct(UpdateTimelinesPhasesAction $updateTimelinesPhasesAction)
    {
        parent::__construct();
        $this->updateTimelinesPhasesAction = $updateTimelinesPhasesAction;
    }

    public function handle()
    {
        $this->updateTimelinesPhasesAction->run();

        \Log::info("Timeline phases updated");
    }
}`

**Comment by johannesschobel** [comment]
I am not sure, but I think, Apiato does some kind of "Auto-Registering" for your Commands, if you put them in the appropriate folder in your container?!

Just a few ideas:
1) Have you read the docs? ;)
2) try to put it in the Ship/Commands folder (not sure if it is called like this - but there should exist one like this) and try if it works
3) Is the constructor executed? Can you `dd('hello');` to see if this works?

Cheers

**Comment by emukiri** [comment]
Yes I have read the docs, [this](http://docs.apiato.io/components/commands/) section specifically. 

As per the docs the Command can either be in the Ship or in a container if it is a container specific command and that is why I have placed the Commands in the container `Container/{container_name}/UI/CLI/Commands` folder.

The issue still persists even after moving the Commands to the Ship/Commands folder.

**Comment by johannesschobel** [comment]
Actually.. I am not sure, if you need to use `Jobs` for this? Never had this specific scenario

**Comment by FWidm** [comment]
Hi, could you re-check your cronjob configuration?

For me (on an older apiato version!)

Cronjob config:
`* * * * * /usr/local/opt/php71/bin/php /path/to/api/artisan schedule:run > ~/apiato_cron.txt`

Inside of the `ConsoleKernel` i've got the following config:
```php
    protected $commands = [
        'App\Containers\Container\UI\CLI\Commands\NewCommand',
    ];
...
    protected function schedule(Schedule $schedule)
    {
        $schedule->command(NewCommand::class)->everyMinute();
    }
`
``

**Comment by emukiri** [comment]
Thank you @FWidm the error was in the crontab configuration file.
