### ISSUE TITLE
API page not found 

### ISSUE THREAD

**Issue by phuongphally** [apiato/apiato#319]
When I try to access api.domain.dev/v1 

Sorry, the page you are looking for could not be found.

**Comment by johannesschobel** [comment]
can you provide more information?
Have you looked through the other issues (especially https://github.com/apiato/apiato/issues/289 and https://github.com/apiato/apiato/issues/288 ) if they might be related to your problem?

Cheers

**Comment by phuongphally** [comment]
@johannesschobel  Thanks you .

**Comment by johannesschobel** [comment]
no problem, you're welcome.. just close the issue if this helps

**Comment by phuongphally** [comment]
Why I can not access static file css or javascript ? what is syntax ? 

In laravel I used assets('css.css') to access file in public/css.css 


Thanks .

**Comment by johannesschobel** [comment]
maybe your `.htaccess` or your `.env` file is not configured properly so the files cannot be loaded

**Comment by Kyslik** [comment]
I recommend installing [Valet](https://laravel.com/docs/5.5/valet) and all server issues will disappear.

**Comment by johannesschobel** [comment]
i closed this issue for now ;) plenty of good details right here, i guess
