### ISSUE TITLE
Chat plataform

### ISSUE THREAD

**Issue by lpj145** [apiato/apiato#323]
Hey, when i see Porto/Apiato, i thinks is so amazing... but i have some points to talk about this architeture and like to talk about it, currently yours used what chat to discuss ?

I not like laravel, but not hate me, i try to reproduce this architeture with zend expressive, and if you can response me, on UI have space to factories ?

**Comment by johannesschobel** [comment]
Hey @lpj145 ,

Currently, we use `Slack` to discuss amongst each other. You can find the link on the official project site www.apiato.io .

The PORTO idea, however, is framework agnostic, so you can port it to ZEND or whatever you like

**Comment by lpj145** [comment]
i try enter on slack by link, but not have success. this link is correct ?

https://slackin-mezlsumyvc.now.sh/

**Comment by johannesschobel** [comment]
the link should be correct @lpj145 .. although it takes some time to load - at least for me.. In turn, there are constantly people joining the apiato slack channel - so this should work.. Can you try it again!?
