### ISSUE TITLE
I don't think composer.lock should be .gitignored

### ISSUE THREAD

**Issue by Kyslik** [apiato/apiato#335]
https://github.com/apiato/apiato/blob/master/.gitignore#L18

**Comment by johannesschobel** [comment]
basically, in your **own** application, it is "best practice" to commit a `composer.lock` file in order to tell specifically to which version you "lock" this build to..

However, for frameworks it is not "recommended" to do so..

**Comment by Kyslik** [comment]
I sometimes have hard time to understand if you are being ironic or not :D (I would not write issue about composer.lock if I had no clue what it is used for).

----

Anyway:

```bash
composer create-project apiato/apiato my-api; cd ./my-api && cat .gitignore | grep "composer.lock"
```
Spits out:

```bash
composer.lock
```

On the contrary take a look at `.gitignore` from laravel/laravel (implementation of laravel/framework) https://github.com/laravel/laravel/blob/master/.gitignore

```
/node_modules
/public/hot
/public/storage
/storage/*.key
/vendor
/.idea
/.vagrant
Homestead.json
Homestead.yaml
npm-debug.log
yarn-error.log
.env
```

So which framework has it wrong Laravel or Apiato? I take it that this repository is **implementation** of the framework (**apiato/core**) is it not? Same way how **laravel/laravel** is implementation of **laravel/framework**.

**Comment by johannesschobel** [comment]
oh sorry.. this is my bad.. i thought about the `composer.lock` in `apiato/core`! Sorry, you are right - i agree that the `composer.lock` should be included..

sorry - wasn't meant to be ironic.. I was just busy and didn't read it carefully 😢

**Comment by Kyslik** [comment]
Do not worry about being ironic, communicating over text is hard :D, I always assume ironic mood :) - my bad.
