### ISSUE TITLE
Request: Better release notes

### ISSUE THREAD

**Issue by Kyslik** [apiato/apiato#337]
I have diverged from this scaffold a lot, and I look at release notes a lot. I am missing exact PRs || Issues links from release notes for example https://github.com/apiato/apiato/releases/tag/v7.3.2 I have no clue where/what did change in order to "**Specify Apiato core package version number.**"

I would welcome PR or Commit or whatever which did the change.

**Comment by johannesschobel** [comment]
Hey there, that is actually a good idea (not meant to ironic 😀 i promise! )..

However, i think, adding the links to the changelog.md file would be better, as this file is continuously updated. Sometimes, it is quite hard to remember what has been done over the last weeks, and why specific changes were introduced..

**Comment by Kyslik** [comment]
Haha thanks! :)

Yea [changelog.md](https://github.com/apiato/apiato/blob/master/CHANGELOG.md) seems to be not maintained thats why I relied on release notes an manually track down the changes.

**Comment by johannesschobel** [comment]
actually - you are right.. hmmmmmmmmmmmm~ i'm going to fix that.. sorry for that!

**Comment by johannesschobel** [comment]
i am going to close this for now.. I hope I will not forget to update the changelog when merging PRs, haha
