### ISSUE TITLE
Testing the Ship things

### ISSUE THREAD

**Issue by Kyslik** [apiato/apiato#345]
I am kind of missing the Ship's testing scaffold.

There might be situations where users (of Apiato) write generic code used with many Containers thus having tests for Ship makes sense.

Any thoughts?

**Comment by Mahmoudz** [comment]
@Kyslik sounds convenient, kindly feel free to submit a PR containing support for testing on the Ship, I would create a Tests directory on the root of the Ship with test folder in it representing the test type (unit, integration, functional, acceptance, infrastructure, performance, security..). You will need to update the `phpunit.xml` to load those tests. Best,

**Comment by Kyslik** [comment]
Yep I already do have this set up within my app. I may make a PR, for anyone else here is part of a `phpunit.xml` I am using:

```xml
<testsuites>
    <testsuite name="Container's Tests">
        <directory suffix="Test.php">./app/Containers</directory>
    </testsuite>
</testsuites>
<testsuites>
    <testsuite name="Ship's Tests">
        <directory suffix="Test.php">./app/Ship/Tests</directory>
    </testsuite>
</testsuites>
```

**Comment by ivanange** [comment]
Yes Also it will be cool to be able to test a specific container
