### ISSUE TITLE
Class 'Apiato\Core\Abstracts\ValueObjects\ValueObject' not found

### ISSUE THREAD

**Issue by dharmendradavid** [apiato/apiato#352]
Currently, I found 
Class 'Apiato\Core\Abstracts\ValueObjects\ValueObject' not found issue after run composer update command.

**Comment by johannesschobel** [comment]
The class has been renamed to 'Values' recently.. try switching to the latest apiato & core version

**Comment by dharmendradavid** [comment]
Thank you, for help. I have updated ValueObject to Value.
