### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by bloggervista** [apiato/apiato#356]
is apiato.io is down? it currently shows 503.

**Comment by johannesschobel** [comment]
looks like so, yes.. hopefully it is just a problem with the hoster :)

**Comment by johannesschobel** [comment]
the docs seems to be up: http://docs.apiato.io/

**Comment by Mahmoudz** [comment]
Sorry about that didn't notice I had an issue with my AWS servers. Fixed it all now.
