### ISSUE TITLE
Awesome Apiato - A curated list of containers...

### ISSUE THREAD

**Issue by rAugustos** [apiato/apiato#357]
Hi team. 

Suggestions:

- Create the file Awesome Apiato - A curated list of bookmarks...

Maybe this can make this project even more bigger.

GJ

**Comment by johannesschobel** [comment]
Haha, that is actually a good idea.
I have set up a respective repository to gather such information. Please find it here:
https://github.com/apiato/awesome-apiato

Submit PRs if you have any containers you would like to share!
