### ISSUE TITLE
getHashedKey('foreign_id') always returns value of primary key when config set to false

### ISSUE THREAD

**Issue by rensreinders** [apiato/apiato#372]
## Expected Behavior

value of the some_other_id field

## Actual Behavior

value of id field

## Steps to Reproduce the Problem

  1. call $object->getHashedKey('some_other_id')
  2. set config apiato.hash-id to false
  3. see return value is always value of $object->id

## Specifications

  - Apiato Version: 2.2

## Additional Details

This is something different than the issue where the value of the primary id is return when the value of some_other_id is false.

**Comment by johannesschobel** [comment]
can you take a look at this issue here https://github.com/apiato/apiato/issues/317
in newer versions of apiato (7.2 and upwards) this should be fixed?! Can you confirm this?
Otherwise, i will take a look

**Comment by petermein** [comment]
This should fix the issue

https://github.com/apiato/core/pull/76

**Comment by johannesschobel** [comment]
I will review this on Sunday or Monday and give feedback.. Thank you

**Comment by johannesschobel** [comment]
merged

**Comment by petermein** [comment]
One addition on hashkey's, when using a key on a nullable value. The library returns "" (empty string) this means you still have to implement logic in your transformers to fallback gracefully. 

https://github.com/apiato/core/pull/77
