### ISSUE TITLE
L5.6

### ISSUE THREAD

**Issue by san4io** [apiato/apiato#373]
We need an upgrade! :)

**Comment by johannesschobel** [comment]
As discussed in another issue, this is currently not possible because 3rd party packages have not updated yet..

However, I have started to update.. just waiting for a few dependencies.. give them (and me) a few more days..

**Comment by shalawani** [comment]
@johannesschobel Thank you for your great job.
may I ask you about the which 3rd party packages are you waiting

**Comment by johannesschobel** [comment]
Problem is with `Laravel-Manager`.. Author said, he will update the package "in the next 2 week".. We will have to wait till then - sorry..

i let this issue open in order to let other people see this issue and not create another one 😆

**Comment by johannesschobel** [comment]
Oh yes.. another thing here..
L5.5, which apiato uses at the moment, is a stable (and long term support) release of Laravel. Laravel 5.6., however, will not be one! 

In my opinion, it is not that super crucal to switch to L5.6... I think, in your own application, several packages don't work with L5.6 either.. so just give it a little more time ;)

**Comment by johannesschobel** [comment]
Hey,.. 
yesterday i pushed a new release `apiato 7.4` that contains `laravel 5.6`. Have fun with it ;)

**Comment by shalawani** [comment]
When first install v7.4 we have this message
"Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them."

**Comment by johannesschobel** [comment]
i think you can safely delete the `composer.lock` file and run `composer update` in order to get the latest updates..

The problem is, that the `composer.lock` comprises the current versions (the date i last updated the `composer.json` file and uploaded it) of the packages. However, you may have updated several package on your own - this will cause this diff..

Hope this helps!?

**Comment by lloricode** [comment]
Hi, is there any update here?
