### ISSUE TITLE
Job Generator generates Jobs that don't autoload

### ISSUE THREAD

**Issue by adcuz** [apiato/apiato#381]
## Expected Behavior
The job generator should generate jobs that work.

## Actual Behavior
The jobs generated don't work, as they don't appear to be autoloaded correctly.

## Steps to Reproduce the Problem

  1. Run `apiato:generate:job`
  2. Attempt to dispatch the generated job from an action

## Specifications
Ubuntu with PHP 7.1.4.1

  - Apiato Version: 7.4.2

## Additional Details
Note that the generator currently sets the namespace of the generated job to `App\Containers\{container name}\Job` which is wrong, after correcting it to `App\Containers\{container name}\Jobs` the issue still exists. Running `php artisan clear-compiled` and `composer dump-autoload` does not help. I suspect this is an issue within Apiato, as I can create a job under any other directory other than Jobs and it will work as expected.

**Comment by FWidm** [comment]
Hi! I've just tested the Generator on my API

First of all, the namespace issue needs to be adressed for sure, i had the same error. Other than that my Job dispatches fine.

Job:
```php
 class DemoJob extends Job
 {
     private $recipients;

     public function __construct(array $recipients)
     {
         $this->recipients = $recipients;
     }

     public function handle()
     {
         Log::info("Recipients of the Demo Job: " . join(',', $this->recipients));
     }
 }
```

Dispatching:
```php
DemoJob::dispatch(["hello","world"]);
```

Start up the queue:
```bash
$ php artisan queue:work --tries=1
```

Output:
```
[2018-03-07 07:35:58] local.INFO: Recipients of the Demo Job: hello,world  
```

I hope this helps a bit :)

**Comment by johannesschobel** [comment]
Thank you very much for the detailed information / explanation @FWidm ..
The issue with the namespace has already been fixed in the latest `apiato/core` version
