### ISSUE TITLE
Install latest stable apiato with laravel 5.5 instead of laravel 5.6

### ISSUE THREAD

**Issue by mfkkloke86** [apiato/apiato#388]
Would like to know is it possible to install latest apiato with Laravel 5.5 only?

**Comment by johannesschobel** [comment]
You can use the 7.3 branch

**Comment by kk86bioinfo** [comment]
If using latest 7.4 and modify composer.json to 5.5 will it break modules?

**Comment by kk86bioinfo** [comment]
Thanks. I think I will just stick to 7.2-LTS branch to be safe. Will experiment on 7.4 for 5.5 downgrade when have free time.

**Comment by johannesschobel** [comment]
You need to manually change all other dependencies back to a valid 5.5 state.. This also includes the core!

**Comment by mfkkloke86** [comment]
I see. Thanks. I will close this issue.
