### ISSUE TITLE
after upgrade 7.4 apiato getting error

### ISSUE THREAD

**Issue by rockers007** [apiato/apiato#389]
after upgrade 7.4 apiato getting error
testing.ERROR: Method Illuminate\Http\Request::setTrustedHeaderName does not exist.

**Comment by johannesschobel** [comment]
This is most likely to the fact that the 3rd party package `fideloper/trustedproxy` has changed / was updated because of a update within symfony! Can you follow the upgrade guide on `Laravel` in order to see if this may affect your application!

**Comment by rockers007** [comment]
Thanks ,but now getting
Type error: Argument 2 passed to Symfony\\Component\\HttpFoundation\\Request::setTrustedProxies() must be of the type integer, array given, called in D:\\xampp\\htdocs\\ratemytaxauditor\\vendor\\fideloper\\proxy\\src\\TrustProxies.php on line 54

**Comment by johannesschobel** [comment]
Have you adapted the `App/Ship/Middlewares/Http/TrustProxies` middleware accordingly?!

**Comment by rockers007** [comment]
Thanks.Now its solved by replacing new one App/Ship/Middlewares/Http/TrustProxies,

**Comment by johannesschobel** [comment]
At the time providing the new Apiato 7.4 version, i also wrote an Upgrade Guide covering the most import steps. This guide is located here: http://docs.apiato.io/miscellaneous/upgrade-guide/

Within the guide, the respective change to the `TrustProxies` middleware is explicitly mentioned!
