### ISSUE TITLE
Validations redirect to api home path

### ISSUE THREAD

**Issue by vituocgia** [apiato/apiato#391]
## Expected Behavior
When applying rules from Request Class, If have any invalid element from user input we should return the error message

## Actual Behavior
When entering an invalid value for a field (JSON input) I got the message "Welcome to Apiato"

## Steps to Reproduce the Problem
Create sample container with API only
Just apply the rules in the requested Class
Note: I was run composer update/install and some repos have been updated...

## Specifications
I'm running Windows 10, PHP 7.2.3, OracleDB (Oci8)

  - Apiato Version: 7.4.4

## Additional Details
I don't know why this happens??
Will try with the blank Apiato project without any modification

**Comment by johannesschobel** [comment]
You may actually add the `Accept : application/json` header to the request.. can you try? This is most likely because your request does not contain required headers..

Regular web browser cannot add such headers, therefore it bypasses and routes to `/` ..

Cheers

**Comment by vituocgia** [comment]
Hello
Thanks for the fast reply, that fixed my problem... But I think we should check the headers to prevent this error...
I'm using Postman to test the API, for most other APIs they do not check for the missing "Accept" in headers but still return the error message.

**Comment by johannesschobel** [comment]
There is an config flag that checks for this in a dedicated Middleware! Can
you check the docs?

vituocgia <notifications@github.com> schrieb am Sa., 24. März 2018, 12:39:

**Comment by vituocgia** [comment]
Yes, I saw it :)
http://docs.apiato.io/getting-started/requests/#send-http-req

**Comment by johannesschobel** [comment]
I'll close this.. if you have additional questions, please ask..

Cheers
