### ISSUE TITLE
is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by q2amarket** [apiato/apiato#395]
I am the new user of this repo and getting trouble installing this.

- On Mac High Sierra I have run the composer command and got all files.
- I have set up my local domain` xyz.local` in `host` and `vhost` files
- I have replaced `APP_NAME`, `APP_URL`, and `API_URL` in `.env` file with my `xyz.local` and `api.xyz.local` respectively.
- I have checked all the server requirements and all required extensions are installed and enabled on my dev server.

**However, I am still having the following error** 
`The page isn't working.... xyz.local is currently unable to handle this request. HTTP ERROR 500`

Can anyone help me to run this script on my local?

**Comment by johannesschobel** [comment]
- did you closely follow the installation instruction on the docs site?
- have you correctly set up required subdomains (and configured them correctly)?
- have you set up oAuth (passport respectively) correctly?
- did you run the migrations and seed the database?
- ...

**Comment by q2amarket** [comment]
Yes, I did. I have fixed some of the issues and most of the things are working but still struggling to get API endpoints.

I am getting this message `Sorry, the page you are looking for could not be found.`

I have set up all sub-domains admin and api both in vhost and host files. Still not getting. Can anyone help me to fix it?

**Comment by johannesschobel** [comment]
can you send a full request you are making against the API.. the url, headers and so on..

**Comment by mukeshgithb** [comment]
This page isn’t working
34.220.46.218 is currently unable to handle this request.
HTTP ERROR 500

I am getting this message when i submit a form for download zip in wordpress .Can anyone help me to fix it.

**Comment by johannesschobel** [comment]
Provide more details

**Comment by mukeshgithb** [comment]
Yeah sure,

I want to download the zip files from live server.And i have code which is

$file_names = array('http://34.220.46.218/wp-content/uploads/2018/11/64920LF_.dwg_.zip','http://34.220.46.218/wp-content/uploads/2018/11/64920LF_.dxf_.zip','http://34.220.46.218/wp-content/uploads/2018/11/64920LF_3ds.zip');
	
    # create new zip opbject
    $zip = new ZipArchive();
    //echo'<pre> zip ';print_r($zip);exit;
    # create a temp file & open it
    $tmp_file = tempnam('.','');
    $zip->open($tmp_file, ZipArchive::CREATE);
    # loop through each file
    foreach($file_names as $file){
        # download file
        $download_file = file_get_contents($file);
        #add it to the zip
        $zip->addFromString(basename($file),$download_file);
    }

    # close zip
    $zip->close();
    # send the file to the browser as a download
    header('Content-disposition: attachment; filename=Resumes.zip');
    header('Content-type: application/zip');
    readfile($tmp_file);

But its give error

**Comment by mukeshgithb** [comment]
![2018-12-04_1224](https://user-images.githubusercontent.com/45414177/49424163-cd4d2780-f7bf-11e8-8aa7-effd53fd4cd1.png)

**Comment by johannesschobel** [comment]
can you `dd('test')` right at the controller method that is called and check, if this is correctly outputted? Actually, i believe, that the error message is thrown by `Apache` itself and **not** by your application --> the error happens BEFORE you enter your application

**Comment by sainivijaykumar** [comment]
esap-autm.techvividsystems.com is currently unable to handle this request.
HTTP ERROR 500


can you tell me solution for this issue
