### ISSUE TITLE
Socialauth in social login with facebook

### ISSUE THREAD

**Issue by jaiminrockersinfo** [apiato/apiato#396]
Can you check social login as per our documentation, It's not working. I will try with "auth/facebook" but they given this type of error. 
{
    "status": "error",
    "code": 0,
    "message": "Trying to get property of non-object",
    "status_code": 500
}
Can you help me.

**Comment by johannesschobel** [comment]
Can you try to authenticate directly via `Socialite` and **not** use the Apiato provided `SocialAuth` container?
