### ISSUE TITLE
App\Ship\Parents\Providers\EventsProvider Default  Not Provider 

### ISSUE THREAD

**Issue by yesterday679** [apiato/apiato#404]
in `ApiatoProvier.php` file
~~~php
    public $serviceProviders = [
        // Third Party Packages Providers:
        HashidsServiceProvider::class,
        RepositoryServiceProvider::class,
        CorsServiceProvider::class,
        FractalServiceProvider::class,
        HeimdalExceptionsServiceProvider::class,

        // add the Laravel Tinker Service Provider
        TinkerServiceProvider::class,

        // Internal Apiato Providers:
        EventServiceProvider::class, //The custom apiato eventserviceprovider
        RoutesProvider::class, // exceptionally adding the Route Provider, unlike all other providers in the parents.
        ShipProvider::class, // the ShipProvider for the Ship third party packages.
        GeneratorsServiceProvider::class, // the code generator provider.
    ];
~~~
not include `EventsProvider `

Should add to `ShipProvider.php` by hand ?

**Comment by johannesschobel** [comment]
you can add it on your own, if you need it..
However, you should NOT modify the `apiato/core/...` package, because it will be updated via `composer update` command, thus, resulting on loss of your changes!

However, you can add it to the `ShipProvider` in `App/Ship/Providers/ShipProvider` in order to apply your changes..

**Comment by yesterday679** [comment]
I found a magic thing ， event/listen do not work

---


This is my code:

~~~php
class EventsProvider extends AbstractEventsProvider
{

    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        'SocialiteProviders\Manager\SocialiteWasCalled' => [
            'SocialiteProviders\Weixin\WeixinExtendSocialite',
        ]
    ];


~~~


~~~php
class ServiceProvider extends SocialiteServiceProvider
{
    /**
     * Bootstrap the provider services.
     */
    public function boot()
    {
        $socialiteWasCalled = app(SocialiteWasCalled::class);

        event($socialiteWasCalled);
    }

~~~


---


The program is not interrupted here

~~~php
class WeixinExtendSocialite
{
    /**
     * Register the provider.
     *
     * @param \SocialiteProviders\Manager\SocialiteWasCalled $socialiteWasCalled
     */
    public function handle(SocialiteWasCalled $socialiteWasCalled)
    {
        dd('weixin event test successd');
        $socialiteWasCalled->extendSocialite(
            'weixin', __NAMESPACE__ . '\Provider'
        );
    }
~~~

**Comment by yesterday679** [comment]
How can I solve this problem?  @johannesschobel

**Comment by johannesschobel** [comment]
can you try it like described in the docs here? http://docs.apiato.io/components/events/

**Comment by yesterday679** [comment]
`Event ` and `Listeners` is third party package

like this  http://socialiteproviders.github.io/providers/weixin/

**Comment by johannesschobel** [comment]
but you can "wrap" it in the apiato's `Event`s and `Listener`s ... Can you test it with a minimal example if the normal apiato event/listener feature works? i.e., NOT use the socialite..

**Comment by yesterday679** [comment]
I also think so, even if I download the project again, the listener in API is still not working.

**Comment by johannesschobel** [comment]
are you sure, you have correctly set up apiato and respective (sub)domains? Regarding the issue you describe in #405 this may look like a misconfiguration?!

**Comment by yesterday679** [comment]
Yes, I tried two times and failed.

**Comment by johannesschobel** [comment]
but you stated, that, if you follow the `how to use events` from the docs, it works, right?

Because your `api` and `web` routes may internally use the same logic (e.g., the same `Actions` and `Tasks`). So it should basically work for API and WEB the same way.. That leaves me puzzled..

**Comment by johannesschobel** [comment]
hey @yesterday679 ,

any news on this issue here?

**Comment by johannesschobel** [comment]
closed due to inactivity.. kindly reply in order to re-open this issue
