### ISSUE TITLE
How to find which apiato version

### ISSUE THREAD

**Issue by mifas** [apiato/apiato#406]
Not an Issue, I want to know how to get current apiato version that I'm using?

**Comment by johannesschobel** [comment]
currently, the most reliable approach is to check for the version of `apiato/core` by running `composer show`.. For the latest apiato framework and core versions, these should "correlate".. i.e., if you have `core : 2.4` you will most likely be running `apiato : 7.4`.. if you run `core : 2.2` you will most likely be running `apiato : 2.2`...

**Comment by johannesschobel** [comment]
i know that this is a problem for you guys, sorry about that..
I am quite busy at the moment, but i try to address this in future releases (e.g., add a specific version tag somewhere) ;)

**Comment by mifas** [comment]
Thank you
