### ISSUE TITLE
UPDATE DOCS - .dev setup in /etc/hosts no longer usable

### ISSUE THREAD

**Issue by paymentsandbox** [apiato/apiato#409]
## Expected Behavior

A working local site at `apiato.dev` Following Installation for Dev  `A.1) Using Docker (with Laradock)`

## Actual Behavior

ERR_CONNECT and browser constantly throwing to `https://`

## Steps to Reproduce the Problem

Following Installation for Dev  `A.1) Using Docker (with Laradock)` and change your `etc/hosts`

```
127.0.0.1  apiato.dev
127.0.0.1  api.apiato.dev
127.0.0.1  admin.apiato.dev
```

## Specifications

  - Apiato Version:

## Additional Details

I got everything to work finally after finding this little gem in ```https://superuser.com/questions/565409/chrome-how-to-stop-redirect-from-http-to-https#881431```

> My problem came from having a .dev domain, which was apparently recently registered as a gTLD and put in a commit to Chrome Canary. I found this out from a recent post I came across as I searched for my problem.

> If you have the same problem I do, it appears that the best solution is to change your domain to be something other than .dev. The article suggested .test with a potential solution of .localhost later down the road (via this proposal).

changed /etc/hosts as follows
```
127.0.0.1  apiato.test
127.0.0.1  api.apiato.test
127.0.0.1  admin.apiato.test
```

And suddenly, just like that entering `apiato.test` in my browser loaded the site.

**Comment by johannesschobel** [comment]
.dev is now a valid top level domain, so this is a general issue but not related to apiato..

Changing the domain from .dev to .foobar or whatever should solve this..

Can you give feedback on this?!

**Comment by paymentsandbox** [comment]
Hello yes I changed to `.test` and seems to work now.  Yes general issue pointing out however you documentation encourages us to change `etc/hosts` to:

```
127.0.0.1  apiato.dev
127.0.0.1  api.apiato.dev
127.0.0.1  admin.apiato.dev
```

http://docs.apiato.io/getting-started/installation/

Thank you for quick reply.  new to php, been in elixir and js lately but have to refactor an old php app now.  Looking at frameworks out there was impressed with the modular setup.   looking forward to learning new stuff here.

**Comment by johannesschobel** [comment]
Hey man.. thanks for adding this info..

I have updated the docs accordingly with this PR reflecting your information: https://github.com/apiato/documentation/pull/27

Cheers
