### ISSUE TITLE
App\Containers\User\Contracts\UserRepositoryInterface not found

### ISSUE THREAD

**Issue by kaula1221** [apiato/apiato#411]
## Steps to Reproduce the Problem

  1.Not found  UserRepositoryInterface in the  \App\Containers\User\Contracts\UserRepositoryInterface,but use in the app\Containers\Socialauth\Tasks\FindSocialUserTask

## Specifications

  - Apiato Version:

**Comment by johannesschobel** [comment]
You must be running a really (!!!) really old version of apiato.. We switched a long time ago from using the interfaces.. Try updating to the latest version of apiato..

Furthermore, i am not really sure if the `SocialAuth` containerd worked properly back then..
