### ISSUE TITLE
Not Working - Laravel Social Login using Socialite 

### ISSUE THREAD

**Issue by jaiminrockersinfo** [apiato/apiato#414]
Hello,

Get successfully social token using **Socialite**
After I have generate **access_token** as per **socialite token** but we getting some error from that.
Please check below code for generate **access_token**

``` 
$user_by_id = OAuthUser::where('oauth_id', $user->social_id)->first();

        $user_by_email = User::where('email', $user->email)->first();

        if ($user_by_email) {
            $user = $user_by_email;
        } else if ($user_by_id) {
            $user = $user_by_id;
        } else {
            // Create User
            $user = User::create([
                'name' => $socialite->getName(),
                'email' => $socialite->getEmail(),
            ]);
        }

        $oauthData = OAuthDriver::where('name', $dataProvider->provider)->first();

        if(!$oauthData){
            $createOauthdriver = OAuthDriver::create([
                'name' =>  $dataProvider->provider,
                'active' => 'ACTIVE',
            ]);
        }

        $oauthUser = OAuthUser::firstOrNew([
            'user_id' => $user->id,
            'oauth_id' => $socialite->getId(),
        ]);
        
        $oauthUser->user_id = $user->id;
        $oauthUser->oauth_id = $socialite->getId();
        $oauthUser->access_token = $socialite->token;
        $oauthUser->refresh_token = $socialite->refreshToken;
        $oauthUser->oauth_driver_id = OAuthDriver::where('name', $dataProvider->provider)->first()->id;
        $oauthUser->save();

        $result = Socialite::driver($dataProvider->provider)->stateless()->user();
```

Please give me some solution for that.

**Comment by johannesschobel** [comment]
can you actually provide some information on the problem? what do you expect? what happens? what version are you using? and so on..

**Comment by jaiminrockersinfo** [comment]
=> Socialite version **"laravel/socialite": "^3.0",**
=> Get Successfully token from facebook Socialite after we have generate new  access_token using laravel passport. 
=> When we try with email and passport getting successfully access_token from laravel passport.
but currently we have only user email.
=> In that time we getting some error like this.

[2018-04-25 10:30:41] testing.ERROR: Client error: `POST https://graph.facebook.com/v2.10/oauth/access_token` resulted in a `400 Bad Request` response:
{"error":{"message":"Can't Load URL: \u0a86 URL \u0aa8\u0ac0 \u0aa1\u0acb\u0aae\u0ac7\u0aa8 \u0a8f\u0aaa\u0acd\u0ab2\u0a (truncated...)
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://graph.facebook.com/v2.10/oauth/access_token` resulted in a `400 Bad Request` response:
{\"error\":{\"message\":\"Can't Load URL: \\u0a86 URL \\u0aa8\\u0ac0 \\u0aa1\\u0acb\\u0aae\\u0ac7\\u0aa8 \\u0a8f\\u0aaa\\u0acd\\u0ab2\\u0a (truncated...)
 at /home/rocku21/public_html/apiato/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /home/rocku21/public_html/apiato/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /home/rocku21/public_html/apiato/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /home/rocku21/public_html/apiato/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Promise\\Promise->wait()
#10 /home/rocku21/public_html/apiato/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('post', 'https://graph.f...', Array)
#11 /home/rocku21/public_html/apiato/vendor/laravel/socialite/src/Two/FacebookProvider.php(76): GuzzleHttp\\Client->__call('post', Array)
#12 /home/rocku21/public_html/apiato/vendor/laravel/socialite/src/Two/AbstractProvider.php(212): Laravel\\Socialite\\Two\\FacebookProvider->getAccessTokenResponse(NULL)
#13 /home/rocku21/public_html/apiato/app/Containers/Authentication/Tasks/ApiLoginFromUserTask.php(78): Laravel\\Socialite\\Two\\AbstractProvider->user()
#14 /home/rocku21/public_html/apiato/vendor/apiato/core/Traits/CallableTrait.php(43): App\\Containers\\Authentication\\Tasks\\ApiLoginFromUserTask->run(Object(App\\Containers\\User\\Models\\User), Object(Laravel\\Socialite\\Two\\User), Object(App\\Ship\\Transporters\\DataTransporter))
#15 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Apiato\\Core\\Foundation\\Apiato->call(Object(App\\Containers\\Authentication\\Tasks\\ApiLoginFromUserTask), Array)
#16 /home/rocku21/public_html/apiato/app/Containers/SocialAuth/Actions/SocialLoginAction.php(81): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#17 /home/rocku21/public_html/apiato/vendor/apiato/core/Traits/CallableTrait.php(43): App\\Containers\\SocialAuth\\Actions\\SocialLoginAction->run(Object(App\\Ship\\Transporters\\DataTransporter))
#18 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Apiato\\Core\\Foundation\\Apiato->call(Object(App\\Containers\\SocialAuth\\Actions\\SocialLoginAction), Array)
#19 /home/rocku21/public_html/apiato/app/Containers/SocialAuth/UI/API/Controllers/Controller.php(36): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#20 [internal function]: App\\Containers\\SocialAuth\\UI\\API\\Controllers\\Controller->authenticateAll(Object(App\\Containers\\SocialAuth\\UI\\API\\Requests\\ApiAuthenticateRequest), 'facebook')
#21 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#22 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('authenticateAll', Array)
#23 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Containers\\SocialAuth\\UI\\API\\Controllers\\Controller), 'authenticateAll')
#24 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#25 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
#26 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/rocku21/public_html/apiato/app/Ship/Middlewares/Http/ProfilerMiddleware.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Ship\\Middlewares\\Http\\ProfilerMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/rocku21/public_html/apiato/app/Ship/Middlewares/Http/ProcessETagHeadersMiddleware.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Ship\\Middlewares\\Http\\ProcessETagHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/rocku21/public_html/apiato/app/Ship/Middlewares/Http/ValidateJsonContent.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Ship\\Middlewares\\Http\\ValidateJsonContent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#42 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#43 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#44 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#45 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/rocku21/public_html/apiato/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/rocku21/public_html/apiato/vendor/barryvdh/laravel-cors/src/HandleCors.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/rocku21/public_html/apiato/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#69 /home/rocku21/public_html/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#70 /home/rocku21/public_html/apiato/public/index.php(69): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#71 {main}
"}

**Comment by johannesschobel** [comment]
Hey there...

Before going into detail. can you please format your issues correctly? because you just created a reference for all issues / pull requests `1` up to `71`! There is actually a "Preview" for the post available - please use it in order to verify the correct formatting of your post! :cry: 

The exception, you are showing, reads the following message:
```
{"message":"Can't Load URL: \u0a86 URL \u0aa8\u0ac0 \u0aa1\u0acb\u0aae\u0ac7\u0aa8 \u0a8f\u0aaa\u0acd\u0ab2\u0a ...
```
What URL does it try to load?
