### ISSUE TITLE
Commands are not being registered for tests

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#416]
## Expected Behavior
Commands that are called through Artisan::call() should be executed normally.

## Actual Behavior
When i execute a Artisan::call() from a testcase it says the command is not found.

## Steps to Reproduce the Problem
Create a test and call a command for example:
Artisan::call('user:delete 1');

## Specifications
php 7.2, nginx, apiato 7.4.7

**Comment by johannesschobel** [comment]
Hey @deviouspk ,

actually, that should work.. I just created a test that calls
```
Artisan::call('apiato:welcome');
```

If you want to pass parameters to a command, you need to add them as additional parameters to your `Artisan::call()` method.. Take a look at the official laravel docs: https://laravel.com/docs/5.6/artisan#calling-commands-from-other-commands

Hope this helps!?

**Comment by deviouspk** [comment]
Hi johannes!
Yes i think you are right i passed the parameters in the command name itself instead of an array as extra parameter :) thanks!

**Comment by johannesschobel** [comment]
glad it worked and you can go on with your development ;)
