### ISSUE TITLE
Why not get real_id although logged in by admin on  get all list `Article`

### ISSUE THREAD

**Issue by at-trungtran** [apiato/apiato#423]
## Expected Behavior

I want get real_id when i log in by admin.
## Actual Behavior

I have issue: 
i have an container Article and tranfomer of it:

 ```
......
$response = $this->ifAdmin([
            'real_id'    => $entity->id,
            'deleted_at' => $entity->deleted_at,
        ], $response);
```
On other action (create, update...) i still get real_id if i logged in by admin.
![screen shot 2018-05-09 at 11 30 21 pm](https://user-images.githubusercontent.com/31870796/39827757-16b3090c-53e3-11e8-9f27-b36651d5a396.png)

But in list all article (by get method), i could not get real_id .

![screen shot 2018-05-09 at 11 44 39 pm](https://user-images.githubusercontent.com/31870796/39827731-0bdf446e-53e3-11e8-8152-32098750f951.png)

Can you explain for me why?. thank so much !
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Apiato Version:

**Comment by johannesschobel** [comment]
Hey,

have you ensured that:
1) the user that makes the actual request is an `admin` user? e.g., the `ifAdmin(...)` method is properly called?
2) you have this `isAdmin(...)` block in the `ArticleTransformer` set up correctly? (e.g., you are using the auto-generated transformers)
3) You are really using the `ArticleTransformer` from 2 (see above)

Can you give feedack on this?!

**Comment by at-trungtran** [comment]
yes, i can sure that .
1.i alrealdy log in by admin.I have got real_id when i run create method .
2.This is my tranfomer : 
```
 public function transform(Article $entity)
    {
        $response = [
            'object' => 'Article',
            'id' => $entity->getHashedKey(),
            'title' => $entity->title,
            'slug' => $entity->slug,
            'description' => $entity->description,
            'content' => $entity->content,
            'image_cover' => $entity->image_cover,
            'image_feature' => $entity->image_feature,
            'keywords' => $entity->keywords,
            'created_by' => $entity->created_by,
            'published_by' => $entity->published_by,
            'is_published' => $entity->is_published,
            'enable_comment' => $entity->enable_comment,
            'viewed' => $entity->viewed,
            'created_at' => $entity->created_at,
            'updated_at' => $entity->updated_at,

        ];

        $response = $this->ifAdmin([
            'real_id'    => $entity->id,
            'deleted_at' => $entity->deleted_at,
        ], $response);

        return $response;
    }
```
3. i already used tranfomer
my code : 
```
 public function getAllArticles(GetAllArticlesRequest $request)
    {
        $articles = Apiato::call('Article@GetAllArticlesAction', [$request]);

        return $this->transform($articles, ArticleTransformer::class);
    }
```

**Comment by johannesschobel** [comment]
can you check the `isAdmin()` method.. and just `dd($user)` within this method, after the user is fetched?
If the route you are accessing is **not** protected (e.g., via the `auth:api` middleware), you are **not** getting a `user`, and, therefore, the `isAdmin()` method does nothing..

Is your route protected?

**Comment by at-trungtran** [comment]
I found that i have two route: 1 private and 1 public
`GetAllArticles.v1.private.php`
`GetAllArticles.v1.public.php`
All case of my check, my route /articles still go to public route.
And in public route, i don't have auth:api
That is reason why i don't get real_id.
But, i still don't know ` how to private route work?`.

**Comment by johannesschobel** [comment]
the issue is, that the `public` route is loaded BEFORE the `private` route.. That is, because laravel loads the route "alphabetically ordered" (**pu**blic is before **pr**ivate)!

Check this out: http://docs.apiato.io/components/routes/#difference-between-public-private-routes-files
