### ISSUE TITLE
javascript client inside the container

### ISSUE THREAD

**Issue by baihaqyaviq** [apiato/apiato#424]
what it might be to put the javascript client inside the container, eg in the ui folder,
if yes how to setup its webpack

**Comment by johannesschobel** [comment]
well, i guess this _should_ technically be possible.. however, you would need to use the `web` instead the `api` routes..

I am no expert in frontend development (e.g,. with angular or vue), but i would probably do something like this:
- have one `index` file, that is served to the client interacting with your applicatoin
- have specifically tailored `javascript_import` files that contain all `*.js` of respective container you need.
- "import" this `javascript_import` file(s) in your `index` file.

The browser of the client should load all js files..

It also may be a good idea to have `webpack` in the top-level folder and then "crawl" for all `*.ts / js` files in specific folders of your project. For example, that you say, your `ts` files are located in `app\Containers\*\Resources\js\` . Then you would need to tell webpack to only search these folders..
