### ISSUE TITLE
Model Factory from Unit test does not trigger model events

### ISSUE THREAD

**Issue by denis019** [apiato/apiato#428]
Calling model factory create in unit test
for example
factory(App\User::class)->create() 
Will not trigger Model Events (https://laravel.com/docs/5.6/eloquent#events)
## Steps to Reproduce the Problem
Create the following Observers https://laravel.com/docs/5.6/eloquent#observers
In for example User Container add some User factory and call it from unit tests you
will see that model events are not triggered.
## Specifications
  - Apiato Version: "apiato/core": "dev-master",

## Additional Details
I have tested the same behavior with laravel 5.6 and the events are fired
While debugging this bug in apiato I came to 
The custom apiato eventserviceprovider
\Apiato\Core\Abstracts\Events\Providers\EventServiceProvider
If we comment the loading of this provider in
\Apiato\Core\Providers\ApiatoProvider::$serviceProviders
the model event will be triggered.

Maybe the order of provider register should be different, need more time to debug.
Please advice if you already have a solution.

**Comment by johannesschobel** [comment]
Hey there.. Is this specifically related to Unit-Tests or the model-events in general?

**Comment by denis019** [comment]
When you call the model factory from seeder it's working fine,
only bug is when you have factory model ->create in Unit-Tests
So it's specifically related to Unit-Tests

**Comment by johannesschobel** [comment]
i am not entirely sure,.. but i think, i once read something, that the seeders may "disable" the events.. because usually you want to dump a f*cking lot of data at once.. maybe this can be the issue!?

**Comment by denis019** [comment]
But with seeders is working fine. when you call seeders via CLI not from UnitTests

**Comment by johannesschobel** [comment]
and it works in a regular laravel project? just to cross "phpunit" from the list? ;)

**Comment by denis019** [comment]
In regular laravel project it works.

**Comment by johannesschobel** [comment]
hm, ok.. now i get it - sorry ;)
However, i am currently not able to give any hints where to search for the solution :disappointed: i am very sorry

**Comment by denis019** [comment]
This issue is related with apiato/core, my mistake adding it here

**Comment by johannesschobel** [comment]
thank you very much for the feedback and your time / effort to further investigate this issue! I will take a look at it shortly :+1:

**Comment by denis019** [comment]
@johannesschobel I have create the pull request on apiato/core which will solve this issue.
Please check https://github.com/apiato/core/issues/100

**Comment by johannesschobel** [comment]
î've seen it.. will take a closer look later and then merge.. thanks a lot..

**Comment by johannesschobel** [comment]
i will close the issue here, as we have another issue in `core`.. thanks for reporting this issue!
