### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mkumarjha** [apiato/apiato#431]
when i am trying to install it on ubuntu with php 7.2  i am getting this error 
Problem 1
    - Installation request for wepay/php-sdk 0.3.1 -> satisfiable by wepay/php-sdk[0.3.1].
    - wepay/php-sdk 0.3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - wepay/php-sdk 0.3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - kevinem/wepay-laravel 0.1.0 requires wepay/php-sdk ^0.3 -> satisfiable by wepay/php-sdk[0.3.1].
    - Installation request for kevinem/wepay-laravel 0.1.0 -> satisfiable by kevinem/wepay-laravel[0.1.0].

**Comment by johannesschobel** [comment]
please remove the entire `wepay` container.. If you don't really require it, throw it away..

**Comment by johannesschobel** [comment]
i think, i will drop it in a future release anyway..

**Comment by daspete** [comment]
But as the error message says, you need the php-curl extension in your php installation

**Comment by knightus** [comment]
Have you installed curl extension?
