### ISSUE TITLE
Sanitize relationship one to many or many to many

### ISSUE THREAD

**Issue by johnathansantos** [apiato/apiato#432]
for example request:
```
{
   "category": {
     "id": "1",
     "name": "abc",
     "products": [
       {
         "id": 1,
         "name": "a"
       },
       {
         "id": 1,
         "name": "b"
       }
     ]
   }
}
```
how to apply sanatizeInput to capture the product name?

```
   $ data = $ request-> sanitizeInput ([
       'category.id',
       'category.name',
       'category.products.*.id',
       'category.products.*.name',
]);
```
because `category.products.*.name` does not work

**Comment by johannesschobel** [comment]
The sanitize method does not support wildcards at the moment..

**Comment by johannesschobel** [comment]
You would need to manually walk over the category.products array to get all keys (0, 1, 2, ...) and build your sanitize array...

**Comment by johannesschobel** [comment]
Maybe I can take a look into this next week.. not sure though..

However, sanitizing for `category.products` should give you the requested array with your relationships..

If you want to ensure that the `id` and `name` is present, I would suggest to test for the occurrence in a `Request` class!
