### ISSUE TITLE
Error at seeding project

### ISSUE THREAD

**Issue by aqualaguna** [apiato/apiato#433]
## Expected Behavior
No error at all

## Actual Behavior
got this error when run `php artisan db:seed`.
```
In GuardDoesNotMatch.php line 12:
                                                                      
  The given role or permission should use guard `` instead of `web`.  
````

## Steps to Reproduce the Problem

  1. create env file
  2. composer install
  3. php artisan key:generate
  4. php artisan db:seed

## Specifications

  - Apiato Version: 7.4

**Comment by johannesschobel** [comment]
which version of apiato/core are you using?

**Comment by aqualaguna** [comment]
sory my bad this my configuration error
