### ISSUE TITLE
RuntimeException: Missing BC Math or GMP extension

### ISSUE THREAD

**Issue by Crazymodder** [apiato/apiato#435]
Hi,

## Actual Behavior
In my User Model I added this code to customize the channel where I like to broadcast my notifications:

`public function receivesBroadcastNotificationsOn()
    {
        return 'user.' . $this->getHashedKey('id');
    }`

This code works:
`public function receivesBroadcastNotificationsOn()
    {
        return 'user.' . $this->id;
    }`

If I queue a notification and try to queue:work with beanstalked I got the error message:
**RuntimeException: Missing BC Math or GMP extension**

Everywhere else the Hashing of Ids works fine.

## Expected Behavior
I search for a way to only expose hashed Ids to outside world. Also for the broadcast channels. So that users can subscribe to there private channels with there id and not with the real id.

## Steps to Reproduce the Problem
  1. Create a Notification and use broadcast
  2. Make the Notification Queueable
  3. Add receivesBroadcastNotificationsOn to the notifiable model and try to get the hashed Id for the name
  4. Use beanstalked as queue worker
  5. php artisan queue:work

## Specifications
Laradock 7
Apiato 7.4.7

## Full Stacktrace:
`RuntimeException: Missing BC Math or GMP extension. in /var/www/project/vendor/hashids/hashids/src/Math.php:113
Stack trace:
#0 /var/www/project/vendor/hashids/hashids/src/Hashids.php(157): Hashids\Math::mod(4, 100)
#1 /var/www/project/vendor/graham-campbell/manager/src/AbstractManager.php(241): Hashids\Hashids->encode(4)
#2 /var/www/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): GrahamCampbell\Manager\AbstractManager->__call('encode', Array)
#3 /var/www/project/vendor/apiato/core/Traits/HashIdTrait.php(229): Illuminate\Support\Facades\Facade::__callStatic('encode', Array)
#4 /var/www/project/vendor/apiato/core/Traits/HashIdTrait.php(48): App\Ship\Parents\Models\UserModel->encoder(4)
#5 /var/www/project/app/Ship/Parents/Models/UserModel.php(34): App\Ship\Parents\Models\UserModel->getHashedKey('id')
#6 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/Events/BroadcastNotificationCreated.php(74): App\Ship\Parents\Models\UserModel->receivesBroadcastNotificationsOn(Object(App\Containers\Friendship\Notifications\UserReceivedFriendshipRequestNotification))
#7 /var/www/project/vendor/laravel/framework/src/Illuminate/Notifications/Events/BroadcastNotificationCreated.php(63): Illuminate\Notifications\Events\BroadcastNotificationCreated->channelName()
#8 /var/www/project/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(47): Illuminate\Notifications\Events\BroadcastNotificationCreated->broadcastOn()
#9 [internal function]: Illuminate\Broadcasting\BroadcastEvent->handle(Object(Illuminate\Broadcasting\Broadcasters\RedisBroadcaster))
#10 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /var/www/project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#15 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Broadcasting\BroadcastEvent))
#16 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Broadcasting\BroadcastEvent))
#17 /var/www/project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Broadcasting\BroadcastEvent), false)
#19 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#20 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(322): Illuminate\Queue\Jobs\Job->fire()
#21 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(272): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\BeanstalkdJob), 'beanstalkd', Object(Illuminate\Queue\WorkerOptions))
#23 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('beanstalkd', 'default', Object(Illuminate\Queue\WorkerOptions))
#24 /var/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'default')
#25 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#26 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#27 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#29 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#30 /var/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#31 /var/www/project/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /var/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#33 /var/www/project/vendor/symfony/console/Application.php(865): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/project/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/project/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/project/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/project/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 {main}`

Thanks for your help

Regards
Crazymodder

**Comment by Crazymodder** [comment]
Hi,

I got the solution:

@Mahmoudz @johannesschobel can we update the apiato core package?
So needed version for 

"vinkla/hashids" must set to 5.0.0 than the dependency "hashids/hashids" get updated to version 3.

Regards
Crazymodder

**Comment by johannesschobel** [comment]
thanks.. will update later today..

**Comment by Crazymodder** [comment]
@johannesschobel does version update cause problems?

**Comment by johannesschobel** [comment]
@Crazymodder no, not really.. but didnt had the time.. i updated the core (master and 2.4) can you test please?

**Comment by liuwei0514** [comment]
@Crazymodder I tested，not work. 
my solution is install the  BC Math extension
change  .env    PHP_FPM_INSTALL_BCMATH=true

**Comment by Crazymodder** [comment]
Hi,

I have tested and you are right its not working with the new versions.

**Comment by johannesschobel** [comment]
just a question.. why do you even put the hashed id in the event / notification and not use the "plain" id? because you will need to decode the ID anyway if you want to actually "work" with the data in the event..

**Comment by Crazymodder** [comment]
@johannesschobel because on the listener site (in my frontend app) I only have access to the hashed user id (after fetching userinformation via api call from apiato). So my socket.io client needs to listen on a private channel. Normally you make somethink like
"user.1" but in apiato the real user id gets hashed so the outside world only know the hashed variant of the id. Users can only subscribe to a channel like user.<hashed_id>, which means on the backend site in laravel I need to push now the notification to that channel with name user.<hashed_id>. For doing so I implement the receivesBroadcastNotificationsOn function on the user model which allows you to specify the channel name where notifications show broadcasted on.

If I push notifications to a channel called user.1 I dont need to hash the user id and don't get the exception. The downsite is that I have to publish the real user id in the api response of /users/profile.

**Comment by johannesschobel** [comment]
Ah ok... I get it.. I thought you use this only within your API..
