### ISSUE TITLE
how to implement microservice

### ISSUE THREAD

**Issue by baihaqyaviq** [apiato/apiato#438]
how to implement microservice using apiato, 
as in the case of ecommerce:
[https://thoughtsbyakhil.wordpress.com/2016/03/04/my-funnelwise-microservices-architecture-for-mature-e-commerce-retailers/](url)

**Comment by johannesschobel** [comment]
I don't know if this is possible "out of the box" - for now, I guess, it is not!

**Comment by baihaqyaviq** [comment]
why not?

**Comment by johannesschobel** [comment]
architecture design.. But you may have several "smaller" apiato applications (each with separate containers) and "link" them via HTTP calls

**Comment by baihaqyaviq** [comment]
what is the same as container in apiato with container in docker?

**Comment by johannesschobel** [comment]
a "container" within apiato is a set of "features" that belong to one "domain" (e.g., everything that is related to the `User` model, is within the `User` container). So basically it "packages" everything related to one topic.

a "container" within docker is a "application scope" (e.g., everything related to one application; i.e., a webserver, a database, ...)

check out the official "guide" for the porto pattern, that apiato relies on: 
https://github.com/Mahmoudz/Porto
