### ISSUE TITLE
Logout endpoint documentation is not rendered

### ISSUE THREAD

**Issue by JulianBustamante** [apiato/apiato#444]
## Expected Behavior
- After generating the API docs the documentation and menu item for the logout should be rendered.
- The endpoint GetAllSettings should appear in the Settings group.

## Actual Behavior
- The documentation and menu item for the logout is not rendered.
- GetAllSettings appears in the Setting group.

## Steps to Reproduce the Problem
Just generate the docs.

## Specifications
  - Apiato Version: 7.4

## Additional Details
The params for @api are {method} path [title]. The title is required so that the documentation is rendered.

**Comment by johannesschobel** [comment]
thanks.. can you provide the same PR for the `master` branch as well?

**Comment by johannesschobel** [comment]
thanks!
