### ISSUE TITLE
How to Request Authorization Codes?

### ISSUE THREAD

**Issue by couth** [apiato/apiato#448]
I want to build a Social Authentication project with apiato.
I do follow laraval API Authentication (Passport) docs and find it doesn't work.

`When Requesting Authorization Codes
When requesting an access token using the authorization code grant, consumers should specify their desired scopes as the scope query string parameter. The scope parameter should be a space-delimited list of scopes:

Route::get('/redirect', function () {
    $query = http_build_query([
        'client_id' => 'client-id',
        'redirect_uri' => 'http://example.com/callback',
        'response_type' => 'code',
        'scope' => 'place-orders check-status',
    ]);

    return redirect('http://your-app.com/oauth/authorize?'.$query);
});`

How to Request Authorization Codes? Would you give me an example?

**Comment by johannesschobel** [comment]
you need to pass a `client_secret` as well?! Can you please follow the instructions here:
1) http://docs.apiato.io/getting-started/installation/#Prepare-OAuth
2) http://docs.apiato.io/features/authentication/#login-with-proxy-for-first-party-clients
