### ISSUE TITLE
 Undefined offset: 0 error issue

### ISSUE THREAD

**Issue by rockers007** [apiato/apiato#454]
local.ERROR: Undefined offset: 0 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /home/eventwithtickets/public_html/ratemytaxauditor/vendor/apiato/core/Foundation/Apiato.php:177

**Comment by johannesschobel** [comment]
pretty sure the filename of a file you are trying to load is incorrect (e.g., you are missing the `Action` suffic for an `Action` class)..

Without more details i cannot dig into this issue..
