### ISSUE TITLE
Call to undefined method Apiato\Core\Abstracts\Events\Jobs\EventJob::delay()

### ISSUE THREAD

**Issue by macias67** [apiato/apiato#455]
## Expected Behavior

Execute an event with a delay time of 60 seconds.

## Actual Behavior

Response: 
```
{
    "status": "error",
    "code": 0,
    "message": "Call to undefined method Apiato\\Core\\Abstracts\\Events\\Jobs\\EventJob::delay()",
    "status_code": 500
}
```

 

## Steps to Reproduce the Problem

  1. I created a new event, implemented `ShouldHandle` and `ShouldQueueue` interfaces.
  2. I set the `$jobDelay` attribute to 60 seconds.
  3. I dispatch the event using the helper function within my creation action: 
`event(new RegisteredEvent($model))`

Original class [here](https://gist.github.com/Macias67/f4d8eb1a89cb99e29fdc1f2b4c85b37c).

## Specifications

  - Apiato Version: 7.1
  - Apiato Core: 2.4

## Additional Details

Following the stacktrace log, the error is caused in `vendor\apiato\core\Abstracts\Events\Dispatcher\Dispatcher.php:21`, in line 20, the EventJob class extends from Job, none of them has the `delay` method.

**Comment by johannesschobel** [comment]
i think, we already solved this in slack? is that true?
if so, can you please post the answer here in order to document it publicly?

**Comment by deviouspk** [comment]
https://github.com/apiato/core/pull/120 will probably fix it

**Comment by johannesschobel** [comment]
@deviouspk can you please check, if it actually solves the issue?

**Comment by deviouspk** [comment]
will do tomorrow

**Comment by deviouspk** [comment]
this pull request https://github.com/apiato/core/pull/120 solves all issues.

**Comment by johannesschobel** [comment]
I'll try to take a look at it tomorrow
