### ISSUE TITLE
Possible to create multi auth

### ISSUE THREAD

**Issue by eaponiente** [apiato/apiato#458]
Is it possible to implement multi auth in passport with Apiato? I mean different guards from different table.

user guard = users table
admin guard = admin table

It seems to me it can only be implement on the users model

**Comment by johannesschobel** [comment]
i think, i already answered via slack to this question, right?

I think, I would try to go for a `Role` approach (e.g., provide an additional `admin` `Role` and assign this role to a specific user). Then, in a specific middleware you may check this role.. Note that this check can be also done automatically in the `Request` classes..

Does this help you?!

**Comment by eaponiente** [comment]
@johannesschobel thanks for answering my solution was to create a separate project. since the specifics was to create a separate table for each
