### ISSUE TITLE
composer create-project creates outdated project by default

### ISSUE THREAD

**Issue by autaut03** [apiato/apiato#459]
## Expected Behavior
composer create-project should install 7.4.7 OR 8.0.0 should be updated.

## Actual Behavior
composer create-project, right from docs, installs version 8.0.0, which is older than 7.4.7. 

## Steps to Reproduce the Problem
Run `composer create-project apiato/apiato my-api` as described in the docs.

## Specifications
http://docs.apiato.io/getting-started/installation/

  - Apiato Version: "Latest stable"

**Comment by johannesschobel** [comment]
i just removed the `8.0.0` tag, which may be created by accident.. hope this solves the issue once it is propagated to packagist?!
