### ISSUE TITLE
Can't install any composer package

### ISSUE THREAD

**Issue by autaut03** [apiato/apiato#460]
## Expected Behavior
Install predis/predis

## Actual Behavior
<pre><code>
$ composer require predis/predis                                                
Using version ^1.1 for predis/predis                                            
./composer.json has been updated                                                
Loading composer repositories with package information                          
Updating dependencies (including require-dev)                                   
Your requirements could not be resolved to an installable set of packages.      
                                                                                
  Problem 1                                                                     
    - Conclusion: don't install apiato/core v2.4.8                              
    - Conclusion: don't install apiato/core 2.4.7                               
    - Conclusion: don't install apiato/core v2.4.6                              
    - Conclusion: don't install apiato/core v2.4.5                              
    - Conclusion: don't install apiato/core v2.4.4                              
    - Conclusion: don't install apiato/core v2.4.3                              
    - Conclusion: don't install apiato/core v2.4.2                              
    - Conclusion: don't install apiato/core v2.4.1                              
    - Conclusion: don't install apiato/core v2.4.0                              
    - Can only install one of: apiato/core[2.4.x-dev, dev-master].              
    - Can only install one of: apiato/core[dev-master, 2.4.x-dev].              
    - Can only install one of: apiato/core[2.4.x-dev, dev-master].              
    - Installation request for apiato/core 2.4.* -> satisfiable by apiato/core[2
.4.7, 2.4.x-dev, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.8]
.                                                                               
    - Installation request for apiato/core (locked at dev-master, required as 2.
4.*) -> satisfiable by apiato/core[dev-master].                                 
                                                                                
                                                                                
Installation failed, reverting ./composer.json to its original content.         
</code></pre>

## Steps to Reproduce the Problem

  1. Run `composer create-project apiato/apiato test ~7.4`
  2. Set queues, cache and sessions drivers to `redis`
  3. Try opening the app. It says `Class 'Predis\Client' not found`
  4. Install predis by doing `composer require predis/predis` in project's root

## Specifications

  - Apiato Version: 7.4.7

**Comment by autaut03** [comment]
Same goes for any other package.

**Comment by johannesschobel** [comment]
can you check, if there is a `apiato/core : dev-master` and `apiato/core : 2.4.x` in one of the `composer.json` files?!

**Comment by autaut03** [comment]
There's one entry in Ship's composer.json, 2.4:
`"apiato/core": "2.4.*",`
No other instances of apiato/core found.

**Comment by johannesschobel** [comment]
Can you please remove the `composer.lock` file in the main folder and then run `composer update` again?

**Comment by autaut03** [comment]
Yep, it worked.  `Downgrading apiato/core (dev-master => v2.4.8): Downloading (100%)`

I think composer.lock should be updated in the main repo too, but I might be missing something.

Anyway, thanks for your help!

**Comment by johannesschobel** [comment]
You're welcome
