### ISSUE TITLE
request http://admin.apiato.develop/ don't auto redirect to http://admin.apiato.develop/login

### ISSUE THREAD

**Issue by larawos** [apiato/apiato#461]
### Just fixed App\Containers\Welcome\UI\WEB\Routes\main.php can solved it. :

```
$router->get('/', [
    'as'   => 'get_main_home_page',
    'uses' => 'Controller@sayWelcome',
    'domain' => parse_url(\Config::get('app.url'))['host'],
]);
```

**Comment by johannesschobel** [comment]
the "admin" panel is just a demo how you *could* set it up.. actually, there is no real "content" available ;) Feel free to adapt / implement it as you want..
