### ISSUE TITLE
Correct the templategenerator

### ISSUE THREAD

**Issue by thejoe8495** [apiato/apiato#466]
## Actual Behavior
After generate a new container it creates all files forme. In my fall, i have a wrong tablename so the laravel default model don't find the table. Second i create a default seeder under {container}/data/seeders/containerseeder_1.php
The error on the Commandline was: " Failed to create Resource." the same line comes in laravel.log file. After a short search i found in **/User/Tasks/CreateUserByCredentialsTask.php** the **->debug($e);**
After adding the debug i found the problem in logfile with the wrong tablename.

## Steps to Reproduce the Problem

  1. php artisan apiato:generate:container
  2. Create ClientType <--- Camelcase
  3. Confirm all others with enter
  4. Edit the migrationfile for fields, create name and descrition not nullable
  5. Create a Seederfile in /ClientType/data/seeders/ with the default file and this line: **Apiato::call('ClientType@CreateClientTypeTask', [['User', 'This is a private person']]);**
  6. php artisan migrate --seed

i hope this was it ;)

## Solution
Replace in the Generator this line
throw (new CreateResourceFailedException())->debug($exception);

and by the way Laravel change **CamelCase** in **camel_case** not **camelcase** so please change the generation of migration file also ;)

  - Apiato Version: latest

## Question
How can i create the seeders like the steps above?
the actual line this:
[2018-08-29 15:32:14] local.ERROR: [DEBUG] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `client_types` (`updated_at`, `created_at`) values (2018-08-29 15:32:14, 2018-08-29 15:32:14)) 

this was a good thing for documentation.

**Comment by johannesschobel** [comment]
Apiato requires to have strict naming conventions, so this is an issue with your setup.

You can easily remove the created migration file and create a new one yourselves..

Further, just adding `debug()` only prints additional debug information, which you will most likely not want in your production environment..

If you want to have all created file use your specific style and formatting, you can customize the stubs yourselves.. see the docs for more details.

Finally.. your migration file does not provide a default data for the `name` field, which leads to this error, I guess..

Hope this helps

**Comment by thejoe8495** [comment]
Yes and no,

i can add it but why it is on default at create user task? This is only a suggestion to add it.

Yes the naming convention is the default by laravel when the **Model** is `CamelCase` it search after the table `camel_case`. When i create a container as `CamelCase` the migration need the initial table `camel_case`. This is not only my setup it is default on Laravel

to my missing `name ` field, i create a name field in migration, in my model as fillable and in repository as searchable but the task won't insert it. I tried also `Apiato::call('ClientType@CreateClientTypeTask', [["name" =>'User', "description" =>'This is a private person']]);` the generated file looks completely different to the default task files in apiato. Do I have to change the files like the ones included?
