### ISSUE TITLE
map search field in query params

### ISSUE THREAD

**Issue by jebraieili** [apiato/apiato#467]
Hi
How can map search field like:
api.domain.develop/endpoint?search=title:keyword

in my repository:
protected $fieldSearchable = [
'd_vch_title' => 'like',
];

**Comment by johannesschobel** [comment]
take a look at the underlying repository package: https://github.com/andersao/l5-repository/
please also take a look at the official docs at http://docs.apiato.io/features/query-parameters/#searching
