### ISSUE TITLE
Screenshots in apiato document cannot be viewed

### ISSUE THREAD

**Issue by yelv123** [apiato/apiato#474]
## Expected Behavior

Apiato's document can be captured normally in apiato's document. For example: 
http://docs.apiato.io/features/api-docs-generator/#api-documentation-headers-example
http://docs.apiato.io/features/default-endpoints/

## Actual Behavior

These images are now not visible in your document
## Steps to Reproduce the Problem

1.Just open up the browser
 

## Specifications

  - Apiato Version: all

**Comment by johannesschobel** [comment]
hm, looks like the image has been removed or the img-service is broken / down..

**Comment by Mahmoudz** [comment]
Finally fixed :)
