### ISSUE TITLE
 How to add the configuration of a package in a container

### ISSUE THREAD

**Issue by HandSoftCorp** [apiato/apiato#475]
![screenshot from 2018-09-27 22-30-31](https://user-images.githubusercontent.com/42792349/46186636-389ce980-c2a5-11e8-858e-28f2497b43b0.png)

**Comment by johannesschobel** [comment]
Simply run the provider in order to publish the package configuration. This should then be copied to the default /config folder in Laravel.
Then move it to the respective container config folder..

See the docs for more information
