### ISSUE TITLE
An Exception occurred when trying to authenticate the User

### ISSUE THREAD

**Issue by maliang** [apiato/apiato#476]
I set in .env file
QUERIES_DEBUG=true

I open admin to login. put the email and password click the "login" button
The page show
"An Exception occurred when trying to authenticate the User"

Why? How to fix? Thank you

**Comment by candro** [comment]
You need to add a middleware => ['auth:web']

**Comment by johannesschobel** [comment]
you need to provide more details on this issue..
there may be an include missing..

**Comment by bishal-saha** [comment]
I am also getting the same issue. My system is ubuntu 18 LTS. I copied the repo to document root and followed the steps mentioned at the documentation. I also created the virtual host of domain admin.apiato.develop. 

When I logged in by using the access  admin@admin.com with password admin the page redirected to http://admin.apiato.develop/dashboard    and there I got the error "An Exception occurred when trying to authenticate the User."

Here is the screenshot  https://ibb.co/qY6sFhw

Do you have any idea, how to remove this error? Please let me know.

**Comment by johannesschobel** [comment]
I think this is because in apiato 7.2 (???) the password for the default seeded user is double hashed.. I remember patching such an issue in later versions..

Can you check this please?

**Comment by johannesschobel** [comment]
can you try to verify the possible solution i have described?!

**Comment by Elshaden** [comment]
This issue happens all the time, when first install Apiato, it tends to not recognize the seeded first user,
I think due to Laravel generated Key,
what I do to resolve this,  is create a new user as admin and grant him all permissions, and remove the default Apiato seeded user. all works fine after that.

**Comment by johannesschobel** [comment]
@Elshaden 
i have posted a possible solution how to fix this.. Can you verify this please

**Comment by Elshaden** [comment]
@jaiminrockersinfo I checked, the Seeded default Admin is created the same way as the CLI create Admin command, through the (CreateUserByCredentialsTask), the password only hashed once in the Task.

**Comment by karneaud** [comment]
+1 

I am also getting this message. I even tries the recommendation by @Elshaden 

my logs

> [2019-04-20 03:22:10] local.ERROR: [ERROR] Status Code: 400 | Message: An Exception happened during the Login Process. | Errors:  | Code: 0  
> [2019-04-20 03:23:24] local.INFO: mysql (9.86): select * from `users` where `email` = kendall@black-pearl.local and `users`.`deleted_at` is null limit 1  
> [2019-04-20 03:23:25] local.INFO: mysql (2.18): select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = 2 and `model_has_roles`.`model_type` = App\Containers\User\Models\User  
> [2019-04-20 03:23:25] local.ERROR: [ERROR] Status Code: 401 | Message: An Exception occurred when trying to authenticate the User. | Errors:  | Code: 0  
> 

the trace output 

> 59
> App\Containers\Authentication\Exceptions\AuthenticationException 
> …/app/Ship/Middlewares/Http/Authenticate.php23
> 58
> App\Ship\Middlewares\Http\Authenticate authenticate
> …/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php41
> 57
> Illuminate\Auth\Middleware\Authenticate handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 56
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 55
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/app/Containers/Localization/Middlewares/LocalizationMiddleware.php37
> 54
> App\Containers\Localization\Middlewares\LocalizationMiddleware handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 53
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 52
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php41
> 51
> Illuminate\Routing\Middleware\SubstituteBindings handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 50
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 49
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php67
> 48
> Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 47
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 46
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php49
> 45
> Illuminate\View\Middleware\ShareErrorsFromSession handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 44
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 43
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php63
> 42
> Illuminate\Session\Middleware\StartSession handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 41
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 40
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php37
> 39
> Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 38
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 37
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php59
> 36
> Illuminate\Cookie\Middleware\EncryptCookies handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 35
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 34
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php102
> 33
> Illuminate\Pipeline\Pipeline then
> …/vendor/laravel/framework/src/Illuminate/Routing/Router.php661
> 32
> Illuminate\Routing\Router runRouteWithinStack
> …/vendor/laravel/framework/src/Illuminate/Routing/Router.php636
> 31
> Illuminate\Routing\Router runRoute
> …/vendor/laravel/framework/src/Illuminate/Routing/Router.php602
> 30
> Illuminate\Routing\Router dispatchToRoute
> …/vendor/laravel/framework/src/Illuminate/Routing/Router.php591
> 29
> Illuminate\Routing\Router dispatch
> …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php176
> 28
> Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php30
> 27
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php65
> 26
> Barryvdh\Debugbar\Middleware\InjectDebugbar handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 25
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 24
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/barryvdh/laravel-cors/src/HandleCors.php36
> 23
> Barryvdh\Cors\HandleCors handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 22
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 21
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/fideloper/proxy/src/TrustProxies.php57
> 20
> Fideloper\Proxy\TrustProxies handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 19
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 18
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php30
> 17
> Illuminate\Foundation\Http\Middleware\TransformsRequest handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 16
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 15
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php30
> 14
> Illuminate\Foundation\Http\Middleware\TransformsRequest handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 13
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 12
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php27
> 11
> Illuminate\Foundation\Http\Middleware\ValidatePostSize handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 10
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 9
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php46
> 8
> Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
> …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
> 7
> Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
> …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
> 6
> Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
> …/app/Containers/Debugger/Middlewares/RequestsMonitorMiddleware.php27

Docker with php 7.3
using Laravel Framework 5.6.7

**Comment by Elshaden** [comment]
Hi @karneaud 
this not an error, this is an exception for not able to authenticate the user,
it is coming from :
App\Containers\Authentication\Exceptions\LoginFailedException

it is the wrong username or password.

try create a new user in CLI
php artisan apiato:create:admin

and try to login with this, as Admin. 

let me k now if you have a problem

**Comment by karneaud** [comment]
> try create a new user in CLI
> php artisan apiato:create:admin

strange as I did try this and I believe I did use the correct password. Would give it another go

**Comment by karneaud** [comment]
@Elshaden 

Took the steps you suggested and the same thing happened.....i used a simple password "admin" and i entered it correctly and the same thing happened. Would anything from the installation setup cause this malfunction?

**Comment by karneaud** [comment]
I note the following query 

select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = '3' and `model_has_roles`.`model_type` = 'App\Containers\User\Models\User'

yields no results..... yet

select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = '3' and `model_has_roles`.`model_type` = 'App\\Containers\\User\\Models\\User'

would yield the expected result....I assume the model_type is being "Escaped"?

**Comment by karneaud** [comment]
ok. Not sure what the bug is here but will look at this again when its out of beta. Thanks.

**Comment by Elshaden** [comment]
do you have a role with Id =3?
check db table roles

**Comment by Elshaden** [comment]
you must have in roles table a role with id = 3
and in model_has_role a user with role_id = 3

**Comment by karneaud** [comment]
@Elshaden I don't follow? Why would there be a **Role** with *id=3*? There is a **Model** with an *id=3* and a **Role** with *id=1*

**Comment by Elshaden** [comment]
I am sorry I am confused,
Your model_id is your id in App\Containers\User\Models\User  users table
the role_id is the role 
in case of admin

model_id = 3
and role_id = 1
in model has roles table

**Comment by Elshaden** [comment]
if this is the case in DB
 model_id = 3
and role_id = 1

you should be able to login with no problems
other possible Causes:
APP_KEY in .env   try to generate again by using  php artisan key:generate

APP_URL  should be the same as your  application in .env

**Comment by karneaud** [comment]
@Elshaden 

I'm sorry. Did this like 100 times....same result. 

Where does the following sql statement run from?

> select roles.*, model_has_roles.model_id as pivot_model_id, model_has_roles.role_id as pivot_role_id, model_has_roles.model_type as pivot_model_type from roles inner join model_has_roles on roles.id = model_has_roles.role_id where model_has_roles.model_id = '3' and model_has_roles.model_type = 'App\Containers\User\Models\User'

**Comment by Elshaden** [comment]
try dd() in App\Containers\Authentication\Tasks\WebLoginTask
as in below see what you get,

public function run(string $email, string $password, bool $remember = false) : Authenticatable
    {

 _**dd(Auth::attempt(['email' => $email, 'password' => $password]);**_

        if (!$user = Auth::attempt(['email' => $email, 'password' => $password], $remember)) {
            throw new LoginFailedException();
        }

        return Auth::user();
    }

**Comment by karneaud** [comment]
@Elshaden 

The results yielded 

> "mysql (9.11): select * from `users` where `email` = kendall@admin.com and `users`.`deleted_at` is null limit 1"
> true

**Comment by Elshaden** [comment]
**true**,
so you are logged in, 
now try dd() in 
App\Containers\Authentication\UI\WEB\Controllers\Controller

 public function viewDashboardPage(ViewDashboardRequest $request)
    {
        **dd($request);**
        return view('authentication::dashboard');
    }

**Comment by Elshaden** [comment]
I assume you are in WEB not API???

**Comment by karneaud** [comment]
@Elshaden I can't get that far as I'm experiencing the error as stated....

> App \ Containers \ Authentication \ Exceptions \ AuthenticationException
> An Exception occurred when trying to authenticate the User.

**Comment by Elshaden** [comment]
OK
Back in the Task
DD()
 public function run(string $email, string $password, bool $remember = false) : Authenticatable
    {
        if (!$user = Auth::attempt(['email' => $email, 'password' => $password], $remember)) {
            throw new LoginFailedException();
        }
 **dd(Auth::user());**
        return Auth::user();
    }

**Comment by Elshaden** [comment]
![Capture](https://user-images.githubusercontent.com/33955172/56473688-e274db00-646e-11e9-9218-22fcac82474c.GIF)

 do you have in Role table first row as in the image

**Comment by karneaud** [comment]
The results rom your lass suggestion yielded

> "mysql (9.58): select * from `users` where `email` = kendall@admin.com and `users`.`deleted_at` is null limit 1"
> User {#634 ▼
>   #table: "users"
>   #fillable: array:18 [▶]
>   #casts: array:2 [▶]
>   #dates: array:3 [▶]
>   #hidden: array:2 [▶]
>   #connection: "mysql"
>   #primaryKey: "id"
>   #keyType: "int"
>   +incrementing: true
>   #with: []
>   #withCount: []
>   #perPage: 15
>   +exists: true
>   +wasRecentlyCreated: false
>   #attributes: array:23 [▶]
>   #original: array:23 [▶]
>   #changes: []
>   #dateFormat: null
>   #appends: []
>   #dispatchesEvents: []
>   #observables: []
>   #relations: []
>   #touches: []
>   +timestamps: true
>   #visible: []
>   #guarded: array:1 [▶]
>   #rememberTokenName: "remember_token"
>   #forceDeleting: false
>   -skippedEndpoints: []
>   #accessToken: null
> }

**Comment by Elshaden** [comment]
so up to here you are OK, no exception,
 
it is to do with Authenticating the Role in 
App\Containers\Authentication\UI\WEB\Requests\ViewDashboardRequest

protected $access = [
        'roles'       => '**admin**',
        'permissions' => '',
    ];

if you cannot see this it is the problem
if you can try to remove admin and check try

**Comment by karneaud** [comment]
@Elshaden 

The above code is present and the issue is the same....regardless if it is there or not


the following yields **_null_** though when attempting again

> class Authenticate extends LaravelAuthenticate
> {
> 
>     public function authenticate(array $guards)
>     {
>     	dd(\Auth::user());

**Comment by Elshaden** [comment]
try {
            return parent::authenticate($guards);
        }
        catch (Exception $exception) {
            **dd($exception);**
            throw new AuthenticationException();
        }

**Comment by karneaud** [comment]
@Elshaden 

I think I figured out what was happening...

I had API_DEBUG = true and REQUEST_DEBUG = true which seemed to interefere with the flow for authentication. turning them off rectified my issue. 

Should I be seeing a "Welcome Admin" page or an actual "Dashboard"??? 


Thanks for your help!

**Comment by Elshaden** [comment]
OK it is REQUEST_DEBUG causing this?

**Comment by Elshaden** [comment]
that is the Dashboard,
you can replace with your own Blade

**Comment by karneaud** [comment]
@Elshaden 

My error it is the **QUERIES_DEBUG** that caused the issue **NOT REQUEST_DEBUG**

**Comment by Elshaden** [comment]
Glad you solved the prb
Apiato is great for API applications, with web too, but you would want to use laravel for web frontend side, and just use the API's to Apiato for all your backend.

**Comment by deviouspk** [comment]
Also for debugging queries/requests/.. try to use telescope:
https://laravel.com/docs/5.8/telescope

**Comment by kalsolio** [comment]
> @Elshaden
> 
> I think I figured out what was happening...
> 
> I had API_DEBUG = true and REQUEST_DEBUG = true which seemed to interefere with the flow for authentication. turning them off rectified my issue.
> 
> Should I be seeing a "Welcome Admin" page or an actual "Dashboard"???
> 
> Thanks for your help!

yes, debug = true ? bad : run

**Comment by Elshaden** [comment]
@kalsolio 
If you should see Welcome Page with Apiato and links to documentation just like Laravel Welcome page, if you log in you should see Welcome Admin and that is the dashboard. nothing else. you need to create your own web dashboard .
