### ISSUE TITLE
Email confirmation does not work, or I don't know how to use it

### ISSUE THREAD

**Issue by zmaren** [apiato/apiato#480]
## Expected Behavior
When I tried to login through **/oauth/token route** I expected to see 403 error, but I got token.

## Actual Behavior
I set **require_email_confirmation** to true, and when I tried to login, I got token without 403 error that my mail is not confirmed.

## Specifications
Using latest 7.4 version, on Ubuntu 18.04 with Apache server

**Comment by johannesschobel** [comment]
You are using the wrong route for login.. the /oauth/token route should not be used for clients to login..

Use the proxy login function.. please see the docs for more info

**Comment by zmaren** [comment]
This did the trick. Put function in User model.

`    public function validateForPassportPasswordGrant($password)
    {
        if ($this->confirmed) {
            return Hash::check($password, $this->getAuthPassword());
        } else {
            return false;
        }
    }`

**Comment by ab192130** [comment]
I have same problem. How can I make my app to send an email confirmation code when an user registers instead of just a "Welcome" email?

**Comment by yalsicor** [comment]
Please do not post to old and closed issues. Do open a new issue and provide more information about the problem you encounter.
