### ISSUE TITLE
Expired/Invalid token usage when performing Reset Password doesn't return Exception

### ISSUE THREAD

**Issue by rmdwirizki** [apiato/apiato#481]
## Expected Behavior

When you resetting password via API endpoint `/v1/password/reset` using an **expired** reset token, this should return an exception

## Actual Behavior

Instead of exception, it just returned 204 http status which is a default success action behaviour

## Steps to Reproduce the Problem

  1. Claim new reset token from endpoint `v1/password/forgot`
  2. Get the reset token from your email or `laravel.log`
  3. Wait until token expired (default is 60 minutes) or just use any random invalid token
  4. Issue a reset password from endpoint `v1/password/reset` using that token

## Specifications

  - Apiato Version: 7.4

## Additional Details

I have temporary fix by updating this updating this file `app/Containers/User/Actions/ResetPasswordAction.php` into:
```php
<?php

namespace App\Containers\User\Actions;

use App\Ship\Exceptions\InternalErrorException;
use App\Ship\Parents\Actions\Action;
use App\Ship\Parents\Exceptions\Exception;
use App\Ship\Transporters\DataTransporter;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Str;

/**
 * Class ResetPasswordAction
 *
 * * @author  Sebastian Weckend
 */
class ResetPasswordAction extends Action
{

    /**
     * @param \App\Ship\Transporters\DataTransporter $data
     */
    public function run(DataTransporter $data): void
    {
        $data = [
            'email'                 => $data->email,
            'token'                 => $data->token,
            'password'              => $data->password,
            'password_confirmation' => $data->password,
        ];

        try {
            $result = Password::broker()->reset(
                $data,
                function ($user, $password) {
                    $user->forceFill([
                        'password'       => Hash::make($password),
                        'remember_token' => Str::random(60),
                    ])->save();
                }
            );
            // ----------------
            // TEMPORARY FIX
            // ----------------
            if ($result == Password::INVALID_TOKEN || 
                $result == Password::INVALID_USER ||
                $result == Password::INVALID_PASSWORD) {
                throw new InternalErrorException();
            }
            // ----------------
            // /TEMPORARY FIX
            // ----------------
        } catch (Exception $e) {
            throw new InternalErrorException();
        }
    }
}
```
I think, it should return a new type of exception (ex: InvalidTokenException) instead of returning internal error, because this fix still lack of information for third party API consumer.

**Comment by johannesschobel** [comment]
i highly suggest to not use the default reset / forget password feature. This feature is, at least in my opinion, broken by design..

**Comment by rmdwirizki** [comment]
Should I make a pull request for my temporary fix above though? IMO reset / forget password is such a basic authentication feature that must be exist for a framework such as Apiato, it's not a problem if the design is currently broken, at least it must be **functional** first and cover a list of standard use case. And _the usage of invalid token_ is one of them.
