### ISSUE TITLE
Sorting related tables error duplicates join

### ISSUE THREAD

**Issue by baihaqyaviq** [apiato/apiato#482]
in request `orderBy=sias_peserta_didik:peserta_didik_id|sias_peserta_didik.nisn&sortedBy=asc` 
i get error:

`code: "42000"
exception: "Illuminate\Database\QueryException"
file: "D:\WWW\sias\vendor\laravel\framework\src\Illuminate\Database\Connection.php"
line: 664
message: "SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'sias_peserta_didik' (SQL: select count(*) as aggregate from `sias_peserta_didik_rombel` left join `sias_peserta_didik` on `sias_peserta_didik_rombel`.`peserta_didik_id` = `sias_peserta_didik`.`id` left join `sias_peserta_didik` on `sias_peserta_didik_rombel`.`peserta_didik_id` = `sias_peserta_didik`.`id`)"
status: "error"
status_code: 500`

**the duplicate join:**
`select count(*) as aggregate from `sias_peserta_didik_rombel`
left join `sias_peserta_didik` on `sias_peserta_didik_rombel`.`peserta_didik_id` = `sias_peserta_didik`.`id` left join `sias_peserta_didik` on `sias_peserta_didik_rombel`.`peserta_didik_id` = `sias_peserta_didik`.`id`

**Comment by johannesschobel** [comment]
This issue is most likely related to `l5-repository` package which handles parsing the request params and mapping it to a Eloquent query.

Can you try opening an issue there and fixing the problem in the respective package?

All the best

**Comment by baihaqyaviq** [comment]
thankyou for respones, yes i create issue to l5-repository, 
[https://github.com/andersao/l5-repository/issues/572](url)
