### ISSUE TITLE
API exceptions rendered as html string when accept json request header is missing

### ISSUE THREAD

**Issue by calin-berbecaru** [apiato/apiato#483]
## Expected Behavior
Exception rendered as JSON, as the response Content-Type header is always 'application/json'

## Actual Behavior
When you hit an API endpoint which throws an exception and the 'Accept: application/json' header is missing, the exception is rendered as html string.

## Steps to Reproduce the Problem

  1. apiato 7.4 fresh install
  2. hit http://api.apiato.develop/v1/users with a browser
  3. exception is rendered as html, but  'Content-Type: application/json' header is set

## Specifications

  - Apiato Version: 7.4

## Additional Details

Because the response is always json, but it is allowed to GET an API endpoint without setting the 'Accept' header and without forcing it in config (`'apiato.requests.force-accept-header' => false`), the exception is rendered by Laravel

Code in \Ship\Exceptions\Handlers\ExceptionsHandler.php

    public function render($request, Exception $e)
    {
        // if the user expects json or the API forces the user to send it
        if (($request->expectsJson()) || (Config::get('apiato.requests.force-accept-header'))) {
            // return the error as json
            return parent::render($request, $e);
        }

        // neither the user nor the application wants json
        return LaravelExceptionHandler::render($request, $e);
    }

## Temporary Fix
Code in \Ship\Middlewares\Http\ValidateJsonContent.php

    // check if the accept header is set to application/json
    if (strpos($acceptHeader, $contentType) === false) {
        // if forcing users to have the accept header is enabled, then throw an exception
        if (Config::get('apiato.requests.force-accept-header')) {
            throw new MissingJSONHeaderException();
        } else {
            // ========= TEMPORARY FIX ===========
            $request->headers->set('Accept', $contentType);
        }
    }

**Comment by TheGodFather05** [comment]
i think the solution can be improved like this:
` public function render($request, Exception $exception)
    {
      $contentType = 'application/json';
      if (str_starts_with($request->url(), "http://api") || str_starts_with($request->url(), "https://api")) {
        $request->headers->set('Accept', $contentType);
      }
        return parent::render($request, $exception);
    }`
