### ISSUE TITLE
transformer withMeta not added meta data

### ISSUE THREAD

**Issue by baihaqyaviq** [apiato/apiato#485]
in this case, i see documentation in [http://docs.apiato.io/components/controllers/#controller-response-builder-helper-functions](url) :
$metaData = ['total_credits', 10000];
return $this->withMeta($metaData)->transform($receipt, ReceiptTransformer::class);

in the returned meta data is not added total_credit.

**Comment by hfengshan** [comment]
yes， this is a useless function, you can modify like this

```
$this->metaData = [
			'meta'    => [
				'include' => $transformer->getAvailableIncludes(),
				'custom'  => array_merge($this->custom, $meta),

public function withCustom(array $data)
	{
		$this->custom = $data;

		return $this;
	}
```
