### ISSUE TITLE
 Has the project stopped updating? How to plan next. happy New Year!

### ISSUE THREAD

**Issue by Osub** [apiato/apiato#486]
Has the project stopped updating? How to plan next. happy New Year!

**Comment by narwy** [comment]
Time to clone the repo and start our own version 😃

**Comment by edwsno29** [comment]
Be more patient! Happy New Year!

**Comment by PrimozRome** [comment]
Also waiting for Laravel 5.7 support. Any upgrade roadmap for Apiato?

**Comment by hungnm1518** [comment]
> Also waiting for Laravel 5.7 support. Any upgrade roadmap for Apiato?

You can manually upgrade to version 5.7 manually. I have just upgraded successfully to Laravel v5.7

**Comment by PrimozRome** [comment]
@hungnm1518 did you had to do something special or you just upgraded Laravel and it worked?

**Comment by hungnm1518** [comment]
@PrimozRome
1. Edit in app/Containers/SocialAuth/composer.json
Change "laravel/socialite": "^3.0" to "laravel/socialite": "^3.2"
2. Edit in app/Containers/Stripe/composer.json
Change "cartalyst/stripe-laravel": "~8.0" to "cartalyst/stripe-laravel": "~9.0"
3. Edit in app/Ship/composer.json
Add a new repositories
`  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/k2inno-tech/core"
    }
  ],`
And change   "barryvdh/laravel-ide-helper": "2.4.*" to "barryvdh/laravel-ide-helper": "2.5.*"
4. Edit in root composer.json
Change "laravel/framework": "5.6.*" to "laravel/framework": "5.7.*",
Run composer update. so, Laravel has been upgraded to version 5.7 :D

**Comment by jjag3r** [comment]
@hungnm1518 can you merge this pull request to your package: [https://github.com/apiato/core/pull/124](Pull request)

**Comment by hungnm1518** [comment]
> @hungnm1518 can you merge this pull request to your package: [apiato/core#124](https://github.com/apiato/core/pull/124)

Yes, I have merged this pull request into my package. You can use my package in step 3

 Edit in app/Ship/composer.json
    Add a new repositories
    ` "repositories": [ { "type": "vcs", "url": "https://github.com/hungnm1518/core" }   ],`

**Comment by mrdionjr** [comment]
Hi @johannesschobel , please any update on this?

**Comment by johannesschobel** [comment]
hey @mrdionjr ,
sorry for the long response times.. currently, i don't have any time to update / work on apiato because i am quite heavy involved here at our university. Furthermore, my main interest has shifted from PHP to TypeScript for now..

**Comment by deviouspk** [comment]
After working with apiato for over a year and making some contributions. I've been working on my own version of a laravel api framework for months now. Functionality and structure wise It's quite similar to apiato (used apiato as inspiration to create it) but written from scratch with a specific structure in mind making it much more maintainable and causing a lot less overhead making it much faster than apiato and performance wise much closer to a default laravel install. However i would need a few weeks to create separate packages for the individual components and also to write all the documentation. If someone is interested in it and wants to help me finish it and write documentation i'll be happy to walk you through it.

**Comment by jalvarez-mrq** [comment]
Hi @johannesschobel !! I saw your contributions on PHP OS projects, just curious about your language choice, I'm currently deciding to learn GoLang, would be interesting to hear about your language shift, can you please share your thoughts?

Thank you!!

**Comment by johannesschobel** [comment]
Hey @jalvarez-mrq , i recently switched for a smaller project to `NestJS` ( https://github.com/nestjs/nest ), which is a framework built upon the famous `express` framework known from `NodeJS`.

`NestJS`, however, is fully written in TypeScript ("object oriented JavaScript), and enables you to fully use the latest features of TypeScript. It comes with features known from other established frameworks, concepts are very similar..

I can highly (!) recommend this framework (`NestJS`) and the language (`TypeScript`) in general!

**Comment by llstarscreamll** [comment]
Cool!! Thank you!!

**Comment by adcuz** [comment]
Will access be given to someone who is willing to continue to maintain the package?

**Comment by ralphstodomingo** [comment]
Would be interested to take part in maintaining this project, too. We could form a group that tackles issues and PRs, and if @johannesschobel and @Mahmoudz could keep at least minimal activity in handing out general direction and things to look out for, I think that would be enough.

**Comment by ralphstodomingo** [comment]
@adcuz @hungnm1518  Interested to hear your thoughts. There's also @parse-code who's recently made changes in his own fork

**Comment by ralphstodomingo** [comment]
@johannesschobel @Mahmoudz interested to hear your thoughts still

**Comment by hungnm1518** [comment]
I've just made some changes to upgrade Apiato to work with Laravel 5.8. 
In addition, I have n't developed any new functionality with the original Apiato

**Comment by Gazzx** [comment]
@hungnm1518 thanks for the 5.8 update. I cloned your repo last week to test it but i got so many fails in the unit tests 
examples : 
```
36) App\Containers\User\UI\API\Tests\Functional\GetAllUsersTest::testGetAllUsersByNonAdmin_
Expected status code 403 but received 500.
Failed asserting that false is true.

/builds/api-projects/snb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/builds/api-projects/snb/app/Containers/User/UI/API/Tests/Functional/GetAllUsersTest.php:61

37) App\Containers\User\UI\API\Tests\Functional\GetAllUsersTest::testSearchUsersByName
Expected status code 200 but received 500.
Failed asserting that false is true.

/builds/api-projects/snb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/builds/api-projects/snb/app/Containers/User/UI/API/Tests/Functional/GetAllUsersTest.php:85

38) App\Containers\User\UI\API\Tests\Functional\UpdateUserTest::testUpdateExistingUser_
Expected status code 200 but received 500.
Failed asserting that false is true.

/builds/api-projects/snb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/builds/api-projects/snb/app/Containers/User/UI/API/Tests/Functional/UpdateUserTest.php:41

39) App\Containers\User\UI\API\Tests\Functional\UpdateUserTest::testUpdateNonExistingUser_
Expected status code 422 but received 500.
Failed asserting that false is true.

/builds/api-projects/snb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/builds/api-projects/snb/app/Containers/User/UI/API/Tests/Functional/UpdateUserTest.php:69

40) App\Containers\User\UI\API\Tests\Functional\UpdateUserTest::testUpdateExistingUserWithoutData_
Expected status code 422 but received 500.
Failed asserting that false is true.

/builds/api-projects/snb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/builds/api-projects/snb/app/Containers/User/UI/API/Tests/Functional/UpdateUserTest.php:85

41) App\Containers\User\UI\API\Tests\Functional\UpdateUserTest::testUpdateExistingUserWithEmptyValues
Expected status code 422 but received 500.
Failed asserting that false is true.
```
I tried to run "composer update" and nothing worked anymore.

**Comment by hungnm1518** [comment]
@Gazzx Sorry for this issue. This error has occurred because (maybe) I forgot to delete file "composer.lock" on my repo. Try deleting this file before running the "Composer install" command to make sure to download Laravel 5.8.*

**Comment by incy247** [comment]
I'm having some issues running test cases on your forked apiato/core @hungnm1518 (I think its just missing the return type declarations)

`php vendor/bin/phpunit
PHP Fatal error:  Declaration of Apiato\Core\Abstracts\Tests\PhpUnit\TestCase::setUp() must be compatible with Illuminate\Foundation\Testing\TestCase::setUp(): void in /var/www/html/api/vendor/apiato/core/Abstracts/Tests/PhpUnit/TestCase.php on line 22`

**Comment by hungnm1518** [comment]
> I'm having some issues running test cases on your forked apiato/core @hungnm1518 (I think its just missing the return type declarations)
> 
> `php vendor/bin/phpunit PHP Fatal error: Declaration of Apiato\Core\Abstracts\Tests\PhpUnit\TestCase::setUp() must be compatible with Illuminate\Foundation\Testing\TestCase::setUp(): void in /var/www/html/api/vendor/apiato/core/Abstracts/Tests/PhpUnit/TestCase.php on line 22`

You should try changing in Apiato\Core\Abstracts\Tests\PhpUnit\TestCase.php
 `protected function setUp()`
to
` public function setUp()`

**Comment by hungnm1518** [comment]
> I'm having some issues running test cases on your forked apiato/core @hungnm1518 (I think its just missing the return type declarations)
> 
> `php vendor/bin/phpunit PHP Fatal error: Declaration of Apiato\Core\Abstracts\Tests\PhpUnit\TestCase::setUp() must be compatible with Illuminate\Foundation\Testing\TestCase::setUp(): void in /var/www/html/api/vendor/apiato/core/Abstracts/Tests/PhpUnit/TestCase.php on line 22`

You should try changing in `/apiato/core/Abstracts/Tests/PhpUnit/TestCase.php `
`protected function setUp(): void`
`protected function tearDown(): void`

**Comment by kovai** [comment]
> > Also waiting for Laravel 5.7 support. Any upgrade roadmap for Apiato?
> 
> You can upgrade to version 5.7 manually. I have just upgraded successfully to Laravel v5.7

Have you upgrade to Laravel 5.8?

**Comment by deviouspk** [comment]
For everyone that wants to keep track of my replacement project for apiato:
here's the repository:
https://github.com/larapie/larapie

It's nowhere near finished at the moment:
But i'm slowly adding all the features apiato has but without the overhead and complexity.
The design is heavily inspired on nwidart modules & apiato. But the porto architecture is ditched.

I would love to get some feedback if someone finds the time to take a look.

**Comment by ralphstodomingo** [comment]
@deviouspk Let's get in touch? I'm interested to see how I can contribute.

**Comment by deviouspk** [comment]
Hi!
please contact me on aamining2@gmail.com
or discord? https://discord.gg/87ReVGK

**Comment by Mahmoudz** [comment]
Hi all, excuse my late reply.
Yes the project is still going, I'm just no longer dedicating much time for it or any other open source.

**Please let me know if you want to become an admin and take this project further.**

@Osub @narwy @edwsno29 @mrdionjr @ralphstodomingo @adcuz @parse-code @hungnm1518 @deviouspk ...
