### ISSUE TITLE
Laravel 5.6 Security Fixes ended on February 7th, 2019

### ISSUE THREAD

**Issue by andrekutianski** [apiato/apiato#489]
## Expected Behavior
Laravel 5.6 reach the end of security fixes on February 7th, 2019. There is any roadmap to upgrade to Laravel 5.7?

  - Apiato Version: 7.4

## Additional Details
The last upgrade of Laravel on Apiato project occurs on #374

**Comment by Osub** [comment]
@johannesschobel   @Mahmoudz

**Comment by hungnm1518** [comment]
You can manually upgrade to version 5.7 manually. I have successfully upgraded to Laravel version 5.7

**Comment by Elshaden** [comment]
@hungnm1518 can you please share what needs to be updated in Apiato to work in laravel 5.7.

**Comment by hungnm1518** [comment]
> @hungnm1518 can you please share what needs to be updated in Apiato to work in laravel 5.7.
@Elshaden You can read my tutorial here. You should try with a blank project for testing.
https://github.com/apiato/apiato/issues/486#issuecomment-465506165
