### ISSUE TITLE
Request data slow

### ISSUE THREAD

**Issue by liezu** [apiato/apiato#490]
It takes about 3-5 seconds to request a piece of data
![image](https://user-images.githubusercontent.com/11386915/52760253-da9d5280-3049-11e9-895e-68311d077b8b.png)

**Comment by liezu** [comment]
Use of laradock

**Comment by johannesschobel** [comment]
may be related to your setup.. requests on my development machine usually takes 200 - 500ms, depending on the amount of DB queries..
however, i do not use laradock but have a "plain installation" on my dev machine..

**Comment by liezu** [comment]
> may be related to your setup.. requests on my development machine usually takes 200 - 500ms, depending on the amount of DB queries..
> however, i do not use laradock but have a "plain installation" on my dev machine..

Thank you very much for your reply! Next I'll try to test it in a different environment.
