### ISSUE TITLE
Not Acceptable (Vue.js)

### ISSUE THREAD

**Issue by promistrio** [apiato/apiato#491]
I try to get token from http://api.apiato.develop/v1/oauth/token. It very easy from postman but it's unreal using axios. Every request give 406 Not Acceptable

## Steps to Reproduce the Problem

  1. Use this code 
```
const requestBody = {
        username: 'admin%40admin.com',
        password: 'admin',
        client_id: '2',
        client_secret: 'g5Dqr0mhigPwh4SJKZ8b5La9Fd90vWHA4B7asdaef',
        grant_type: 'password',
        scope: '',
      }
      const config = {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'accept': 'application/json',
        }
      }
      axios.post('http://api.apiato.develop/v1/auth/token',
        requestBody,
        config)
        .then(response => {
          console.log(response)
        })
```

  2. Go to console
![image](https://user-images.githubusercontent.com/6287944/52914557-f703ee00-32da-11e9-99ca-5a2e63f743d2.png)

![image](https://user-images.githubusercontent.com/6287944/52914676-5b737d00-32dc-11e9-81c3-60469fb764c4.png)

How does this relate to social authorization

## Specifications

vuestic https://github.com/epicmaxco/vuestic-admin
npm run surve (localhost:8080)

api domain: "api.apiato.develop"

**Comment by johannesschobel** [comment]
Don't send data as x-www-form-encoded but as application/json

**Comment by promistrio** [comment]
> Don't send data as x-www-form-encoded but as application/json

Could you give an example? I try replace x-www-form-encoded on application/json and got the same

**Comment by johannesschobel** [comment]
Hey there..

1) try rebuilding the *exact same* request as in postman, if this request works for you
2) you should **not** use the `/oauth/token` routes (provided by passport) directly. instead, please use a proxy login (e.g., http://docs.apiato.io/features/authentication/#login-with-proxy-for-first-party-clients )

All the best
