### ISSUE TITLE
How to force return exceptions via ajax in json format

### ISSUE THREAD

**Issue by hungnm1518** [apiato/apiato#493]
## Expected Behavior

I'm trying to work with apiato. In my web UI, I want to send data to the server via Ajax (by [jquery form](http://malsup.com/jquery/form/)) and receive exception messages in json format.
## Actual Behavior

I tried it with the authentication package. But Exceptions returned from the server are always in text format. How to force return exceptions via ajax in json format? I tried using ExceptionFormatter but it didn't seem to work.
![image](https://user-images.githubusercontent.com/43890051/53406031-acc1f180-39eb-11e9-85e0-f0d06b45eea1.png)

**Comment by johannesschobel** [comment]
send the `accept: application/json` header when requesting data
