### ISSUE TITLE
How to deploy project for LAMP

### ISSUE THREAD

**Issue by promistrio** [apiato/apiato#494]
## Expected Behavior
If I tried to open index.php I got 500 internal error, but it works with OpenServer 
![image](https://user-images.githubusercontent.com/6287944/53702240-d2009680-3e15-11e9-90d2-9c4a635f2874.png)
+problem that i would like to deploy my repository.(Original also don't work)

## Specifications
  - PHP Version 7.2.16

**Comment by hungnm1518** [comment]
Check all required PHP Extensions, make sure they are enabled in LAMP
OpenSSL 
PDO 
Mbstring
Tokenizer 
BCMath (required when the Hash ID feature is enabled)
Intl (required when you use the Localization Container)

**Comment by promistrio** [comment]
> Check all required PHP Extensions, make sure they are enabled in LAMP
> OpenSSL
> PDO
> Mbstring
> Tokenizer
> BCMath (required when the Hash ID feature is enabled)
> Intl (required when you use the Localization Container)

I installed all packages for php7.2. But on Desktop ubuntu I got this error and white page 
![default](https://user-images.githubusercontent.com/6287944/53770812-83282f00-3ef1-11e9-8009-ec8e8179a0dd.png)
Another php file in /public work well.
May be it connect with my .env file.
I try to change from php7.2 to php 7.1.25 and download all extentions -> same problem 
How can I debug it?

```

APP_ENV=local

APP_DEBUG=false
API_DEBUG=false
REQUESTS_DEBUG=true
QUERIES_DEBUG=false
DEBUGBAR_ENABLED=false

APP_LOG_LEVEL=debug
LOG_CHANNEL=stack

APP_NAME="apiato"
APP_URL=http://apiato.develop
API_URL=http://test.site

APP_KEY=base64:qNPN3XgZzD2cEoJbdcikL562PHwqxrwGTU1y1PwlYTE=

HASH_ID=true
HASH_ID_KEY=
HASH_ID_LENGTH=16

API_RATE_LIMIT_ENABLED=true
API_RATE_LIMIT_ATTEMPTS=30
API_RATE_LIMIT_EXPIRES=1

API_REQUEST_APPLY_REQUEST_CRITERIA=true

PAGINATION_LIMIT_DEFAULT=10
PAGINATION_SKIP=false

API_TOKEN_EXPIRES=1440
API_REFRESH_TOKEN_EXPIRES=43200
API_ENABLE_IMPLICIT_GRANT=true
API_RESPONSE_SERIALIZER=League\Fractal\Serializer\DataArraySerializer

ELOQUENT_QUERY_CACHE=false
ELOQUENT_QUERY_CACHE_TIME=60

SRC_PATH=app

ROOT_NAMESPACE=App\
USER_NAMESPACE=App\Containers\User\Models\

DB_CONNECTION=mysql
QUEUE_DRIVER=sync
CACHE_DRIVER=file
SESSION_DRIVER=file
BROADCAST_DRIVER=log
FILESYSTEM_DRIVER=local

DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=bold
DB_USERNAME=root
DB_PASSWORD=temp

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DATABASE=0

QUEUE_HOST=localhost
QUEUE_DEFAULT=default
QUEUE_RETRY_AFTER=90

SESSION_COOKIE=apiato

MAIL_ENABLED=true
MAIL_DRIVER=log
MAIL_FROM_ADDRESS=test@test.test
MAIL_FROM_NAME="apiato"
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_TO_SUPPORT_ADDRESS=test@test.com
MAIL_TO_SUPPORT_NAME="apiato Support"

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

STRIPE_KEY=
STRIPE_SECRET=

PAYPAL_ID=
PAYPAL_SECRET=

WEPAY_CLIENT_ID=
WEPAY_CLIENT_SECRET=
WEPAY_ACCESS_TOKEN=
WEPAY_ACCOUNT_ID=
WEPAY_ENV=
WEPAY_VERSION=

AUTH_FACEBOOK_CLIENT_ID=
AUTH_FACEBOOK_CLIENT_SECRET=
AUTH_FACEBOOK_CLIENT_REDIRECT=

AUTH_TWITTER_CLIENT_ID=
AUTH_TWITTER_CLIENT_SECRET=
AUTH_TWITTER_CLIENT_REDIRECT=

AUTH_GOOGLE_CLIENT_ID=
AUTH_GOOGLE_CLIENT_SECRET=
AUTH_GOOGLE_CLIENT_REDIRECT=

CLIENT_WEB_ADMIN_ID=
CLIENT_WEB_ADMIN_SECRET=

CLIENT_MOBILE_ADMIN_ID=
CLIENT_MOBILE_ADMIN_SECRET=
```
I'll try to run Laravel only.

**Comment by Osub** [comment]
APP_DEBUG=true
API_DEBUG=true
