### ISSUE TITLE
Forward HTTP_ACCEPT_LANGUAGE in CallOAuthServerTask

### ISSUE THREAD

**Issue by DMDc0de** [apiato/apiato#495]
## Expected Behavior
Call `clients/web/admin/login` with an `Accept-Language` headers setted differently from the app default locale and get a localized exception in case something goes wrong

## Actual Behavior
The exception message is not localized

## Steps to Reproduce the Problem
 1. Force the `'require_email_confirmation' => true,` inside the `authentication-container.php`
 2. Create a `UserNotConfirmedLocalizedAuthenticationExceptionFormatter` to translate the `UserNotConfirmedException`exception
  2. Map the custom formatter inside `optimus.heimdal.php`: `\App\Containers\Authentication\Exceptions\UserNotConfirmedException::class => \App\Containers\Authentication\Exceptions\Formatters\UserNotConfirmedLocalizedAuthenticationExceptionFormatter::class,`
  3. Add translations inside the `Authentication container`
  4. Try lo login with the admin user with the `clients/web/admin/login` endpoint

## Specifications
  - Apiato Version: `* dev-master`

## Additional Details
The Localization middleware is working fine, but the `CallOAuthServerTask` task is not forwarding the request language, so the request Accept-Language gets overridden by the default. If you set the headers like this
```
$headers = [
            'HTTP_ACCEPT' => 'application/json',
            'HTTP_ACCEPT_LANGUAGE' => App::getLocale()
        ];
```
in the the task everything works.

Anyway, wonderful project, keep up the good work!

**Comment by kuamanet** [comment]
Why was this closed? Did I get something wrong reporting the bug?

**Comment by Mahmoudz** [comment]
@kuamanet @DMDc0de I only closed it cause it has been open for long time and today Apiato 8.0 was released which could solve this problem! If you believe it's still relevant please open another Issue. I was mainly cleaning the repo from old Issues and PR's.. for a fresh start in 2020.
