### ISSUE TITLE
Lamp localhost/v1/ not working

### ISSUE THREAD

**Issue by promistrio** [apiato/apiato#496]
Hello! I try to run apiato on LAMP. Localhost show "Welcome to apiato" but localhost/v1/ - 404. debug outputs are empty.

**Comment by mrdionjr** [comment]
Hi, it's easier to setup Apiato with a tool like Docker or Vagrant, as they offer the ability to use custom domains. These tools are easy to setup and offer a better (IMO) development environment. You can follow the instructions at http://docs.apiato.io/getting-started/installation/#Development-Environment to setup your environment. I've never used XAMP/LAMP/WAMP so I can't help, sorry.

**Comment by deviouspk** [comment]
checkout this:
https://laradock.io/

**Comment by promistrio** [comment]
I tried to use Laradock some times, but I get database error (authentification process when I did a migrate)

**Comment by deviouspk** [comment]
use mariadb instead of mysql

**Comment by mrdionjr** [comment]
@promistrio Oh I runned into this error too. It's due to mysql version 5.8. Open .env in the laradock folder and change the mysql version from `latest` to `5.7`. Then rebuild mysql. That's it.

**Comment by Elshaden** [comment]
I use Xampp with Apiato with no problems, if I use api.apiato.local then I need to add this domain to vhosts and and windows local domains. pointing to the same Directory as apiato.local.

if you prefer to use apiato.local/api than just change the app url in .env
