### ISSUE TITLE
How to install Laravel nova beside apiato

### ISSUE THREAD

**Issue by rasadeghnasab** [apiato/apiato#500]
I want to install laravel nova in my project. I do that multiple times by pure laravel. But with apiato I think it does not know where is the NovaServiceProvider and ... 
I put both 
1. "Laravel\Nova\NovaServiceProvider" and 
2. "App\Nova\NovaServiceProvider" in config/app.php file also "Laravel\Nova\Nova" as an alias in config/app.php aliases array.

By doing that /nova/login page was correctly shown to me but after login it shows nothing but redirect me to /nova and shows me 404.

How can I install nova in my project with no pain?

**Comment by pulkitpagare** [comment]
I am facing this same issue?
@Raminsadeghi let me know if you find any solution.

**Comment by Elshaden** [comment]
Hi, This late but for anyone who wants to use Nova in Apiato Project :
1- install Nova normally 
2- In main root config.php under providers add

```
   'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
         .
         .
          \App\Providers\NovaServiceProvider::class,
```

3- in nova config file nova.php  You need to change the guard for Nova to 'web' 

```
   'guard' => 'web',         //env('NOVA_GUARD', null),

```

Try it now it should work as expected.
