### ISSUE TITLE
have the api drive from a the main domain with /api vs running from a sub domain api.

### ISSUE THREAD

**Issue by pcottrell** [apiato/apiato#502]
## Expected Behavior
https://apiato.io/api  instead of https://api.apiato.io

I realize this might be the wrong place for this, but I feel my question is justified.  

How do you allow the API to work from www.domain.com/api vs api.domain.com

Is there an easy way to do it with the code, or is just trying to sort out nginx as a proxy the best way to do it?

The reasoning is I'm getting tired of seeing options calls in the debugger as it creates a slight latency issue with interacting with the API on certain web apps.

**Comment by devmansurov** [comment]
Here is solution http://docs.apiato.io/miscellaneous/faq/#q5
