### ISSUE TITLE
how to optimize the performance of apiato

### ISSUE THREAD

**Issue by hfengshan** [apiato/apiato#505]
## Expected Behavior
how to speed up the performance of apiato, cause it is too slow to run a single route, usually 4 second per running a route. Is there any method to optimize it?

## Actual Behavior
how to optimize the performance of apiato.

## Steps to Reproduce the Problem

  1. running a route
  2. wait a long time until a response
  3. how to speed up the response time?

## Specifications

  - Apiato Version: 7.2

**Comment by candro** [comment]
I think the problem is in your server. I have no such problems.

**Comment by johannesschobel** [comment]
this is definetely 100% your own setup. My development machine has about 300ms response time and it runs the web server, local database and so on.

you may increase the performance by using apache instead of nginx, using a mysql / postgres database instead of sqlite, or ...
