### ISSUE TITLE
how to avoid the unit test Exception: `InvalidArgumentException : Unable to locate factory with name [default] App\Containers\User\Models\User`

### ISSUE THREAD

**Issue by hfengshan** [apiato/apiato#507]
## Expected Behavior
run getTestingUser() function in unit test case, it will run smoothly.

## Actual Behavior

private function factoryCreateUser($userDetails = null)
    {
        return factory(User::class)->create($this->prepareUserDetails($userDetails));
    }

call this function, it will throw 
`InvalidArgumentException : Unable to locate factory with name [default] App\Containers\User\Models\User`

## Steps to Reproduce the Problem

  1. run App\Containers\User\UI\API\Tests\Functional\FindUserTest\testFindUser_() function
  2. it throws `InvalidArgumentException : Unable to locate factory with name [default] App\Containers\User\Models\User` Exception
  3. how to avoid this Exception?

## Specifications

  - Apiato Version: 5.6.39

**Comment by Mohammad-Alavi** [comment]
This issue has been fixed twice in now deprecated [apiato/core](https://github.com/apiato/core) by this ignored pull requests.
[this](https://github.com/apiato/core/pull/124) and [this](https://github.com/apiato/core/pull/129)
