### ISSUE TITLE
why it's not work,always give me "welcome to apiato"

### ISSUE THREAD

**Issue by ruhong65** [apiato/apiato#509]
Hello, I just started using apiato, after I configured it, I opened the browser and visited http://api.soshanghai.cn:8080/v1
Got a reply:
["Welcome to Apiato (API V1)"]

Then I use the curl input command under linux:
Curl -X POST -H "Accept: application/json" -H "Cache-Control: no-cache" -F "email=red@zalt.me" -F "password=so-secret" -F "name=red Zalt" "http://api.soshanghai.cn:8080/v1/register"

and got a reply:
{"data":{"object":"User","id":"bml0wd39b5pkznag","name":"red Zalt","email":"red@zalt.me","confirmed":null,"nickname":null,"gender":null,"birth":null,"social_auth_provider":null,"social_id":null,"social_avatar":{"avatar":null,"original":null},"created_at":{"date":"2019-08-21 02:32:01.000000","timezone_type":3,"timezone":"UTC"},"updated_at":{"date":"2019-08-21 02:32:01.000000","timezone_type":3,"timezone":"UTC"},"readable_created_at":"1 second ago","readable_updated_at":"1 second ago"},"meta":{"include":["roles"],"custom":[]}}

But when I use postman to debug the interface of the api, I always return it to me.
[
    "Welcome to Apiato"
]
The interface I used for the post request request is also http://api.soshanghai.cn:8080/v1/register

Please help me.

**Comment by hfengshan** [comment]
你可以看下， 你上传了啥数据，另外你用的什么IDE，如果是phpstorm，可尝试一下用xdebug一下，看看问题出现在了那里。

**Comment by merianos** [comment]
Πραγματικά μου αρέσει η γλώσσα σας και θέλω να την μάθω. Ωστόσο, όταν ένα ερώτημα είναι στα Αγγλικά, καλό θα ήταν και η απάντηση να είναι στα Αγγλικά. Ευχαριστώ πολύ !

**Comment by johannesschobel** [comment]
Send the proper "accept" headers
