### ISSUE TITLE
Any upgrades in near future? Laravel 5.8 or 6.0?

### ISSUE THREAD

**Issue by serj42** [apiato/apiato#510]
Hello!
Are any updates planned for the near future? Will laravel upgrade to 5.8 or 6.0? Or is the project already abandoned?
Thanks for any information.

**Comment by Jimmylet** [comment]
I read in the issues that the author was abandoning the package.  It's a shame because he built something great around Laravel for the APIs.  Thousands of projects were born under Apiato and today ... well it's lost.  Open source, it's sad sometimes.  I do not have the skills to take over the project also no I would have done.

**Comment by TayyabTalha** [comment]
@serj42 I think this person is updating it [5.8](https://github.com/hungnm1518/apiato)

**Comment by Mahmoudz** [comment]
@serj42 @hungnm1518 @jaiminrockersinfo Thank you guys for your interest in the project. If you like to join the core maintainers team, for upgrading the framework and adding more feature.. Please let me know.

@aazbeltran and @rdehnhardt have just joined us. And since we all share the same interests, I guess it would be great if you can work together toward customizing the project to your needs.

I guess some of you already know @johannesschobel, (I'm not sure about his availability these days), he was the last person maintaining the project and bringing it to its current state today.

**Comment by rdehnhardt** [comment]
Thanks @Mahmoudz and I will use this issue to ask you what you think of adopting as the base version for apiato/core, the current version of laravel, I have some packages and I follow this pattern, it helps a lot

**Comment by jaiminrockersinfo** [comment]
Hello @apiato/apiato
<reply@reply.github.com>


Thank you for asking us.

We are ready to join the core maintainers team for upgrading the framework
and adding more feature.

Thanks & Regards,
Jaimin Suthar
Sr. Software Developer | Rockers Technology | Information Technology
*Site**:* https://www.rockersinfo.com/
*Email:* jaimin.rockersinfo@gmail.com <virald.rockersinfo@gmail.com>
*Address:* 3rd Floor, Corner Heights, Near Delhi Public School, Kalali
Vadsar Ring Road, Vadodara, Gujarat 390012.

**Comment by zmaren** [comment]
Hello guys, I tried to upgrade to Laravel 6, please feel free to continue with anything you think it's ok so we can continue using Apiato with L6 as well.

https://github.com/zmaren/apiato

**Comment by rdehnhardt** [comment]
I'm trying to update, but there some problems in default containers! In this repository, I remove the problematic exception package

**Comment by zmaren** [comment]
> I'm trying to update, but there some problems in default containers! In this repository (https://github.com/rdehnhardt/core), I remove the problematic exception package

If you talking about heimdal package, I think its just requirement from composer file to max laravel 5.3, you can try my repo. I removed that package and added copy of it with laravel 6 support

**Comment by rdehnhardt** [comment]
Heimdal package is one of the problems! There is problems with default containers like Wepay and another one that I dont remember now!

**Comment by johannesschobel** [comment]
IMHO the `Wepay` container should be dropped, as it contains a lot of issues (this was a copy/paste PR from another developer, who did not properly adapt the container. It was copied from the `Stripe` container and, hence, was not fully ported. I am not even sure if this container works..)

**Comment by rdehnhardt** [comment]
Problematic Packages in Laravel 6

johannesschobel/laravel-shoppingcart
kevinem/wepay-laravel

**Comment by rdehnhardt** [comment]
@johannesschobel now I see! The "johannesschobel/laravel-shoppingcart" It's yours! 

In your composer, "laravel/framework": "^5.4"

Can you replace this?

**Comment by johannesschobel** [comment]
i would also vote to remove this :D

**Comment by rdehnhardt** [comment]
On my core fork, I removed the package from Heimdal, but api was without proper exception handling! For this reason I did not push my branch! However, I don't know the creators' internations about the exception treatment.

**Comment by martin-arvisais** [comment]
Hi all, any news on Apiato being compatible with Laravel 6? Or any fork, or how to make the migration? I need to be Laravel 6, but don't know where to start. Thanks

**Comment by zmaren** [comment]
Hey @martin-arvisais you can try this one until my merge request is accepted by @Mahmoudz 

https://github.com/zmaren/apiato

I'm using it now and it works great with L6

**Comment by martin-arvisais** [comment]
Great, thx, i will check this out, much appreciate!

**Comment by meysamhashemi** [comment]
is there any plan for upgrading apiato to the newer laravel version??? any sign of upgrading process? can we hope to have laravel's newer versions  support in near future?

**Comment by meysamhashemi** [comment]
> Hey @martin-arvisais you can try this one until my merge request is accepted by @Mahmoudz
> 
> https://github.com/zmaren/apiato
> 
> I'm using it now and it works great with L6

have you develop any project using this laravel 6 branch?? can we trust it for our future projects???

**Comment by zmaren** [comment]
@meysamhashemi I have several projects with this upgrade and everything working as expected.

**Comment by Mahmoudz** [comment]
First of all big thanks to all of you for using Apiato.
I've just released [Apiato 8.0](https://github.com/apiato/apiato/releases/tag/v8.0.0) with support for Laravel 6. *([Tested](https://travis-ci.org/apiato/apiato/builds/639578333?utm_source=github_status&utm_medium=notification))* with PHP 7.2 - 7.3 & 7.4.
You can upgrade by following these simple and tested steps in the [upgrade guide](http://docs.apiato.io/miscellaneous/upgrade-guide/#upgrade-apiato-from-version74To80).
Happy Coding :)
