### ISSUE TITLE
We are upgrade APIATO 5.6 to 5.8 or 6.0?

### ISSUE THREAD

**Issue by jaiminrockersinfo** [apiato/apiato#512]
But We are facing multiple issues when we upgrade laravel in our apiato package.
[error.txt](https://github.com/apiato/apiato/files/3579506/error.txt)

**Comment by niuto** [comment]
6.0 Thanks

**Comment by rdehnhardt** [comment]
This is because there is a problem with the composer in the Ship folder, you are using the **dev-master** version when you should be using  **2.4.8** version.
