### ISSUE TITLE
How do I make aggragate and group by queries with apiato?

### ISSUE THREAD

**Issue by TheGodFather05** [apiato/apiato#520]
I'm trying to make an enpoint for statistics and I 
Am struggling on aggregating data. How can I properly make a groupby request and apply aggregate functions on attributes

**Comment by johannesschobel** [comment]
that is entirely up to your business logic. i would suggest to take a look at the proper eloquent queries (i.e,. there is a way to groupby or whatever) and then serialize the data. For example, you can easily make a `statistics` model and just shove all your aggregated data from your DB into this model and return it.

This is, however, not related to apiato..
