### ISSUE TITLE
Issue Or Bug in API Authenticating Token

### ISSUE THREAD

**Issue by Elshaden** [apiato/apiato#527]
## Expected Behavior
authenticate User

## Actual Behavior
Invalid Token
## Steps to Reproduce the Problem

  1.Login with API, and Got Access Token
  2.use any other route with Authorization Bearer Token
  3.got Exception Invalid or Missing Token

## Specifications

  - Apiato Version:8

## Additional Details
in IDE Debugger I traced the error to this exception

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'where clause' (SQL: select * from `users` where `api_token` = gwjW8WQkjXKXdgsiq62b6zZhHVS5MwfF5X2s_H843zn96Iw and `users`.`deleted_at` is null limit 1)
```
It is looking for api_token in User Table, and that Obviously Does not exist.

**Comment by Te7a-Houdini** [comment]
@Elshaden have you set the guard api driver to [passport](https://laravel.com/docs/6.x/passport#installation)?

![Screenshot from 2020-01-23 15-13-16](https://user-images.githubusercontent.com/17250137/72987374-f0d39700-3df2-11ea-8ecc-55c7d571d71e.png)

**Comment by Elshaden** [comment]
@Te7a-Houdini 
Thanks, It works now,
This was out of the box in previous Apiato version,
Though it is good to know That I can use this feature if needed.
