### ISSUE TITLE
How to Use Apiato for multiple applications ?

### ISSUE THREAD

**Issue by houssam-saissi** [apiato/apiato#529]
Hello,

After seeing, studying and testing Apiato, I find it very professional and interesting. However, I want to do the following manipulation and I cannot find a sample code:

I want to create multiple applications that use the same Application Core:
- Same database called from a API.
- API application which uses this database. (api.test.com)
- 1 Dashboard application (Vue or React) which uses this API. (www.dahsboard.com)
- 2 Frontend applications (Vue or React) which uses this API. (www.front.com and www.anotherfront.com)
- 1 mobile application why not ...

Each application (website) uses a different domain or subdomain and different directories.

Any help is very appreciate, Thank you :)

**Comment by Mohammad-Alavi** [comment]
That is exactly why we develop APIs in the first place. I don't see where
is your problem. You can develop your API using apiato then consume it
through many different frontend applications e.g website developed using
any front end framework, mobile application and anything you can imagine
that can interact with your API.

**Comment by houssam-saissi** [comment]
Okey : 

1 - how to use jwt with apiato?
2 - how to integrate Azure AD and AD B2C auth with apiatio ?
 Thanks :)
