### ISSUE TITLE
Migrate from exisiting Laravel App?

### ISSUE THREAD

**Issue by quantumio** [apiato/apiato#531]
**Is your feature request related to a problem? Please describe.**
it's related to a problem I have?  I wonder (non-techie) if it's possible to migrate an existing Laravel app into Apiato?

**Describe the solution you'd like**
Perhaps a basic article on how?  A wizard or CLI command to allow discovery of existing routes within the app? Is that something you offer consultancy on?

**Describe alternatives you've considered**
I have an API and im looking to take more control with Apiato, am I the only app owner with this problem?  I feature on Postman, is there a way to reverse engineer (I see document article with the API going into a collection ...but not the other way around?)

**Additional context**
I love the idea of integrating my app with Apiato framework - what are my options please?

**Comment by johannesschobel** [comment]
There is a default laravel command to show all routes ( I think it's `php artisan routes:list`) . From the you may start migrating.

Note that there is no wizard it cli to do so

**Comment by quantumio** [comment]
Awesome, thanks!...I thought this is how I would do it ...I just wanted to make sure it wasn't more complicated..
