### ISSUE TITLE
merg requst not working

### ISSUE THREAD

**Issue by jebraieili** [apiato/apiato#533]
hi
merg requst not working in controller
$request->merge(['search'=>'subject_id:1']);
$questions = Apiato::call('Question@GetAllQuestionsAction', [$request]);

this return all questions
in QuestionRepository :
    protected $fieldSearchable = [
        'id' => '=',
        'subject_id' => '='
    ];

**Comment by Te7a-Houdini** [comment]
@jebraieili have you tried to make **dd($request->all());** after the merge ?
