### ISSUE TITLE
Impossible to install optimus/heimdal

### ISSUE THREAD

**Issue by andreacivita** [apiato/apiato#535]
### Description:
New apiato project can't run because optimus/heimdal is missing. I have tried to install it but this dependecy requires laravel ~5.3. There is no version provided for laravel 6, so composer can't find a version that satisfy apiato dependecies. 
With this problem, I can't start apiato project because it returns error 500.

### Expected Behavior:
I should run apiato project without problems

### Additional Context:
I paste first part of trace found in error.log file (apache)
`PHP Fatal error:  Uncaught ErrorException: include(../optimus/heimdal/src/ExceptionHandler.php): failed to open stream: No such file or directory in vendor\\composer\\ClassLoader.php:444`

### Versions:
- Apiato Version: 8.0.2
- PHP Version: 7.4.3

### Steps To Reproduce:
1. Create project with `composer create-project apiato/apiato my-api`
2. Setup apiato (following this link [Installation | Apiato](http://docs.apiato.io/getting-started/installation/#App-Composer)
3. Setup vhost and hosts file (i'm on Windows). E.g: 127.0.0.1 apiato.test
4. Trying to navigate to http://apiato.test return error 500.

**Comment by andreacivita** [comment]
Downloading directly [Optimus/heimdal](https://github.com/esbenp/heimdal) and unzipping src directory in vendor/optimus/heimdal will solve error 500.

**Comment by johannesschobel** [comment]
heimdal is not actively maintained any more. the latest versions of apiato do not include heimdal any more (because of such issues).
copying heimdal to your `vendor/` folder is a bad practice, as it may be removed when running `composer` commands!

**Comment by andreacivita** [comment]
Yeah, i know that copying directory is very bad and all composer commands will delete it, but latest version of apiato (8.0.2) crash because optimus/heimdal is not found.
I've downloaded apiato this morning, so i'm sure i'm using latest version
