### ISSUE TITLE
upgrade to laravel 7

### ISSUE THREAD

**Issue by muhsenmaqsudi** [apiato/apiato#537]
is there any plan for upgrading apiato's laravel version to 7??
i don't think it should get a lot of your time for this upgrade,
if not what's the best way we can upgrade it by our own??

**Comment by Mahmoudz** [comment]
@muhsenmaqsudi Good suggestion, 
I've spent 2 hours on the upgrade today, and finished around 80% of it, I guess!

The work can be found on this the [9.0](https://github.com/apiato/apiato/tree/9.0) branch, at this [commit](https://github.com/apiato/apiato/commit/bdcf9fa97973373c88e0f4a3ff146973fb1d6d97)

_I would appreciate if someone can pick it up and complete it, but if not, I will try to spend another couples hours hopefully by end of this week._

### TODO:
[x] Upgrade all dependecies.
[x] Upgrade the CORS package namespace and config file.
[x] Replace Exception with Throwable.
[x] Run composer install successfully.
[x] Verify installing Laravel 7.5.1 `php artisan -V`.
[ ] Run phphnit and solve any occurring errors.
[ ] Run `composer install` and solve any occurring warnings.
[ ] (Optional but recommended) remove the "optimus/heimdal" package, _it's old and doesn't support Laravel 7_. 

	[ ] Remove the package from composer.json of the core and its repositories link.
	[ ] Delete the package folder from the project.
	[ ] Unregister its ServiceProvider.
	[ ] Delete its config file.
	[ ] Replace HeimdalExceptionHandler with LaravelExceptionHandler.
	[ ] Update composer.
	[ ] Fix any problems and verify tests are still working.
	[ ] Update the docs by deleting irrelevant info such as [this page](http://docs.apiato.io/components/exceptions-formatters/) or notify me to update the docs.

[ ] Write [upgrade guide](http://docs.apiato.io/miscellaneous/upgrade-guide/), or notify me to do so.

**Comment by muhsenmaqsudi** [comment]
i really appreciate your work, i have a suggestion for the upgrade, there is a package that was missed from the previous update, the facade ignition package (https://github.com/facade/ignition) that was added in laravel 6 the new error page that is very beautiful and gives a lot of info on our errors that the old one doesn't have... while your are upgrading it to the new laravel 7 version, please also add this package, thanks....

**Comment by Mahmoudz** [comment]
@muhsenmaqsudi good to know. 
It has already been [added](https://github.com/apiato/apiato/commit/bdcf9fa97973373c88e0f4a3ff146973fb1d6d97#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R45) for next release.

**Comment by Mohammad-Alavi** [comment]
Hello @Mahmoudz .

Did you find the time to upgrade to Laravel 7?

**Comment by Mohammad-Alavi** [comment]
> Hello @Mahmoudz .
> 
> Sorry for asking this but did you find the time to upgrade to Laravel 7? I really appreciate it.
> I would have helped in upgrade process if i had enough confidence in my skills.

I just want you to know that i really tried to update today with no success :( Could't go past the failing tests. I may try again tomorrow.

And btw why didn't you merge the latest PR's on v8.0 also with master? They where mostly bug fixes.
May i ask what was the reason for that? (for learning purposes)

There where some very needed bug fixes on that 3 4 last PR's which 9.0 branch lacks which may be the reason for some the failing tests.

**Comment by Mahmoudz** [comment]
@Mohammad-Alavi Thanks for trying.
I will try to finish this today! And make sure everything is merged in the new release.

**Comment by Mahmoudz** [comment]
Finally, **Laravel 7** is supported in [Apiato 9.0](https://github.com/apiato/apiato/releases).

Please follow these [easy instructions](http://docs.apiato.io/miscellaneous/upgrade-guide/#upgrade-apiato-from-version80To90) to upgrade.
