### ISSUE TITLE
Apiato / Laravel / Apis / Backend

### ISSUE THREAD

**Issue by MarahNajjar** [apiato/apiato#542]
hi
i try used apiato laravel project for use it as backend (using apis)
i install project apiato and run it normally
test web api running successfully
but when i test any of api route return not found
i don't know where is the problem
i want to work it locally , i used windows 10 and PHP version 7.2
any one can help me please??

**Comment by Tirro** [comment]
Hi, you followed all the instructions in the documentation ?
What do you use as a server ?
You configured your `/etc/hosts` file ?
You configured your `.env` file ?

**Comment by jmatembu** [comment]
@MarahNajjar Check with your API_URL variable in the `.env` file. For example, if APP URL is `http://project.test`, then set your API URL like: `http://api.project.test` or something similar but not necessarily the same as APP URL.
