### ISSUE TITLE
Specific Seeder class not work

### ISSUE THREAD

**Issue by wangdeer** [apiato/apiato#548]
### Description:

Hi, thank you for make thus wonderful project!

Now, I have a problem,I create a seeder file with `php artisan apiato:generate:seeder`,

```shell
 Enter the name of the Container:
 > Authorization
 Enter the name of the Seeder file [AuthorizationSeeder]:
 > AuthorizationTestRoleSeeder
> Generating (AuthorizationTestRoleSeeder) in (Authorization) Container.
Seeder generated successfully.
```

Exec `composer dumpautoload`:

```shell
Generated optimized autoload files containing 6076 classes
```
But when I exec `php artisan db:seed --class=AuthorizationTestRoleSeeder`  command, it return the error below:

```
In Container.php line 805:
  Target class [AuthorizationTestRoleSeeder] does not exist.  
In Container.php line 803:
  Class AuthorizationTestRoleSeeder does not exist 
```

I have submit this problem in [apiato slack](https://app.slack.com/client/T4SA6BM1S/C4SA6BSJ0?cdn_fallback=1), Maybe you are too busy to see it, so I submit this issue and hope to get your help. Thank you very much!

### Versions:
- Apiato Version: 8.0.1
- PHP Version: 7.3.15

**Comment by yalsicor** [comment]
You need to provide the fully quallified Namespace of your Seeder class.

Try `php artisan db:seed --class="App\Containers\Authorization\Data\Seeders\AuthorizationTestRoleSeeder"`

**Comment by wangdeer** [comment]
Wow! It's working. 
I also tried `php artisan db:seed --class=App\Containers\Authorization\Data\Seeders\AuthorizationTestRoleSeeder`, but it not work, because I didn't add `""`.
Thanks a million！
