### ISSUE TITLE
Authentication and Authorization Traits

### ISSUE THREAD

**Issue by egbertmza** [apiato/apiato#551]
### Description:
It seems these 2 are swapped around. The AuthenticationTrait.php file contains the Authorization Trait and Visa versa

### Expected Behavior:
Probably needs to be the other way around.

### Versions:
- Apiato Version: 9.0.1

**Comment by Mohammad-Alavi** [comment]
Interesting :thinking: I can't find an **AuthenticationTrait.php** in my project and **AuthorizationTrait.php** doesn't have **AuthenticationTrait.php** in it  :thinking:

**Comment by egbertmza** [comment]
Hi

 

They are in v9

 

https://github.com/apiato/apiato/tree/9.0/app/Containers/Authorization/Traits

 

Regards

**Comment by Mohammad-Alavi** [comment]
I am using v9 🤔

**Comment by midoalone** [comment]
@Mohammad-Alavi AuthorizationTrait and AuthenticationTrait class names are replaced with each others, that's kinda wired, but if you just switch class names all thing will work normally.

I will try to make a pull request fixing it.

**Comment by Mohammad-Alavi** [comment]
This changes have been introduced in v9.0.1 not 9.0.0 and i use v9.0.0 that is why i don't have this problems. Please indicated the exact version number in issues to avoid confusions like this.

**Comment by egbertmza** [comment]
Apologies, I see that now as well...updated original comment accordingly

**Comment by newsages** [comment]
and in test?
FAILURES!
Tests: 59, Assertions: 138, Failures: 1.
newsages@workspace-php:/var/www$ vendor/bin/phpunit 
PHPUnit 8.5.4 by Sebastian Bergmann and contributors.

........F..................................................       59 / 59 (100%)

Time: 12.36 seconds, Memory: 60.50 MB

There was 1 failure:

1) App\Containers\Authorization\UI\API\Tests\Functional\AttachPermissionsToRoleTest::testAttachSinglePermissionToRole_
Expected status code 200 but received 400.
Failed asserting that 200 is identical to 400.

/var/www/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:185
/var/www/app/Containers/Authorization/UI/API/Tests/Functional/AttachPermissionsToRoleTest.php:44

**Comment by Mahmoudz** [comment]
https://github.com/apiato/apiato/pull/553

**Comment by Mahmoudz** [comment]
Fixed in [v9.0.3](https://github.com/apiato/apiato/releases/tag/v9.0.3)
