### ISSUE TITLE
The sql script has double conditions

### ISSUE THREAD

**Issue by wangdeer** [apiato/apiato#554]
### Description:

Hi, I have a Repository below 
```php
<?php

namespace App\Containers\Category\Data\Repositories;

use App\Ship\Parents\Repositories\Repository;

/**
 * Class CategoryRepository
 */
class CategoryRepository extends Repository
{

    /**
     * @var array
     */
    protected $fieldSearchable = [
        'parent_id' => '=',
        'type' => '=',
        'sn' => '=',
        'name' => 'like',
        'description' => 'like',
        'status' => '=',
        'created_at' => 'between'
    ];

}
```

I query like this `domain/categories?search=name:name;status:0`,  as common the sql script should be ：

```sql
select count(*) as aggregate from `categories` where (`categories`.`name` like '%name%' or `categories`.`status` = '0')  and `categories`.`deleted_at` is null
```

but when I debug with the package [laravel-debugbar](https://github.com/barryvdh/laravel-debugbar), the sql script retrun is :
```sql
select count(*) as aggregate from `categories` where (`categories`.`name` like '%name%' or `categories`.`status` = '0') and (`categories`.`name` like '%name%' or `categories`.`status` = '0') and `categories`.`deleted_at` is null
```

The same condition happened twice.

I dig into the source code, find the `pushCriteria(app(RequestCriteria::class));` is used in two files `app/Ship/core/Traits/HasRequestCriteriaTrait.php` and `app/Ship/core/Abstracts/Repositories/Repository.php` causes duplicate conditions to be added.  

Is it all necessary? Can I remove one of them?

Tank you !

### Versions:
- Apiato Version: 8.0.1
- PHP Version: 7.3.15

**Comment by Mohammad-Alavi** [comment]
Fixed in v10
