### ISSUE TITLE
cors.php into fruitcake/laravel-cors config override app cors.php

### ISSUE THREAD

**Issue by Tirro** [apiato/apiato#562]
### Description:
`cors.php` into `fruitcake/laravel-cors` override `cors.php` which is located in the `var/app/ship/configs`, if place `cors.php` into `var/config/cors.php` then everything works fine.

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.3.17

**Comment by lumineida** [comment]
Installing a new project via composer on Apiato version: 9.0.4 and PHP 7.4.5 I get these warnings that may be related:

Warning: Ambiguous class resolution, "Fruitcake\Cors\CorsServiceProvider" was found in both 
"vendor/barryvdh/laravel-cors/src/CorsServiceProvider.php" and "vendor/fruitcake/laravel-cors/src\CorsServiceProvider.php", 
the first will be used.
Warning: Ambiguous class resolution, "Fruitcake\Cors\HandleCors" was found in both 
"vendor/barryvdh/laravel-cors/src/HandleCors.php" and "vendor/fruitcake/laravel-cors/src\HandleCors.php", the first will be used.

I'm having issues with CORS on this new project

**Comment by lumineida** [comment]
After many attempts, I finally got it to work by removing from composer.json: "fruitcake/laravel-cors": "^1.0", leaving the package as it is defined in Ship/core/composer.json: "fruitcake/laravel-cors": "^1.0.5", and also moved cors.php from Ship/Configs to main config folder. 
Hope this helps someone else :-)

**Comment by Elshaden** [comment]
Thanks @lumineida , I fixed it the same way you mentioned and ran composer update.
don not know if I am going to face any further issues .

**Comment by Mohammad-Alavi** [comment]
For now use [this](https://github.com/apiato/apiato/issues/565#issuecomment-646523122) solution until we fix it permanently.
