### ISSUE TITLE
How Can i get Exceptions in JSON FORMAT?

### ISSUE THREAD

**Issue by davidreyg** [apiato/apiato#570]
### Description:
I'm trying to access a route that doesn't exists from my app and I'm getting a HTMLJSON response

![screenshot-6d239642](https://user-images.githubusercontent.com/19297294/83724063-44f25180-a605-11ea-9b49-da52ff5864ed.jpg)

### Expected Behavior:

I want to get this response from apiato.

{
  "status": "error",
  "code": xxxx,
  "message": "xxxxxxxxxxxxxxx",
  "status_code": 40x
}

### Additional Context:
I'm sending the header
* Accept : application/json

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4

**Comment by jebraieili** [comment]
i have this problem too ,Unfortunately ExceptionBuilder class and addCustomData method not working in apiato 9.0.0

**Comment by newsages** [comment]
Errors are erros,,  Exceptions are Http Exceptions,,  if you catch exception, make response.
