### ISSUE TITLE
composer install is skipping some packages

### ISSUE THREAD

**Issue by egbertmza** [apiato/apiato#571]
### Description:
 The issue I am having is that when running composer install, it seems to miss packages. Once I delete the composer.lock file and run composer install again it seems to detect and install the missing packages. AS an interim fix I move SOME of them to the main composer.json file , but then when i clear out vendor folder and delete the lock file and run composer install again, it ends up skipping some other package....(it seems to skip laravel passport, spatie and a few others.... so I cant pick up a specific packages or issues.... 

the solution probably has 50 or more "containers" that each contain a composer.json file (most of them empty). I get the feeling something goes wrong when its merging...but I cant validate my theory... there are no errors or warnings...

has anyone experienced similar issues ?

I have no idea how to resolve this....

### Versions:
- Apiato Version: 9.0
- PHP Version: 7.3

**Comment by ab192130** [comment]
I had something like this.  That was when I've added any composer dependencies in my Containers. They wasn't discoverable when I run "composer install" in the project root. 

The only solution I've found was to run "composer update" instead of "install". Try it, maybe helps.

**Comment by Mohammad-Alavi** [comment]
I think this issue is related to [this](https://github.com/apiato/apiato/issues/565#issuecomment-646523122) one that @egbertmza have found and fixed.
