### ISSUE TITLE
Can't login with multiple attributes

### ISSUE THREAD

**Issue by midoalone** [apiato/apiato#573]
### Description:
When I add another attribute for login beside email it won't work

### Expected Behavior:
It should accept any attributes for login and return success

### Additional Context:
authentication-container.php > login attributes
`'attributes' => [
      'email' => ['email'],
      'mobile' => ['string'],
    ],`

ProxyApiLoginTransporter.php
`protected $schema = [
        'type' => 'object',
        'properties' => [
            'email',
            'mobile',
            'name',
            'password',
            'client_id',
            'client_password',
            'grant_type',
            'scope',
        ],
        'required'   => [
            'password',
            'client_id',
            'client_password',
        ],
        'default'    => [
            'scope' => '',
        ]
    ];`

### Versions:
- Apiato Version: 9.0
- PHP Version: 7.4

### Steps To Reproduce:
1- add mobile to login attributes
2- add mobile to ProxyApiLoginTransporter properties
3- try to login with email or mobile only one of them works "the later in order will work"

**Comment by Mohammad-Alavi** [comment]
In your third step (Steps To Reproduce), what do you mean by "the later in order will work"?

**Comment by KielD-01** [comment]
@Mohammad-Alavi he means, that mobile login works, but email
