### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by raakkan** [apiato/apiato#574]
postman request working and browser request working but axios request not working.

axios setup.
```
import axios from 'axios';

const api = axios.create({
    baseURL: 'http://api.apiato.test/v1',
    headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-type': 'application/json',
    },
});

api.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

let token = document.head.querySelector('meta[name="csrf-token"]') as HTMLMetaElement;

if (token) {
    api.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}

export default api;

```

error.
```
Access to XMLHttpRequest at 'http://api.apiato.test/v1/users' from origin 'http://apiato.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

app.js:1691 Uncaught (in promise) Error: Network Error
    at createError (app.js:1691)
    at XMLHttpRequest.handleError
```

**Comment by davidnnachi** [comment]
@raakkan In line 27 in cors.php, I replaced

```
/*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => [],
```

with

`'paths' => ['*'],`

**Comment by AdnaneX** [comment]
there are two cors files one override the other.

**Comment by Mohammad-Alavi** [comment]
> there are two cors files one override the other.

If that is the case, there is a know issue with configs not being loaded. Ill try to look into it this weekend.

**Comment by actmkan** [comment]
I found a temporary solution to the problem.
After moving the cors.php file from /app/Ship/Configs directory to /config directory, the solution of @davidnnachi worked.

**Comment by quangtam** [comment]
I've got same issue and can not resoveled.

**Comment by AdnaneX** [comment]
> I've got same issue and can not resoveled.

move the cors.php file from /app/Ship/Configs directory to /config
and change from 'paths' => [], to 'paths' => ['*'], in config/cors.php
thene run php artisan config:cache

**Comment by quangtam** [comment]
> > I've got same issue and can not resoveled.
> 
> @quangtam
> move the cors.php file from /app/Ship/Configs directory to /config
> and change from 'paths' => [], to 'paths' => ['*'], in config/cors.php
> thene run php artisan config:cache

Thanks! The issue has resolved.

**Comment by folkevil** [comment]
> > I've got same issue and can not resolved.
> 
> @quangtam move the cors.php file from /app/Ship/Configs directory to /config and change from 'paths' => [], to 'paths' => ['*'], in config/cors.php thene run php artisan config:cache

I do the same but it isn't work ;(
