### ISSUE TITLE
Validation exception not working

### ISSUE THREAD

**Issue by raakkan** [apiato/apiato#575]
any validation error server returns this message.

```
[
    "Welcome to Apiato"
]
```

**Comment by Mohammad-Alavi** [comment]
Mine is working fine. 🤔

**Comment by quangtam** [comment]
It's not work with me. Show the same message.

**Comment by Mohammad-Alavi** [comment]
If you are using postman/insomnia, add "accept" header with value of "application/json"

**Comment by quangtam** [comment]
> If you are using postman/insomnia, add "accept" header with value of "application/json"

Thanks! It's work now.
