### ISSUE TITLE
Swagger documentation generator

### ISSUE THREAD

**Issue by sdjrppl** [apiato/apiato#581]
### Description:
Calling `php artisan apiato:swagger` causing error: Cannot read property 'indexOf' of undefined. Idk if is just me but when calling the command to generate swagger doc files it throws that error and I was not able to solve it.
Calling `php artisan apiato:apidoc`  works fine.

### Expected Behavior:
It's expected to generate the swagger documentation.

### Additional Context:
![image](https://user-images.githubusercontent.com/17573664/92656171-7c4e5980-f2ea-11ea-8770-2ee6fae8cbeb.png)
Also I've change this line, because before it was not finding the files.
![image](https://user-images.githubusercontent.com/17573664/92656296-b15aac00-f2ea-11ea-8597-1a5eaa4f7a4e.png)

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4.9

### Steps To Reproduce:
1. Go to root and call `php artisan apiato:swagger`

**Comment by dons20** [comment]
Still experiencing this issue, any potential fixes in the interim?

**Comment by darkons** [comment]
That error is coming from `apidoc-swagger` not from Apiato.

Check #536 for more info.

**Comment by Mohammad-Alavi** [comment]
Swagger doc generator was relying on an old and unmaintained project. This feature is removed in v10. PRs are welcome to add it back.
