### ISSUE TITLE
Cache doesn't work for $this->repository->paginate();

### ISSUE THREAD

**Issue by Jedliu** [apiato/apiato#588]
### Description:
Cache doesn't work for `$this->repository->paginate();` while it works for `'all', 'find', 'findByField', 'findWhere', 'getByCriteria'`

### Expected Behavior:
Cache should work for `$this->repository->paginate();`

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4.4

### Steps To Reproduce:
1. Enable cache setting in .env
2. Call `$this->repository->paginate();` task and check if it hits the cache

### Possible solution:
When call `$this->repository->paginate();`, the `paginate()` of the abstract class Repository is called(/app/Ship/core/Abstracts/Repositories/Repository.php) then `parent::paginate($limit, $columns, $method)` is called. This paginate function SHOULD be from `CacheableRepository` of the I5-repository package in order to use the cache service, however, actually it is from `BaseRepository`.

So I created another abstract class `ParentRepository` as below:
````
<?php

namespace Apiato\Core\Abstracts\Repositories;

use Prettus\Repository\Contracts\CacheableInterface as PrettusCacheable;
use Prettus\Repository\Eloquent\BaseRepository as PrettusRepository;
use Prettus\Repository\Traits\CacheableRepository as PrettusCacheableRepository;

abstract class ParentRepository extends PrettusRepository implements PrettusCacheable
{
    use PrettusCacheableRepository;
}
````

and updated the `Repository.php` extends this`ParentRepository` instead.
```
namespace Apiato\Core\Abstracts\Repositories;

use Illuminate\Support\Facades\Config;
use Prettus\Repository\Criteria\RequestCriteria as PrettusRequestCriteria;
use Request;

/**
 * Class Repository.
 *
 * @author  Mahmoud Zalt <mahmoud@zalt.me>
 */
abstract class Repository extends ParentRepository
{
    /**
     * Define the maximum amount of entries per page that is returned. 
     * Set to 0 to "disable" this feature
     */
    protected $maxPaginationLimit = 0;
```

This fixes the problem at this moment. Does anyone have a better suggestion? 
Thank you!

**Comment by Mohammad-Alavi** [comment]
Fixed in v10 (in this [commit](https://github.com/apiato/core/commit/5d0fcfe52c3db4b0d265d8bf29b731f92a711f33) in core)
