### ISSUE TITLE
Socialite error: Response::setContent()

### ISSUE THREAD

**Issue by andreacivita** [apiato/apiato#589]
### Description:
Hi! I'm developing an app with Apiato, and using socialite (as described in docs) generate error i couldn't fix.

I mean, when trying to login with google, callback response is:

```

Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given,

```

I couldn't figure out what is going on...

### Expected Behavior:

Callback should work making me login with google

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4.3

### Steps To Reproduce:
1. Follow docs about socialauth (using google client_id and secret_id)
2. Try to login and found error in callback

**Comment by andreacivita** [comment]
Hi man, any updates about this issue? :)

**Comment by Mohammad-Alavi** [comment]
Fixed in v10
