### ISSUE TITLE
Composer 2 problem

### ISSUE THREAD

**Issue by erikhu** [apiato/apiato#591]
### Description:
when use composer install or composer update

### Expected Behavior:
Must install all deps

### Additional Context:
Composer is 2, recently as stable version

### Versions:
- Apiato Version: 9.0.10
- PHP Version: 7.3.23

### Steps To Reproduce:
1. install composer 2
2. composer install

![composer](https://user-images.githubusercontent.com/7550327/97332103-11c88d00-1848-11eb-9f07-e1ff647bbf6d.png)

**Comment by pacholoamit** [comment]
Same here as well.

**Comment by erikhu** [comment]
> Same here as well.

by now i fixed to composer 1, while this is solve but by default when i installed composer is 2

**Comment by dmouse** [comment]
this package needs to be updated https://github.com/apiato/containers-installer/blob/master/composer.json

**Comment by GigiArteni** [comment]
Same here as well.

**Comment by Jedliu** [comment]
It's not compatible with Composer 2 and there will be problems as below.
`- apiato/containers-installer[v1.0.0, ..., v1.0.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
- Root composer.json requires apiato/containers-installer ^1.0 -> satisfiable by apiato/containers-installer[v1.0.0, v1.0.1].
- Root composer.json requires wikimedia/composer-merge-plugin 1.4.1 -> satisfiable by wikimedia/composer-merge-plugin[v1.4.1].
- wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.`

Here is how I make it work. Hope it helps.
Update the **composer.json** as below
`"require": {
    "php": "^7.4",
    "ext-mbstring": "*",
    "ext-openssl": "*",
    "ext-pdo": "*",
    "ext-tokenizer": "*",
    "laravel/framework": "^7.0",
    "doctrine/dbal": "2.5.*",
    "fideloper/proxy": "^4.2",
    "guzzlehttp/guzzle": "^6.3",
    "laravel/tinker": "^2.0",
    "fruitcake/laravel-cors": "^1.0",
    "wikimedia/composer-merge-plugin": "dev-feature/composer-v2"
  },
  "repositories": [
    {
        "type":"vcs",
        "url":"https://github.com/mcaskill/composer-merge-plugin"
    }
  ],`

and update **app/Ship/core/composer.json** to
`{
  "name": "apiato/core",
  "description": "core Container for apiato.",
  "repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/Jedliu/containers-installer"
    }
  ],
  "require": {
    "illuminate/support": "~7.5",
    "apiato/containers-installer": "dev-composer-v2",
    "prettus/l5-repository": "^2.6",
    "fruitcake/laravel-cors": "^1.0.5",
    "spatie/laravel-fractal": "^5.7",
    "vinkla/hashids": "^8.0",
    "dto/dto": "^3.2"
  },
  "autoload": {
    "psr-4": {
      "Apiato\\Core\\": ""
    }
  }
}`

Reference to:
[https://github.com/wikimedia/composer-merge-plugin/issues/184](https://github.com/wikimedia/composer-merge-plugin/issues/184)
[https://github.com/wikimedia/composer-merge-plugin/pull/189](https://github.com/wikimedia/composer-merge-plugin/pull/189)

**Comment by mohammadb5** [comment]
in composer version 2, many issues occur.
you can easily downgrade your composer version with this command:

composer self-update --<version>

**Comment by dendihandian** [comment]
I hope this is supported soon and eventually along with an upgrade to Laravel 8. I have an API project coming up and really want to try this API framework  😆

**Comment by Mohammad-Alavi** [comment]
This is already fixed in Apiato v10 which is under development and will be released soon.
