### ISSUE TITLE
The Post method is not supported for this route on v1/register

### ISSUE THREAD

**Issue by ikkysleepy** [apiato/apiato#592]
### Description:
I am trying to Post to the v1/register url and I get this error message: 

`The POST method is not supported for this route. Supported methods: GET, HEAD.`

URL: 
http://api.openstudio-api.test/v1/register

Valet is the environment setup. I get a welcome json request to 
http://api.openstudio-api.test/v1

`["Welcome to Apiato (API V1)"]
`
### Expected Behavior:
I expect a json response.

### Additional Context:
I had to modify the .env file to the correct url.

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4.10

### Steps To Reproduce:
1.) Setup http://docs.apiato.io/getting-started/installation/
2.) Setup Valet on MAC, https://laravel.com/docs/8.x/valet#introduction
3.) Update the env file to folder-name uri
4.) Make POST Request

**Comment by Elshaden** [comment]
The POST method is not supported.
check that you are using the correct header as per the docs.
check that the url is not https

--header 'accept: application/json' \
  --header 'content-type: application/x-www-form-urlencoded' \
