### ISSUE TITLE
ServiceProvider generator always generates MainServiceProvider stub

### ISSUE THREAD

**Issue by darkons** [apiato/apiato#593]
### Description:
When using apiato:generate:serviceprovider command and choose Generic a MainServiceProvider is generated.

### Expected Behavior:
Generate Generic service provider

### Additional Context:
Nothing

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.2.34

### Steps To Reproduce:
Run apiato:generate:serviceprovider command and choose Generic stub.

**Comment by Mohammad-Alavi** [comment]
Fixed in v10
