### ISSUE TITLE
Pagination Does not working

### ISSUE THREAD

**Issue by PenSereyOtdom** [apiato/apiato#594]
### Description:
I had some problems with the pagination function. I can not use limit=0 and some of the function I cannot even use limit=1
Ex:  public function run()
    {
        return $this->repository->where('confirmed','!=','cancel')->paginate();
    }

in this function, I cannot use pagination function in endpoint like (applies?limit=0 or limit= 3)  
but in the function i can use limit = 1 or 3 but not limit = 0
public function run()
    {
        return $this->repository->paginate();
    }
event I try to change it in env file and also go to change directly in repository.php(ship/Configs) it still the same it not working evening I try to use PAGINATION_LIMIT_DEFAULT = 10 it not working I always show 15 data.

### Expected Behavior:
when i use PAGINATION_LIMIT_DEFAULT = 10 i expected the data return is 10 but is not 10 is show 15 and when i use PAGINATION_SKIP=true i expected that i can use ?limit=0 and i show all data but not is how only 15 data
### Additional Context:
<img width="605" alt="Screen Shot 2020-12-02 at 7 23 38 PM" src="https://user-images.githubusercontent.com/24617191/100872167-f6e6d980-34d3-11eb-9d74-c208906541b9.png">
<img width="313" alt="Screen Shot 2020-12-02 at 7 23 43 PM" src="https://user-images.githubusercontent.com/24617191/100872171-f8b09d00-34d3-11eb-8289-9c064148b5b2.png">
<img width="291" alt="Screen Shot 2020-12-02 at 7 23 49 PM" src="https://user-images.githubusercontent.com/24617191/100872174-f9493380-34d3-11eb-8fce-8bab56be83cf.png">
<img width="662" alt="Screen Shot 2020-12-02 at 7 24 03 PM" src="https://user-images.githubusercontent.com/24617191/100872176-f9493380-34d3-11eb-937f-6cacf422a4a2.png">

### Versions:
- Apiato Version: v1.0.1 
- PHP Version: ^7.2.5

**Comment by miladkian** [comment]
When you use ->where() function, the repository return Eloquent model and the paginate method called from the Eloquent, not repository! so the limit params does not applied.
To fix this issue you should use criteria instead where function. 
The [criteria](http://docs.apiato.io/components/criterias/) explained in Apiato documentation. you should define a criteria for filtering confirmed column and call it inside your task.
