### ISSUE TITLE
Get Personal Access Token with new Registration.

### ISSUE THREAD

**Issue by Elshaden** [apiato/apiato#596]
### Description:
In the docs, it says that after user is registered , it automatically issue personal access token and sent back in the response.

"This will registered new Users and generates Personal Access Tokens and respond with user object and token"

### Expected Behavior:
get personal access token for new registered user

### Additional Context:
nothing, not new personal access token is registered in the Database, and you don't get it in the response

another question , I get Personal Access by using the cli, but what role and permissions are set for the access token.? it is not related to any user.

### Versions:
- Apiato Version: 9
- PHP Version:7.2

### Steps To Reproduce:
1. Go to  "http://api.apiato.test/v1/register"

**Comment by Mohammad-Alavi** [comment]
Docs has been [updated](http://docs.apiato.io/features/user-registration/) to clarify this.
