### ISSUE TITLE
Upgrade to Laravel 8 or how could I do it manually

### ISSUE THREAD

**Issue by quarkmarino** [apiato/apiato#598]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the latest features of laravel 8 in an apiato project

**Describe the solution you'd like**
Is there any current plans to upgrate apiato to require laravel 8, or is there a manually way to upgrade the requirement correctly.

**Describe alternatives you've considered**
I'v already tried to upgrade the dependencies in the the compose.json of a fresh apiato installation, but I got stuck on messages like "Can only install one of:" specially with the "fruitcake/laravel-cors", where I specified the "^2.0" in my composer.json (not sure yet if resolving this will result on more errors or that will solve the requirements upgrade)

Thank you.

**Comment by Mohammad-Alavi** [comment]
Yes, we are going to overhaul Apiato in 1st quarter of 2021.
One of the things we are going do is Upgrade to latest Laravel version at that time.

Any PRs is appreciated 👓

**Comment by parse-code** [comment]
@Mohammad-Alavi if you can consider add plugin system to apito, it will be very awesome.

**Comment by GigiArteni** [comment]
I have managed to upgrade through composers files here `https://github.com/GigiArteni/apiato`
The errors I have found so far are related to PHPUnit tests. Tests are using Factory - factories are the major changes in Laravel 8.
If @Mohammad-Alavi can give use some hints from where to start in changing the factories loader and add factory generator - maybe we all, that we love this tool, can contribute :)

**Comment by Mohammad-Alavi** [comment]
@GigiArteni I am on a heavy crunch this days and cannot help you in this matter right now but we will focus on working on Apiato and resolve issues again once I find a little more time. (Soon)

**Comment by Jedliu** [comment]
> I have managed to upgrade through composers files here **https://github.com/GigiArteni/apiato**
> The errors I have found so far are related to PHPUnit tests. Tests are using Factory - factories are the major changes in Laravel 8.
> If @Mohammad-Alavi can give use some hints from where to start in changing the factories loader and add factory generator - maybe we all, that we love this tool, can contribute :)

Not sure if this package would do some help.
This package provides support for the previous generation of Laravel factories (<= 7.x) for Laravel 8.x+.
[https://github.com/laravel/legacy-factories](url)

**Comment by GigiArteni** [comment]
@Jedliu Thanks! I have investigated that package but, in my view will be better to use L8 as in the future can be easily upgraded to, let's L9 and so on.

**Comment by GigiArteni** [comment]
Hi guys, any news on this?

**Comment by Mohammad-Alavi** [comment]
v10 with Laravel 8 Support will come out around mid March.
