### ISSUE TITLE
Target [Lcobucci\JWT\Parser] is not instantiable while building [Laravel\Passport\Http\Controllers\AccessTokenController].

### ISSUE THREAD

**Issue by dimitribocquet** [apiato/apiato#606]
### Description:
I created a fresh project, to try Apiato.
I got few small bugs (especially because of composer 2), but after reading few issues it's OK and running well.
Then I run the command `php artisan route:list` to see all existing routes, and the following error is displayed:

`Target [Lcobucci\JWT\Parser] is not instantiable while building [Laravel\Passport\Http\Controllers\AccessTokenController].`

### Expected Behavior:
It should display all registered routes.

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4.12

### Steps To Reproduce:
1. Create a fresh project
2. Install everything
3. Run the command `php artisan route:list`

**Comment by Mohammad-Alavi** [comment]
This issue is fixed in v10 which hopefully will be released soon.

**Comment by Mohammad-Alavi** [comment]
Fixed in v10
