### ISSUE TITLE
Support composer 2

### ISSUE THREAD

**Issue by livevasiliy** [apiato/apiato#612]
### Description:
Cannot use apiato with composer 2. The problem in using dependency packages `composer-merge`

![image](https://user-images.githubusercontent.com/15705591/109430583-2d6cbb80-7a13-11eb-90e3-459c59e68af1.png)

### Expected Behavior:
Except for successful install.

### Additional Context:
-
### Versions:
- Apiato Version: 9.0
- PHP Version: 7.4.5

### Steps To Reproduce:
1. Clone or install via composer package or create the project via composer 
2. input `composer install`

**Comment by miobit** [comment]
same issue... 
![image](https://user-images.githubusercontent.com/8502205/109586066-e19a3f00-7b04-11eb-9a4b-ab6242346453.png)

**Comment by Mohammad-Alavi** [comment]
This is fixed in the upcoming v10. It will be released in less than a week.

**Comment by anatolygerasimov** [comment]
Hi all,  Could you provide change list of v10?

**Comment by Mohammad-Alavi** [comment]
Some of the changes are:

Updated to Laravel ^8.0.0
Required PHP is now ^7.4|^8.0
Update to composer v2
All pkgs are now using their latest version
All stubs used in code generations are updated
Enabled Laravel package auto discovery feature (it was causing problems in previous versions)
Fixed a bug were configs were not loaded correctly
Apiato core is extracted from Ship layer to its own repo
Almost all reported issues are fixed.

**Comment by miobit** [comment]
Excellent! Ill try tonight. I think this issue Can be closed

**Comment by Mohammad-Alavi** [comment]
v10 branch is still WiP. PR's are welcome 😄
