### ISSUE TITLE
No Environment Variable Available in Command

### ISSUE THREAD

**Issue by ikkysleepy** [apiato/apiato#618]
### Description:
Don't have access to the Environment Variables when running a command   This is using vagrant setup and after clearing cache.

### Expected Behavior:
Have access to environment variables when executing a CLI command.

### Additional Context:
This does not work on SHIP\Commands Hello World Example as well. 

### Versions:
- Apiato Version: Lastest
- PHP Version: 7.2.*

### Steps To Reproduce:
1. Create a New Project
2. Add this line to your Welcome Command file,SayWelcomeCommand.php
```
        echo env('APP_NAME');
```
3. Try to run the command , after you ssh into vagrant.
```
 php artisan apiato:welcome
```

**Comment by Mohammad-Alavi** [comment]
I cant reproduce this.
`php artisan apiato:welcome` works fine for me.

**Comment by ikkysleepy** [comment]
I had to run this command:

```
php artisan config:clear
```

To fix the issue.
