### ISSUE TITLE
Including Null Transformer 

### ISSUE THREAD

**Issue by ikkysleepy** [apiato/apiato#626]
### Description:
Including Null Transformer not working on Apiato 10

### Expected Behavior:
This was working on Apiato 9

```
  public function includeAnalysis(Project $project) {
        if($project->analysis_id ) {
            return $this->item($project->analysis, new AnalysisTransformer());
        }
        
        return;
    }
```
Error:

```
return value of Apiato\Core\Abstracts\Transformers\Transformer::callIncludeMethod() must implement interface League\Fractal\Resource\ResourceInterface, bool returned
```

if I just have the method always try to transform with null data then I get this error:
```
Argument 1 passed to App\Containers\Koritsu\Analysis\UI\API\Transformers\AnalysisTransformer::transform() must be an instance of App\Containers\Koritsu\Analysis\Models\Analysis, null given, called in /home/vagrant/code/koritsu-www/vendor/league/fractal/src/Scope.php on line 419
```

### Additional Context:
So I have users -> projects -> analysis  (1-1) -> alternative_analysis (1- many)

### Versions:
- Apiato Version: 10
- PHP Version: 7.4

### Steps To Reproduce:
1. Try to Add a related item that does not yet exist yet
2. See the error

**Comment by Mohammad-Alavi** [comment]
I don't understand, why anyone try to add **Try to Add a related item that does not exist yet**? Could you please explain more?

**Comment by Mohammad-Alavi** [comment]
I have found the problem, ill fix it in the next rc.

**Comment by Mohammad-Alavi** [comment]
I think it is [fixed](https://github.com/apiato/core/commit/56367b8270b2d8bec64f10b828e3687aed670a59). Could you please `composer update` and confirm it?

**Comment by ikkysleepy** [comment]
Ok, that seemed to work. 

I guess I didn't need the trailing return statement. 

Regarding the fix, I think before in version 9 I would get a blank object 
````
"updated_at": "2021-04-20T06:54:10.000000Z",
"analysis":{"data":{}}
````

and now I don't get that object if it does't exist. 
````
"updated_at": "2021-04-20T06:54:10.000000Z",
````

Not a big deal, but noticed it. I'll just update my front end to check if that object exist or not yet.

Here is some context, I have a Job that needs to generate an analysis, which can take several minutes to complete, so I will get several request before the relationship is created. 


Thanks,
-- Jorge
