### ISSUE TITLE
CamelCase not Supported in Model 

### ISSUE THREAD

**Issue by Elshaden** [apiato/apiato#630]
### Description:
When The Model name is camel case, like NewItem, the database table is created as newitems, but when you try to call any query from a related Model, the table named as new_items.

if you try to use the relation function without specifying the table, you get error result. as the laravel will try to find the camelCase model class as new_items. 

Easy to fix by declaring protected $table="newitems" in the model, and will work. 

this should not be the case.  
### Expected Behavior:
the migration generator should create table as new_items. to fix the problem.
so that we don't have to name the table in the model.
 
### Versions:
- Apiato Version: 10.0.3
- PHP Version: 8.#.#

**Comment by Mohammad-Alavi** [comment]
It is a core related bug and is fixed now. run a composer update to get this fix.
