### ISSUE TITLE
Request Default Support for Laravel Sanctum.

### ISSUE THREAD

**Issue by brunoalfred** [apiato/apiato#634]
**Requesting the support for Laravel Sanctum for small / Medium sized projects**

[Ref](https://laravel.com/docs/8.x/sanctum) - As its recommended for simplicity in designing of Auth Service.

**Comment by Mohammad-Alavi** [comment]
We don't have plan to do this atm.

**Comment by Elshaden** [comment]
@Mohammad-Alavi  @brunoalfred 
I made Apiato work with Sanctum, fairly easy.
the main problem is the HasApiTokens trait , you cannot use Passport and Sanctum at the same time.
if you go ahead and install sanctum package in main app or in any container, and change the HasApiToken Trait to use the sanctum one, every thing works just fine..
But you loose all the Passport Features.. 

Maybe if I have time I will make a pull request to give you a choice if you want to install Passport or Sanctum when you first install Apiato..
