### ISSUE TITLE
Powerjoin memory exhausted

### ISSUE THREAD

**Issue by vikramsra** [apiato/apiato#639]
### Description:
I did a fresh installation as mentioned in the documentation. We have created multiple container and all is fine. We installed powerjoins https://github.com/kirschbaum-development/eloquent-power-joins  and while using it we received following error

`{
    "message": "Allowed memory size of 536870912 bytes exhausted (tried to allocate 266342400 bytes)",
    "exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
    "file": "C:\\laragon\\www\\mispune\\app\\Containers\\AppSection\\Container\\UI\\API\\Controllers\\Controller.php",
    "line": 85,
    "trace": []
}`

Regular join queries work fine, we have used additional composer packages without any issue. We only have 2 rows in DB

### Expected Behavior:
We should be able to use the package without issue as the package is working fine when we installed it on vanilla laravel

### Versions:
- Apiato Version: 10.0.0
- PHP Version: 8.0.7

### Steps To Reproduce:
composer create-project apiato/apiato my-api

1. cd my-api
2. composer update
3. php artisan migrate
4. php artisan db:seed
5. php artisan apiato:permissions:toRole admin
6. php artisan passport:install
7. composer require kirschbaum-development/eloquent-power-joins
8. Try any join query using PowerJoin
Please let me know in case if I am missing something

**Comment by Mohammad-Alavi** [comment]
Is this issue still persist?

**Comment by vikramsra** [comment]
Yes, it will be great if this tool work as this is very helpful.

**Comment by Mohammad-Alavi** [comment]
@vikramsra It would be awesome if you could pinpoint the source of the problem or create a PR. It would be harder for me to fix as I am not familiar the the mentioned package.

**Comment by vikramsra** [comment]
I will try that will update you. I am closing the issue but will comment on the same about my findings
