### ISSUE TITLE
How we know data come from redis cache or not?

### ISSUE THREAD

**Issue by rockers007** [apiato/apiato#640]
**Is your feature request related to a problem? Please describe.**
No,I want to know how redis cache use with Tasks

**Describe the solution you'd like**
I want to know how redis cache use with Tasks

**Describe alternatives you've considered**
I want to know how redis cache use with Tasks

**Additional context**
I have redis server .I want to know how redis cache use with Tasks .

**Comment by Mohammad-Alavi** [comment]
I have not used any caching with Apiato yet but I am going to dive deep into it in the following week or on after that. I'll tell you what I find and I will update the docs if needed.

**Comment by rockers007** [comment]
thank you so much

**Comment by rockers007** [comment]
@Mohammad-Alavi : waiting for update
Thank you

**Comment by yalsicor** [comment]
@rockers007 Your question is not very specific. What are you asking?

Caching is actually not a thing of apiato, but Laravel. Have a look at Laravel caches: https://laravel.com/docs/9.x/cache
