### ISSUE TITLE
Api Versioning

### ISSUE THREAD

**Issue by Aliakbari1994** [apiato/apiato#650]
Hi,
my system version is as follows:
1-   Web App version (one version): /web
2-   Android version (including special versions of Android): /android/v1 ...
3-   IOS version (including special versions of IOS):  /ios/v1 ...
...
And how can I handle the version with this format: v1.0.2 

How can I separate the api versions for different devices and also not have problems in Generation Document?

**Comment by pishguy** [comment]
@Aliakbari1994 why you don't define special routes?

**Comment by Aliakbari1994** [comment]
@pishguy What is the best structure you can suggest for special routes?

**Comment by moslem-deris** [comment]
1- REST api must be designed independently, not knowing what kind of platform is calling routes! So having `/ios` or `/android` routes is a very bad practice!
2- Api versioning uses integers, So we have v1, v2, v3, etc. There is no v1.0.2 in api versioning.
