### ISSUE TITLE
Routes priority

### ISSUE THREAD

**Issue by Aliakbari1994** [apiato/apiato#657]
I have an issue which I'm stuck for hours trying to resolve and didn't find a proper solution yet.

I have two routes:

/genres/trash    --->  hard-coded routes
/genres/{slug}

I need to prioritize routes in this way ( hard-coded routes first ), but since each route is in a separate file, I do not know how to prioritize.

How I'm suppose to give priority to last defined routes?

**Comment by yalsicor** [comment]
This is bad design imho.

You could distinguish by using singular on get single entity endpoint: /genre/{slug}

If you want to stick with it, the order on which the route files are loaded matters. I dont know the order, but maybe changing the name of the trash route to something before in alphabetic order will help?

**Comment by moslem-deris** [comment]
What you want is actually possible in laravel, when you put all the routes in a single file the order matters and can save you!
But as you know here in Apiato this is not possible to do it.
As yalsicor just mentioned this is a very bad pattern and the best way of getting rid of it is to solve the conflict between your routes!

**Comment by momadthenomad** [comment]
You can just use regex to restrict the routes:

```
Route::get('/genre/{slug}', [
    'uses' => 'Controller@getGenre'
])->where('slug', '[a-z0-9-]{10,32}');
```

Now `trash` is less than 10 characters so it will skip slug and go to trash. I typically use this for distinguishing between `/users/{id}` and `/users/new` so I restrict the `/users/{id}` to numeric and it has no problem finding `/users/new`.
