### ISSUE TITLE
Tests: $auth = false doesn't seem to work as excepted

### ISSUE THREAD

**Issue by TZK-** [apiato/apiato#660]
### Description:

I'm trying to add an API functional test in which I need to be unauthenticated.

After reading the test documentation, I've found that I need to use the property `$auth = false` for this.

But it does not seem to work. I am still getting HTTP success code rather than a 401 code.

I tried to understand how `$auth` is working during `makeCall` method call.

What I found is during the `makeCall` call, it always creates a new user (via `getTestingUser`) and this method finally calls `actingAs($user)` in `Apiato\Core\Traits\TestsTraits\PhpUnit\TestsAuthHelperTrait:88` without taking consideration about `$auth` nor `$overrideAuth`.

So it always acts as an user, and the test is ran as authenticated.

Didn't I understand the documentation well or is there really a problem ?

### Versions:
- Apiato Version: 10.0.0
- PHP Version: 8.1.1

**Comment by Mohammad-Alavi** [comment]
That is intresting. I just used it today and it seemed to wrok 🤔

**Comment by Mohammad-Alavi** [comment]
Ill have a better and ore intuitive way of doing this later but for now you can use this trick:

```
    public function testGetAuthenticatedUser_ByUnauthenticatedUser(): void
    {
        $this->testingUser = User::factory()->create();

        $response = $this->auth(false)->makeCall();

        $response->assertStatus(401);
    }
 ``` 
 
 Note that you need to set the `$this->testingUser` to a new user or else Apiato creates an `authenticated` User automatically.
