### ISSUE TITLE
Move existing laravel project into apiato

### ISSUE THREAD

**Issue by sajjad30sakhti** [apiato/apiato#661]
Apiato is great for large scale projects. I have a project written in laravel and I want to migrate to apiato,
i'm seeking for some ways to convert my project into a section or container in apiato.

**Comment by Mohammad-Alavi** [comment]
Awesome! Welcome to Apiato.
So what is your problem while migrating? It should be that hard 🤔

**Comment by mderis** [comment]
I close this issue due to inactivity.
Anyways we can continue this discussion in [apiato discord](https://discord.gg/vVUahP7rkQ)

**Comment by mderis** [comment]
I close this issue due to inactivity.
Anyways we can continue this discussion in [apiato discord](https://discord.gg/vVUahP7rkQ)
