### ISSUE TITLE
apiato:apidoc is not generating document ,throw error

### ISSUE THREAD

**Issue by rockers007** [apiato/apiato#662]
### Description:
We are getting error when php artisan apiato:apidoc

Error Output:

   Symfony\Component\Process\Exception\ProcessFailedException

  The command ""node_modules/.bin/apidoc" -c "app/Containers/Vendor/Documentatio
n/ApiDocJs/public" -f public.php -i app -o "app/Containers/Vendor/Documentation/
UI/WEB/Views/documentation/public" --single" failed.

Exit Code: 1(General error)

Working directory: D:\dockers\apiato

Output:
================

Error Output:
================
[error] Invalid option: --config/-c must be a path to a file. Directory provided
.

### Versions:
- Apiato Version: 10.x (latest)
- PHP Version: 8.0

### Steps To Reproduce:
1. Go to php artisan apiato:apidoc

**Comment by Mohammad-Alavi** [comment]
@rockers007 Which version of Apidoc u are using?

**Comment by rockers007** [comment]
"apidoc": "^0.50.4"

**Comment by Elshaden** [comment]
Hi
I am getting the same error, any fix?

**Comment by Elshaden** [comment]
Ok 
You need to change the line in  ' DocsGeneratorTrait ' 
```
        return 'app/Containers/' . config('vendor-documentation.section_name') . '/Documentation/ApiDocJs/' . $type ;

```

to

```
        return 'app/Containers/' . config('vendor-documentation.section_name') . '/Documentation/ApiDocJs/' . $type .'/apidoc.json';

```

This should do it.
