### ISSUE TITLE
Register New User is missing in Version 11.

### ISSUE THREAD

**Issue by Elshaden** [apiato/apiato#676]
### Description:
Register and create a new User route, controller, action and task are missing in version 11
### Expected Behavior:
expected to be as in version 10
### Versions:
- Apiato Version: 11.*

**Comment by Mohammad-Alavi** [comment]
`Regiser User` functionality is moved to `Authentication` Container.

**Comment by Elshaden** [comment]
Hi Thanks for the upgrade, real nice.
However, is moving the User Actions to Authentication Container necessary. this will cause major breaking change for many add on containers. 
if there is no major requirement to be this way, may I advise to keep it in the User container for consistency and the real separation of concerns. 
After All all new comers to Apiato will learn how to use it by looking to the provided examples in the User container as it includes most if not all of the functionality of a typical Apiato container.

**Comment by Mohammad-Alavi** [comment]
@Elshaden Sure, your welcome! I am very exicted for this release too!

Here is my reasoning for this changes: 

> if there is no major requirement to be this way, may I advise to keep it in the User container for consistency and the real separation of concerns.

The registering action is actually related to the `authentication` and by moving it there we put this responsibility where it should be.
We have already something like this in `authorization` container where `roles` and `accesses` are managed `by` the container `using` the User.

> After All all new comers to Apiato will learn how to use it by looking to the provided examples in the User container as it includes most if not all of the functionality of a typical Apiato container. That's how I learnt Apiato.

Yes, this is the way I learned it too and I am really trying to keep it as simple as possible and put as many examples as I can at least in the default containers.

What do you think. I am really open to this kind of discusstions.

**Comment by Mohammad-Alavi** [comment]
@mderis @yalsicor What do you think? Can you jump into this discussion if you have some free time?
