### ISSUE TITLE
Upgrade to Laravel 9

### ISSUE THREAD

**Issue by Aliakbari1994** [apiato/apiato#679]
Hello . How can I upgrade Laravel version of my project to 9? When will the new version of APIATO come with Laravel 9?
(how to use v11.2.0 with composer update - php 8.1)

**Comment by Mohammad-Alavi** [comment]
Hey. Apiato v11 is already released with Laravel 9 support.
`composer create-project apiato/apiato my_apiato_dir 11.2`

**Comment by Aliakbari1994** [comment]
> Hey. Apiato v11 is already released with Laravel 9 support. `composer create-project apiato/apiato my_apiato_dir 11.2`

Thanks, Please update website and documents.
