### ISSUE TITLE
APIATO create-project command guzzlehttp issue

### ISSUE THREAD

**Issue by black-code1** [apiato/apiato#687]
I am trying to create apiato project with `composer create-project apiato/apiato lara-apiato`
I am getting this error 
![Screenshot from 2022-08-31 14-02-36](https://user-images.githubusercontent.com/31560529/187684998-c608158f-918d-4d89-83ae-439a53fbbee6.png)

I ran this command `composer create-project apiato/apiato lara-apiato -W` it didn't solve the issue.
I ran `composer clear-cache` still getting the same issue.
I ran `composer global remove guzzlehttp/guzzle` still getting the same issue.
I ran `composer update` still getting the same issue.
I **removed composer** completely and install it but i still get the same issue.
I use **apiato installer** but i still get the same issue.
I check on stackoverflow, i got no solution.

Please need help.

Here is the OS i am trying to create the project on.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by mderis** [comment]
Try removing `composer.lock` file ,then run `composer update`.

**Comment by isudakoff** [comment]
Hello! Issue still exists.

@mderis Your advice helped to me, but this process looks broken to me :)
