### ISSUE TITLE
Add Laravel 10 support

### ISSUE THREAD

**Issue by mlutsiuk** [apiato/apiato#704]
Add Laravel 10 support
Currently Apiato requires
`"laravel/framework": "^9.2",`

So after upgrade to Laravel 10 composer update throws
`apiato/core[v7.2.0, ..., v7.2.5] require laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.4] but it conflicts with your root composer.json require (^10.0).`

**Comment by Mohammad-Alavi** [comment]
Yes, there is a lot more to upgrading Apiato to Laravel 10 than just bumping a package version.

**Comment by Aliakbari1994** [comment]
When will version 12 be released with Laravel 10?

**Comment by Mohammad-Alavi** [comment]
@Aliakbari1994 I don't know tbh. I started working on it 2 month ago but couldn't find the time to finish it.

**Comment by febelery** [comment]
wait for Laravel10 version to upgrade my software

**Comment by Aliakbari1994** [comment]
How much of this project has been completed and when will it be released?

**Comment by Aliakbari1994** [comment]
@Mohammad-Alavi  How much of this project has been completed and when will it be released?

**Comment by Mohammad-Alavi** [comment]
@Aliakbari1994 I just released Apiato v12 with Laravel v10 support.
