### ISSUE TITLE
how to handle relationship

### ISSUE THREAD

**Issue by Aliakbari1994** [apiato/apiato#712]
If containers' models from two different sections want to have a relationship with each other, how should I handle this issue?

**Comment by Mohammad-Alavi** [comment]
@Aliakbari1994 Models in different Sections should not have direct dependency on other models outside of a Section.

To understand Sections better, read about `Bounded Context` in `Domain Driven Design`. A Section essentially is a Bounded Context.

**Comment by Aliakbari1994** [comment]
Thanks, If the user is in one section, I can have a user_id in a model in another section. Should I use events to fill this field?

**Comment by Mohammad-Alavi** [comment]
@Aliakbari1994 Yes 😎
