### ISSUE TITLE
Why i  am getting "Welcome to Apiato" message even after specifying route end point

### ISSUE THREAD

**Issue by Abs-vedantt** [apiato/apiato#721]
http://localhost/public/v1/createorders this is my URL for create order Api, but I am getting **"welcome to apiato"** message. This message usually comes if my route is like this "http://localhost/public/v1/ ".

But i am getting this message even after specifying the api endpoint. Why it is like this i ma not able to understand.

i have setup my apiato on my local computer. i have changed the hosts and vhosts file as it was mentioned. Sometimes my api works. Some time it gives me a Welcome to Apiato message.

Help me out , if you have any idea about this...

Thanks And Regards, Vedant.

**Comment by Mohammad-Alavi** [comment]
Can you try to call your api domain instead of `localhost`? e.g., `api.apiato.test/v1/yourendpoint`
Notice the `api.` subdomain.

Or are you using the a api prefix? In this case `public`?
