### ISSUE TITLE
apiato:apidoc command throw ProcessFailedException Error

### ISSUE THREAD

**Issue by pedram-shariat** [apiato/apiato#722]
When I use the apidoc command, I get the following error
`
Error Output: 

   Symfony\Component\Process\Exception\ProcessFailedException 

  The command ""node_modules/.bin/apidoc" -c "C:\laragon\www\reemod-api\app\Containers/Vendor/Documentation/ApiDocJs/C
onfigs/apidoc.public.json" -f public.php -i app -o "app/Containers/Vendor/Documentation/UI/WEB/Views/documentation/pub
lic" --single" failed.

Exit Code: 1(General error)

Working directory: C:\laragon\www\reemod-api

Output:
================

Error Output:
================
ENOENT: no such file or directory, stat 'C:\laragon\www\reemod-api\app\Containers/Vendor/Documentation/ApiDocJs/Config
s/apidoc.public.json'

  at app\Containers\Vendor\Documentation\Tasks\GenerateAPIDocsTask.php:37
     33▕         $process->run();
     34▕
     35▕         if (!$process->isSuccessful()) {
     36▕             $console->error('Error Output: ' . $process->getOutput());
  ➜  37▕             throw new ProcessFailedException($process);
     38▕         }
     39▕
     40▕         // echo the output
     41▕         $console->info('[' . $type . '] ' . implode(' ', $command));

  1   app\Containers\Vendor\Documentation\Actions\GenerateDocumentationAction.php:35
      App\Containers\Vendor\Documentation\Tasks\GenerateAPIDocsTask::run("public", Object(App\Containers\Vendor\Docume
ntation\UI\CLI\Commands\GenerateApiDocsCommand))

  2   [internal]:0
      App\Containers\Vendor\Documentation\Actions\GenerateDocumentationAction::App\Containers\Vendor\Documentation\Act
ions\{closure}("public")
`

what's the solution?

**Comment by Mohammad-Alavi** [comment]
@pedram-shariat Could you please tell your Apiato, Documentation container & ApiDocJs versions?

**Comment by pedram-shariat** [comment]
apiato version : 12.0.0
Documentation container : 3.0.0
apidoc: 1.0.0

**Comment by Mohammad-Alavi** [comment]
@pedram-shariat What is your OS?

Try to create the `Config` folder at `app/Containers/Vendor/Documentation/ApiDocJs/` and rerun the command.

Please tell me if this fixes your problem so I can develop a fix later. 🙏

**Comment by pedram-shariat** [comment]
Windows 10
`Configs` folder exists in this path

**Comment by Anas-Nabulsi** [comment]
I'm facing same issue here

**Comment by Mohammad-Alavi** [comment]
I just [released](https://github.com/apiato/documentation-generator-container/releases/tag/v3.0.4) a possible fix based on @yalsicor findings but I cannot test it because I am using WSL.
@Anas-Nabulsi could you please do a `composer update` and see if it is fixed?
Thanks.

**Comment by Anas-Nabulsi** [comment]
@Mohammad-Alavi 
Now I'm receiving the following error:
`
file_put_contents(/C:\Users\APP_PATH\app\Containers\Vendor\Documentation\ApiDocJs\Configs\apidoc.public.json): Failed to open stream: No such file or directory

  at app\Containers\Vendor\Documentation\Tasks\RenderApidocJsonTask.php:85
     81▕             if (!is_dir($dir) && !mkdir($dir)) {
     82▕                 throw new \RuntimeException(sprintf('Directory "%s" was not created', $dir));
     83▕             }
     84▕         }
  ➜  85▕         file_put_contents("{$dir}/{$file}", $contents);
     86▕     }
     87▕ }
     88▕

  1   app\Containers\Vendor\Documentation\Tasks\RenderApidocJsonTask.php:85

  2   app\Containers\Vendor\Documentation\Tasks\RenderApidocJsonTask.php:62
      App\Containers\Vendor\Documentation\Tasks\RenderApidocJsonTask::fileForceContents("", "{"name":"apiato","description":"apiato (Public API) Documentation","title":"Welcome to apiato","version":"1.0.0","url":"http:\/\/api.apiato.test","sampleUrl":"http:\/\/api.apiato.test","template":{"withCompare":true,"withGenerator":true},"header":{"title":"API Overview","filename":"Containers\/Vendor\/Documentation\/UI\/WEB\/Views\/documentation\/header.md"},"order":[]}")
`
note APP_PATH is just a placeholder for the actual app path.

There seem to be a missing file called apidoc.public.json and a missing folder called Configs.
I tried to create the folder Configs under ApiDocJs and an empty apidoc.public.json. 
But when I run php artisan apiato:apidoc again the file gets deleted and I receive the same error.
