### ISSUE TITLE
API Test Error: "The requested Resource was not found."

### ISSUE THREAD

**Issue by Xjodia** [apiato/apiato#727]
### Apiato Version

11.x

### PHP Version

8.2.13

### Database Driver & Version

MySQL 8.2

### Description

Hello everyone, I'm new to Apiato.
I have installed everything the docs instructed, but when I test the API with Postman, it always returns the error "The requested Resource was not found."
I have ran cmd `php artisan route:list --path=categories` and it returned:

```
  POST       api.apiato.test/v1/categories ................... App\Containers\AppSection\Category\UI\API\Controllers\Controller@createCategory
  GET|HEAD   api.apiato.test/v1/categories ................. App\Containers\AppSection\Category\UI\API\Controllers\Controller@getAllCategories
  DELETE     api.apiato.test/v1/categories/{id} .............. App\Containers\AppSection\Category\UI\API\Controllers\Controller@deleteCategory
  GET|HEAD   api.apiato.test/v1/categories/{id} ............ App\Containers\AppSection\Category\UI\API\Controllers\Controller@findCategoryById
  PATCH      api.apiato.test/v1/categories/{id} .............. App\Containers\AppSection\Category\UI\API\Controllers\Controller@updateCategory
```

When i tried `http://127.0.0.1:8000/api.apiato.test/v1/categories` or `http://api.apiato.test/v1/categories`, it only return `"message": "The requested Resource was not found.",`

**Here is my `.env` config**
```
APP_NAME="apiato"
APP_ENV=local
APP_KEY=base64:AzI3e1aFiv15K7vjvAc1hfPAKNW9DJG27NR6bKMEZgs=
APP_URL=http://apiato.test
API_URL=http://api.apiato.test
API_PREFIX=/
```

### Steps To Reproduce

![Screenshot from 2023-12-11 14-27-34](https://github.com/apiato/apiato/assets/91233284/170a60b1-6407-40a8-94e3-2cdbc76c5600)

**Comment by yalsicor** [comment]
Is your db setup correctly?

**Comment by Xjodia** [comment]
> Is your db setup correctly?

yes, i have setup mydb setup correctly. Btw I have a question, is' it true to run `php artisan serve `to start up Apiato?

**Comment by yalsicor** [comment]
If you are not running a proper webserver locally, `http://api.apiato.test:8000/v1/categories` would only work if you point the domain to 127.0.0.1, on Linux this would be in the /etc/hosts file.

**Comment by Xjodia** [comment]
> If you are not running a proper webserver locally, `http://api.apiato.test:8000/v1/categories` would only work if you point the domain to 127.0.0.1, on Linux this would be in the /etc/hosts file.

Bro you save me!!!
