### ISSUE TITLE
Invalid key supplied

### ISSUE THREAD

**Issue by altalya** [apiato/apiato#747]
### Apiato Version

12

### PHP Version

8.2

### Database Driver & Version

10.6.16-MariaDB-0ubuntu0.22.04.1

### Description

As per the installation doc, I've created the app and started laravel server with 
`php artisan serve`

But it throws below error even though I've regenerated keys, cleared all caches.
**Invalid key supplied**
![image](https://github.com/apiato/apiato/assets/65558158/affb0d99-57f6-49ec-9b55-27bb2fadd893)

`Invalid key supplied (View: example-app/app/Containers/AppSection/Authentication/UI/WEB/Views/home.blade.php) vendor/league/oauth2-server/src/CryptKey.php#67

Invalid key supplied
vendor/league/oauth2-server/src/CryptKey.php#67`

### Steps To Reproduce

1. Install the packages via composer
2. Configure database
3. Run DB Migrate & seeders
4. Regenerate keys and clear cache
5. Run localserver via artisan serve command

**Comment by m0nclous** [comment]
`php artisan passport:install` helped me

**Comment by polarikus** [comment]
I think this is more a request to add documentation, I also solve it with the `php artisan passport:install` command

**Comment by Mohammad-Alavi** [comment]
Thank you @m0nclous & @polarikus 
The docs are updated to mention this step now.
`php artisan passport:install`
