### ISSUE TITLE
IfAdmin not found

### ISSUE THREAD

**Issue by coalman11** [apiato/apiato#772]
### Apiato Version

12.0.0

### PHP Version

8.3.11

### Description

![image](https://github.com/user-attachments/assets/2d823d8f-17a8-4169-9dee-c6cf0701b2be)

ifAdmin cannot be found, seems like the code generator needs to be updated.

### Steps To Reproduce

- Add new container/transformer
- Transformer has ifAdmin method but shows error

**Comment by Mohammad-Alavi** [comment]
This is fixed in the [Core v8.15](https://github.com/apiato/core/releases/tag/v8.15.0).
