### ISSUE TITLE
Feature: Support Swagger

### ISSUE THREAD

**Issue by nhazdun** [apiato/apiato#90]
Swagger gives possibility easy import into Postman his collections.

**Comment by Mahmoudz** [comment]
Yes I'm aware of the power of Swagger. I prefer supporting both tools, letting users specify the tool he wants to use for each project from a config file.

**Comment by jjag3r** [comment]
Any updates about this feature?

**Comment by johannesschobel** [comment]
i don't think someone implemented it.. at least it is not aavailable here in `apiato/apiato`. But you may need to change the `Documentation` container accordingly..

**Comment by jjag3r** [comment]
ok, I'll see what can I do. Thanks

**Comment by jjag3r** [comment]
APIDocJS it's not developing anymore and that's the main problem.
Currently, I need to add some links to the other parts of the documentation. Also, my documentation is really big and it's started to work slowly with one-page documentation. 

I don't know yet how much time will take me. Will see :)

**Comment by johannesschobel** [comment]
maybe you can keep me updated on this? ;) perhaps we can switch from apidocjs to swagger?

**Comment by jjag3r** [comment]
I will, no problem :) I will notify you on Slack.

**Comment by jebraieili** [comment]
Hi, Any updates about this feature?

**Comment by johannesschobel** [comment]
Hey there..
Yeah, i have indeed read the new OpenApi (swagger 3) specs and found it quite difficult to use this in Laravel applications.. S3 requires extensive annotations on models and controllers..

For example it requires you to explicitly specify all attributes of a model, which is - kind of - not "Laravelish"..

**Comment by jebraieili** [comment]
thanks
